











                               CELLULAR


                    Original Story and Screenplay

                                  by

                             Larry Cohen




















                               CELLULAR


        FADE IN:

        EXT. LOS ANGELES, CALIFORNIA - AERIAL SHOT - DAY

        Flying low over the massive sprawl of the city.

                                 NARRATOR
                     There are 2,762,500 cellular
                     phones currently operating in the
                     county of Los Angeles.

        QUICK CUTS

        Local citizens on their cellulars.

        A BUSINESSMAN IN A CROWDED RESTAURANT - simultaneously
        devouring his lunch and conducting a heated negotiation over
        his cellular.

        CAMERA PANS THE RESTAURANT

        A pretty woman at the next table also on her cell phone.
        And beyond two more on theirs.  Half the restaurant seems to
        be talking and eating at the same time.

        Even the waiter is in the corner anxiously taking a call
        from his agent.

                                 NARRATOR
                     Forty percent of all households in
                     the city utilize one or more
                     cellular devices.

        EXT. DOWNTOWN L.A. STREET

        A teenager on a skateboard weaves through traffic while
        chattering on the phone.

        He whips past numerous motorists at the light who are
        likewise engaged in conversation.

        OVER THIS:  OPENING CREDITS APPEAR

        EXT. THE BALL PARK - DAY

        The crowd cheers as the Dodgers score a base hit -- except
        for those who are too busy on the phone to notice.

        INT. DARKENED MOVIE THEATE

        Packed with customers.  At the crucial dramatic moment
        someone's cell phone goes off.  The audience voices its
        disapproval, hooting as the owner of the offending device
        dashes up the aisle to the lobby.

        EXT. THE BEACH - DAY

        Gorgeous sun worshippers -- and many of them glued to their
        telephones.

        One couple mouth to mouth in an embrace, oblivious to all
        around them -- until a cell phone rings.  They immediately
        terminate their lovemaking -- both of them reaching for
        their cellular at the same moment.  Nobody can afford to
        miss a call.

                                 NARRATOR
                     An estimated 200 new units are
                     being added each day.

        CREDITS CONTINUE

        INT. MEN'S ROOM

        A long line of gentlemen at the urinals.  And one of them
        using his free hand to punch up a number.

        EXT. BEVERLY HILLS - HIGH SCHOOL - DAY

        As the students swarm out, immediately switch on their cell
        phones and launch into an update of the day's events.

        INT. A LAP DANCING CLUB

        As a frustrated young lady vainly tries to attract the
        attention of her middle aged client by giving it her all --
        only to find him oblivious to her charms and entirely
        focused on his cellular call.

        Despite the proximity of her bare breasts and the thrashing
        of her long auburn hair across his face there is no
        response.  It's as if she's not even there.

        HIGH ANGLE - ABOVE THE CANYONS

        Perched here amidst the wilderness one of the giant dishes
        that relay thousands of calls to a satellite station in the
        sky.

        ON THE SOUND TRACK we HEAR a cacophony of overlapping voices
        -- idle babble -- crucial information -- and just plain
        talk, totally unintelligible -- which quickly begins to take
        on the quality of chirping insects -- as still more voices
        join in and the volume rises to virtually engulf us.

                                                       CUT TO BLACK:

        SILENCE ON SOUND TRACK

                                 NARRATOR
                     This is the story of 90 minutes in
                     the life of one cellular phone.

        FADE IN:

        EXT. CULVER CITY - DAY

        A convertible moves through afternoon traffic with its top
        down.  It's a 1995 Chrysler Sebring, colored maroon.

        INT. THE CAR

        MUSIC is BLARING.  It's vintage Tito Puente; "Cherry Pink
        and Apple Blossom White."

        THEO NOVAK is alone at the wheel.  He's handsome, a sharp
        dresser in his Imperio Armani suit and cashmere turtleneck.
        He seems to be enjoying the ride until the cell phone lying
        on the seat intrudes upon his privacy.

                                 THEO
                     What now?

        The caller I.D. on the cell phone reads "ANONYMOUS."

                                 THEO
                     Yeah, hello?

        There's a woman's voice on the line -- a voice choked with
        fear.  Not any voice he expected to hear.

                                 LENORE'S VOICE
                     Thank God -- thank God I've got
                     you.

                                 THEO
                     Who is this?

                                 LENORE'S VOICE
                     You mustn't hang up.

        PRODUCTION NOTE:  WE NEVER CUT TO THE OTHER END OF THE LINE.
        WE REMAIN WITH THEO AT ALL TIMES.

                                 THEO
                     Do I know you?

                                 LENORE
                     I've been trying to get someone --
                     anyone.  For hours ...

                                 THEO
                     If this is some sales pitch I'm
                     not buying --

                                 LENORE
                     You don't understand.

                                 THEO
                     No.  You don't understand!  You
                     caught me on my cellular on the
                     way to pick up some business
                     associates.  And I've got no time
                     to screw around.

                                 LENORE
                     Will you let me explain!

                                 THEO
                     And what're you whispering for?

                                 LENORE
                     I can't talk any louder.  They
                     might hear.

        Theo switches off the Latin CD so he can hear more clearly.

                                 THEO
                     Lady, try making some sense.

                                 LENORE
                     You may be our only chance.  I
                     don't know if I can do this again.

                                 THEO
                     What'd you do!  Just pick my
                     number out of the air?

                                 LENORE
                     They smashed the phone.  I've been
                     clicking the loose wires together
                     hoping it'd make a connection.

                                 THEO
                     Who smashed the phone?

                                 LENORE
                     They're holding my husband
                     downstairs.

                                 THEO
                     Sure.  And they left you upstairs
                     to make phone calls?

                                 LENORE
                     They gave me pills to make me
                     sleep.  They didn't realize how
                     much Seconal I'm used to -- that
                     I'd have so much tolerance --

                                 THEO
                     Well I'm not tolerant of being
                     bothered with this bullshit story
                     when I'm about to make the most
                     important score of my life.  This
                     has gotta be some "put-on," right?

                                 LENORE
                     I'm sorry.  I'm so sorry to do
                     this to you.

                                 THEO
                     You're not doing anything to me --
                     because -- listen to this
                     carefully -- I do not care.

                                 LENORE
                     I don't believe you.

                                 THEO
                           (laughs)
                     You're the one who's not to be
                     believed.

                                 LENORE
                     My name is --

                                 THEO
                     I don't want to know --

                                 LENORE
                           (persists)
                     My name is Lenore Oberfeld.

                                 THEO
                     Don't expect me to tell you who I
                     am.

                                 LENORE
                     I realize you don't want to be
                     involved.

                                 THEO
                     I am not involved.  Keep clicking
                     your little wires.  You'll get
                     someone else.  Good luck.

                                 LENORE
                     You won't disconnect.

                                 THEO
                     Oh won't I?

                                 LENORE
                     Because you know you'll be killing
                     us.

                                 THEO
                     Don't lay this on me!

                                 LENORE
                     Then hang up!  Do it!

        It's the total despair of these words that finally hooks
        Theo Novak.  He can't hang up.

                                 THEO
                     Why would anybody want to hurt
                     you?

                                 LENORE
                     They tortured my husband.  Made
                     him give them the pin numbers of
                     our accounts.  Once they get
                     what's in the safe deposit box
                     they'll kill us.

                                 THEO
                     Where'd they take you to?

                                 LENORE
                     I have no idea.  They put us in
                     the back of a van with blacked out
                     windows.  The shutters up here are
                     nailed shut.

                                 THEO
                     Well isn't there a number on the
                     goddam phone?

                                 LENORE
                     No -- nothing.

        Theo is so shaken by the call he runs a stop sign.  Other
        cars honk furiously.  He ignores them.

                                 THEO
                     Okay.  The police are gonna need
                     your full name and address.

                                 LENORE
                     No!  No police.  They'll know
                     right away the authorities are
                     looking for us.  They'll kill us.
                     We've seen their faces.

                                 THEO
                     The cops could trace this call
                     back to you.

                                 LENORE
                     One of them is a cop.

                                 THEO
                     What makes you say that?

                                 LENORE
                     He pulled us over as we left the
                     Riviera Tennis Club.  Claimed we'd
                     run a stop sign.  And when Elliot
                     was reaching for his license --

                                 THEO
                     Who?

                                 LENORE
                     Elliot -- our driver.  The officer
                     put his gun to the back of
                     Elliot's head and -- fired.  It
                     was so quick.

                                 THEO
                     Oh man.  These people mean
                     business.

                                 LENORE
                     Then they took the Mercedes away
                     -- with his body in it.

                                 THEO
                     Listen, there's an overpass coming
                     up.  I may lose you for a minute.

        We see a freeway overpass up ahead clogged with congested
        traffic.  Theo could get stuck under it for awhile.

                                 LENORE
                     No don't.  You could lose me for
                     good.  Don't go through that
                     tunnel.

                                 THEO
                     I'm in traffic.  There's no place
                     to turn.

                                 LENORE
                     Please.

                                 THEO
                     Shit!

        Theo Novak throws on the brakes.  The car behind him
        screeches to a stop nearly rearending him.

                                 DRIVER
                     Are you nuts?

                                 THEO
                     Back up.  I've got to pull out of
                     this lane.

                                 DRIVER
                     Fucking idiot!

                                 THEO
                     I acknowledge that!  Just back up!

        The cars behind are beginning to honk horns.

        Theo is waving at the driver in the next lane.

                                 THEO
                     Hey Buddy!  Can you let me pull
                     over?  Give me some space to pull
                     over.

                                 2ND DRIVER
                     Where do you think you're going?

                                 THEO
                     Any place.

                                 2ND DRIVER
                     This is one way.

                                 THEO
                     I know.  But it's an emergency.
                     Somebody dying.  Okay?

                                 2ND DRIVER
                     I don't see anybody in there but
                     you.

                                 THEO
                     I would appreciate a little space.
                     Thank you.

        The driver in the next lane backs up.  Now Theo can squeeze
        his Chrysler through.  By jumping the curb he can drive
        across the sidewalk and into the parking lot of a small
        corner mall with its donut shop and Chinese laundry.  He
        takes the exit which leads onto a residential side street.

                                 THEO
                           (into phone)
                     Fine, no tunnel.  Are you still
                     with me?  Hello?

                                 LENORE
                     I hear them coming upstairs.  I
                     won't be able to talk for awhile.
                     I have to lay the phone down and
                     pretend to be asleep.  So don't
                     talk.  Don't say a word or they'll
                     hear it.

                                 THEO
                     I can't stay on this line.  I'm
                     picking people up.  I'm already
                     overdue.
                           (no response)
                     Hello?
                           (no answer but the
                           line remains open;
                           Theo listens)

        Theo quickly puts the convertible top up and rolls up the
        windows so he can hear more clearly.

        There are indeterminate sounds coming over the open phone
        line.  It could be someone walking on a wood floor.  Theo
        keeps listening as he drives.  He's not paying a lot of
        attention to the road.  A large trailer truck honks at him
        nearly blowing him out of his seat.  He quickly covers the
        earpiece of the phone.  But the kidnappers may have already
        heard the sound and have been alerted by it.  He waves at
        the truck driver to hold it down.  The truck driver laughs
        at him.  Honks again.

        Theo pulls around onto the main boulevard again.  He's
        bypassed the overpass but not the traffic.  He keeps driving
        and listening.  Maybe she's gone.  Gone for good.

        Minutes ago he wanted her gone.  Now he's oddly concerned.
        He listens harder.  Still nothing.  Alongside him a black
        kid in a Honda has his rap music blaring.  Theo continues to
        keep the mouthpiece of the cellular pressed tightly to his
        chest to muffle all noise.  But he has to lift the receiver
        to his ear now and then to listen.  Still nothing.

        THEO'S POV - THE INTERNATIONAL HOUSE OF PANCAKES on the
        corner ahead.  His two partners are waiting to climb in when
        Theo pulls up.

        KLINGER is about sixty.  Once a ladies' man he has watched
        his looks fade.  He tries to hide his years with the aid of
        Clairol, badly applied and a few shades too dark.

        CAITLIN CARUSO has the look of a young woman who works out
        five or six times a week.  She's completely buffed.  She
        compensates by dressing in ultra-feminine attire -- pinks
        with lace cuffs and an abundance of makeup.

                                 KLINGER
                     You took your sweet time.

        Theo still keeps the phone buried in his chest.

                                 THEO
                     Just get in and keep still.

        Klinger climbs in the back seat.  Caitlin piles in beside
        Theo and gives him a fleeting kiss.

                                 CAITLIN
                     Who's on the phone?

                                 THEO
                     I'll explain later.  I'm sort of
                     on hold.

        Theo pulls away into traffic.

                                 KLINGER
                     You switched license plates?

                                 THEO
                     It's taken care of.

                                 KLINGER
                     We have never worked a gig
                     together but I am a firm believer
                     in preparation.  So let's go over
                     this again step by step.

                                 THEO
                     Not this minute.

                                 CAITLIN
                     He's screwing with us.  There's
                     nobody on that phone.

        Caitlin tries to take the phone.  Theo slaps her hand away
        hard -- and keeps the mouthpiece tightly covered.

                                 CAITLIN
                     What was that for?

                                 THEO
                     You could've made me lose my call.

                                 CAITLIN
                     So what?  What could be important
                     enough to put your hands on me?

                                 THEO
                     I didn't hurt you.

                                 CAITLIN
                     You couldn't hurt me.  But it's
                     the principle.

                                 KLINGER
                     That was definitely out of line
                     and totally unprovoked.  I heard
                     you were a hitter.

                                 THEO
                     Bullshit.

                                 KLINGER
                     That's your "rep."

                                 THEO
                     Wait!  I hear her breathing now.
                     There, she just picked it up
                     again.

                                 CAITLIN
                     It's some chick you've got on
                     there?  With heavy breathing, for
                     Christ sake?

        He listens anxiously as he drives.

                                 THEO
                     Say something ...

                                 CAITLIN
                     Me, he won't stay on the phone
                     with for five fucking minutes
                     without bitching.

                                 THEO
                     I'm trying to help somebody.
                     Okay?

                                 CAITLIN
                     He's at it again.  Like that night
                     at the Emerald.  This piece of
                     Euro-trash is slapping shit out of
                     his little wife in a back booth --
                     so Mr. Good Deed here has got to
                     step in and pound the fucker's
                     head into the wall.  Meantime
                     "Wifey" recovers enough to pull
                     off her high heel and nearly take
                     our hero's eye out.  It took six
                     stitches.

                                 THEO
                     How was I in the wrong?

        Some pedestrians crossing the street shout obscenities at
        Theo as they jump back on the curb.

                                 CAITLIN
                     Be careful.  There were people in
                     that crosswalk.

                                 KLINGER
                     That's all we need.  Better let me
                     drive.

                                 THEO
                     I'm fine.  She's back on.  Hello?
                           (uncovers mouthpiece)
                     I'm here.

                                 LENORE
                           (in pain)
                     They just walked out.  The smaller
                     man -- he must be Dominican or
                     Haitian -- he kicked me so hard.
                     I felt a rib crack but I never
                     made a sound.  It's starting to
                     hurt now -- real bad.  A
                     throbbing.  I can't even take a
                     deep breath.

                                 THEO
                     Don't move around.  You don't want
                     to puncture a lung.

                                 CAITLIN
                     Was someone in an accident?

                                 LENORE
                     Do I hear a woman's voice?

                                 THEO
                     I'm with two friends now.

                                 LENORE
                     Rachel!  They're going after
                     Rachel now -- and I can't stop
                     them.

                                 THEO
                     Stop throwing names at me.

                                 LENORE
                     Rachel, my daughter.  She's an
                     honor student at Parker.  My God,
                     she's only nine.

                                 THEO
                     What do they need her for?

                                 LENORE
                     They know Jack will give them what
                     they want once they have her.

                                 THEO
                     Bottom line!  There's nothing I
                     can do for you but tip the cops.

                                 KLINGER
                     What do you mean tip the cops?
                           (to Caitlin)
                     Is the man a lunatic or what?

                                 THEO
                     Will you relax?  This in no way
                     affects our business.
                           (into phone)
                     Go on.

                                 LENORE
                     The bigger man is driving our
                     Mercedes to the school.  Rachel
                     will recognize the car.  She'll
                     get right in.

                                 THEO
                     Let me call the school -- tell
                     them not to let her go.

                                 LENORE
                     They don't know you.  They won't
                     listen.

                                 KLINGER
                           (grabs Theo from
                           behind)
                     Hear this, Novak!  Loud and clear.
                     No cops!  Who did I get mixed up
                     with here?  Has he got a fucking
                     suicide wish?

        Lenore has overheard Klinger's outburst.

                                 LENORE
                     He's right.  You'll get my whole
                     family killed.

                                 THEO
                     He's right?  Look, don't try to
                     put blood on my hands.  You've got
                     one hell of a nerve siding with
                     him!

                                 KLINGER
                     Just hand up on the bitch!
                           (yells)
                     Fuck you, madam.  And goodbye!

                                 THEO
                     That's what I deserve for
                     listening in the first place.

        He glares at the cellular that got him into this.

                                 THEO
                     And I thought the worst this thing
                     could do was give me brain cancer.

        But he still can't bring himself to hang up.

                                 CAITLIN
                     Wait.  Let me talk.

        Theo gives up the phone.  Caitlin speaks.

                                 CAITLIN
                     I'm sorry for whatever's happened
                     to you but we're definitely not
                     the right people to do you any
                     good.

                                 LENORE
                     Don't you have children?

                                 CAITLIN
                     Matter of fact I did have a kid
                     once.  But he's a lot better off
                     with his father in Milwaukee.

                                 KLINGER
                     Have you got to tell her your life
                     story?

                                 CAITLIN
                     This is my conversation.  I'll say
                     what I fucking please.

                                 KLINGER
                           (directing Theo)
                     Wake up.  Make a right at Ocean
                     Avenue.  The hotel's a few blocks
                     up on the left.

                                 THEO
                     I know where it is.
                           (to Caitlin)
                     Give me that phone back.

                                 CAITLIN
                     I'm not finished.
                           (into phone)
                     Under other circumstances I'd
                     gladly go out of my way.  I don't
                     understand why you just don't
                     phone some other person.

                                 THEO
                     She can't!  It's busted.  Now hand
                     that on back!

                                 CAITLIN
                     Theo wants to talk again.

                                 THEO
                     Did you have to tell her my name?

        She returns the phone to him.

                                 LENORE
                     "Theo?"

                                 THEO
                     Forget who I am.  Where's this
                     school located?

                                 LENORE
                     26th off Wilshire.

                                 THEO
                     Even if I got there first she
                     wouldn't go with me.

                                 LENORE
                     She would if she heard my voice on
                     the phone.

                                 KLINGER
                     Enough!  You're not going
                     anywhere!

        Klinger makes a wild grab for the phone.  Theo reaches back
        and whacks him across the face.  Hard.

                                 THEO
                     I don't like anybody laying their
                     hands on me.

                                 KLINGER
                     Just like they say; no fucking
                     self control.

                                 THEO
                     If you know that just back off.

                                 KLINGER
                     Shit.  There's the hotel.  You
                     overshot the driveway.

                                 THEO
                     And stop with the directions.

                                 KLINGER
                     Make a "U" and go back.

                                 THEO
                     That's illegal.  You want us
                     pulled over?  I'll turn around at
                     the corner if you'll shut the fuck
                     up.

                                 KLINGER
                     You're doing all the talk.

                                 CAITLIN
                     Will you two cut it out?

                                 THEO
                           (into cellular)
                     This Mercedes of yours, what's it
                     look like?

                                 LENORE
                     A 600S black.  I feel like such a
                     fool.  I don't even know the
                     license number.  We have four
                     cars.

        Klinger is talking while Lenore is speaking.  They overlap.

                                 KLINGER
                     We still gotta run the drill
                     before we walk in that lobby.

                                 THEO
                     Go ahead then.  I'm covering the
                     receiver.  She can't hear.

                                 KLINGER
                     First off, this Mr. Chow Yen
                     doesn't speak a lot of English.
                     The girl with him will interpret.
                     There will be a third person to
                     accompany you into the men's room
                     where you can take count.  I hope
                     you know Krugerands better than
                     they know a Hockney.

                                 THEO
                     I improved on the fucking
                     original.

                                 KLINGER
                     Let's hope so.  Once you come out
                     and okay everything I'll give
                     Caitlin the sign that she can
                     bring the painting on over.

                                 THEO
                     It's rolled up in the tube on the
                     floor back there.

        They have turned around and pulled into the hotel's circular
        driveway.

                                 LENORE
                     Why isn't anyone answering me?

                                 THEO
                     Just hang on.  I've got a life of
                     my own.

                                 CAITLIN
                     What if they do question the
                     authenticity?

                                 KLINGER
                     Oh.  Seems yours girlfriend is
                     casting doubts on your expertise.

                                 CAITLIN
                     I am not!  Fuck you!  Theo's a
                     genius.

                                 KLINGER
                     Any trouble, we whip out our
                     Treasury Department badges -- show
                     them the wire I'm wearing and read
                     them their rights.  Theo seizes
                     the Krugerands as evidence.
                     Naturally they start negotiating.
                     Offer to give us up somebody else.
                     And we listen.  Take notes on who
                     bought what stolen art and tell
                     them we have to clear it with our
                     superiors at Justice.  We pick up
                     their passports -- escort them to
                     their room and leave them all in
                     the bathroom handcuffed to the
                     plumbing.

                                 LENORE (V.O.)
                     Will you please speak to me!
                     Theo?

                                 THEO
                     Another minute.

                                 KLINGER
                     Got your badge?

                                 THEO
                           (pulling out folder
                           with fake Treasury
                           Dept. badge)
                     Satisfied, Wiseass?

                                 KLINGER
                     In any event, whatever occurs you
                     do not belt anybody.

                                 THEO
                     What do you keep making me out to
                     be?

        Theo spots a pay phone kiosk near the hotel.

                                 THEO
                           (into phone)
                     Okay, okay, Lenore, calm down.
                     Either let me call the school or
                     better yet, the F.B.I.

                                 KLINGER
                     Sure -- and they record your
                     voice.  And later on we all get
                     slammed for kidnap and murder.
                     That's out!

        A parking valet rushes up.

                                 VALET
                     Checking in?

                                 KLINGER
                     Here for lunch.
                           (hands over a five
                           dollar bill)
                     Leave it close by.

                                 VALET
                     No problem.  It'll be in that
                     loading zone.

                                 KLINGER
                     Step out of the car, Theo.

                                 CAITLIN
                     He's right, Theo.  She might not
                     be around to back up your story.
                     You could end up in the middle of
                     this.

                                 THEO
                     Look -- I've got the lives of
                     maybe three innocent people
                     hanging on the end of this line.

                                 KLINGER
                     Well, I don't know any innocent
                     people and I don't give a shit.

                                 VALET
                     Excuse me but you're blocking our
                     driveway.  I've got to move the
                     vehicle.

        Several cars are backed up trying to depart the hotel.

        Klinger jumps out of the back seat opening the passenger
        side for Caitlin who takes along the tube with the fake
        "Hockney" inside.

                                 CAITLIN
                     I know you feel awful but it's not
                     your responsibility.

                                 THEO
                     Then whose is it?

                                 CAITLIN
                     You gotta just look the other way.

                                 THEO
                     I'm sorry.  You'll do all right
                     without me.  Keep my share.

                                 VALET
                           (insistent)
                     Sir?

                                 THEO
                     I'm moving the car.  See!  I'm
                     moving it!

        The passenger door is still open as Theo steps on the gas.
        The Chrysler careens down the circular driveway into traffic
        on Ocean Avenue and makes a sharp left.

        Caitlin and Klinger stare after it in apparent disbelief.

                                 KLINGER
                     I knew it the minute I laid eyes
                     on him.  A fucking flake!

        He looks over at the parking valet who now has no car to
        park.

                                 KLINGER
                     Give me back that five.

        INT. THEO'S CAR - DAY

        Speeding now -- and talking into the cellular.

                                 THEO
                     Hello?  It's just me and you
                     again.

                                 LENORE
                     What about the others?

                                 THEO
                     I kind of dropped them off.  They
                     were getting on my nerves.

                                 LENORE
                     What are you doing now?

                                 THEO
                     What do you think I'm doing?  I'm
                     on my way to the school like you
                     wanted.

                                 LENORE
                     Forget about us.  Just save
                     Rachel.

                                 THEO
                     Tell me what she looks like.

                                 LENORE
                     They say she resembles me -- dark
                     hair, ponytail, very dark eyes.
                     They all wear the same uniform.
                           (a beat)
                     Please.  Be careful.  The man
                     driving the car must have a gun.

                                 THEO
                     I'm not looking to get myself
                     killed.  I just hope the battery
                     on this phone holds out.

        He flips open the glove compartment and searches around
        inside.  Jammed with nothing but CDs.

                                 THEO
                     Where's the fucking recharger
                     cord?  Must be in her car, dammit.

                                 LENORE
                     How much time do you have left on
                     it?

                                 THEO
                     I don't know.  80 or 90 minutes,
                     tops.

                                 LENORE
                     Why didn't you do what your
                     friends wanted and just -- get rid
                     of me?

                                 THEO
                     I don't know.
                           (a beat)
                     I hung up on somebody else a long
                     time ago, and later on I wished I
                     hadn't of.

                                 LENORE
                     A woman?

                                 THEO
                     Hey drop it, okay?

                                 LENORE
                     I didn't mean to open up any old
                     wounds.

                                 THEO
                     It never healed.  I called her a
                     lying bitch and everything else
                     and I hung up on her.  "Click."
                     You don't exist.

                                 LENORE
                     And that was the end of it?

                                 THEO
                           (laughs)
                     I sure as hell got my wish.  She
                     doesn't exist.
                           (a beat)
                     So maybe you reached the
                     appropriate person after all.

                                 LENORE
                     I'm sorry if I caused you to lose
                     your business deal.

                                 THEO
                     Well you did.

        He feels like hurling the damn cellular out the car
        window.

                                 THEO
                     Now I know why I never wanted one
                     of these.  I should've made her
                     take it back.

        He makes a screeching left against oncoming traffic.

                                 LENORE
                     What do you do for a living?

                                 THEO
                     Sometimes I paint.

                                 LENORE
                     Our house always needs touching
                     up.

                                 THEO
                     Pictures.

                                 LENORE
                     I didn't mean to insult you.
                     You're an artist.

                                 THEO
                     They say my work is somewhat
                     derivative.

        He takes a shortcut, racing down a narrow alley behind a
        line of shops, knocking a few plastic trash bins over.

                                 LENORE
                     I suppose if you're a struggling
                     artist you need a patron.

                                 THEO
                     Lady, you don't have to keep up a
                     running commentary.

                                 LENORE
                     I'm afraid if I stop talking I'll
                     lose you.
                           (a beat)
                     Just name any reasonable amount
                     and it's yours.

                                 THEO
                     Shit, stop with the money!  I
                     never asked for a nickel.  I was
                     just doing this.  And you have to
                     fuck it up with a price tag.

                                 LENORE
                     I didn't mean to.  It's just the
                     way I am.

                                 THEO
                     A price on everything.

                                 LENORE
                     I wasn't always like that.  I
                     don't think I was.

                                 THEO
                     I'm about ten blocks from the
                     school.

                                 LENORE
                     I have no right to ask for help.
                     I've never thought of anybody but
                     myself.

                                 THEO
                     That makes two of us.

                                 LENORE
                           (suddenly)
                     You're breaking up.  I can't hear
                     you.  Theo?

        There's heavy static on the line.

                                 THEO
                     There are cables overhead.  Hang
                     on.  It'll clear up.

                                 LENORE
                     I've lost you.  You're gone.  I
                     can't hear anything.

        Suddenly another voice comes on.  As often happens, the
        cellular has picked up another call in progress.

                                 CALLER
                     Somebody's on our fucking line!

                                 FEMALE CALLER
                     How long have they been listening?

                                 THEO
                     Lenore, hang on.

                                 CALLER
                     Mister, get off of our call!

                                 THEO
                     This is an emergency so you get
                     off!

                                 FEMALE CALLER
                     Don't tell us what to do.  You've
                     got some nerve!  Dickhead!

                                 THEO
                     Lenore, are you still there?  Is
                     it a right or left off Wilshire?

                                 LENORE
                     Make a right.  You can't miss it.

                                 THEO
                     I'm making my turn.  I see the
                     school up ahead.

        THEO'S POV - THE PARKER SCHOOL - its yard now full of
        students.

        The voices on the crossed line still remain, giving Theo a
        hard time.

                                 CALLER
                     This shit happens all the time.
                     I'm switching to Air Touch!

                                 THEO
                     Good idea.  Get lost!

                                 FEMALE CALLER
                     Rude asshole.

        She hangs up.  The line is clear again.

        There are school buses already loading up.  The day's
        session has ended.

        CAMERA WHIP PANS AROUND - car doors slamming, buses pulling
        out.  Mothers are car-pooling, picking up groups of kids,
        all of whom are in uniform.  Vehicles are departing, none of
        them a black Mercedes.

                                 THEO
                     Lenore, I'm here.  I'm getting
                     out.

                                 LENORE
                     I can hear you again, clearly.

                                 THEO
                     Great.  Stay with me.  There must
                     be a hundred kids out here.

        Theo is out of the car which he leaves double parked.

        Camera races with Theo as he enters the school yard.

                                 THEO
                     I don't see any Mercedes.

        He looks around, trying to find any dark girl with a
        ponytail.  He sees one and catches up with her.

                                 THEO
                     Are you Rachel?

        The girl looks at him suspiciously and keeps walking.  She's
        obviously been trained not to talk to strangers.

                                 THEO
                     Does she have a red ribbon on that
                     ponytail?

                                 LENORE
                     That's not her.

        Whip pan to another prospect.

                                 THEO
                     Does she wear glasses?

                                 LENORE
                     No.

                                 THEO
                     I've got to ask somebody.

        Theo approaches a group of boys.

                                 THEO
                     Anybody see Rachel Oberfeld?

                                 2ND BOY
                     She always gets picked up by her
                     driver.  For dance class.
                     Stuck-up little bitch.

                                 THEO
                     Is she gone?

        Then Theo realizes a female teacher has come up behind him.

                                 TEACHER
                     May I help you?

                                 THEO
                     Did Rachel Oberfeld leave?

                                 TEACHER
                     Of course she did.  What business
                     is that of yours?

        A uniformed security guard is approaching.  This schoolyard
        is well patrolled.

                                 SECURITY GUARD
                     Any trouble?

                                 TEACHER
                     He's asking about the Oberfeld
                     girl.

                                 LENORE
                           (on cellular)
                     What's happening?

                                 THEO
                           (into phone)
                     She's gone --

                                 LENORE
                     Don't say anything.  Don't alarm
                     them.  Just go!

                                 THEO
                     I'm trying to.

                                 SECURITY GUARD
                     Is that your Chrysler double
                     parked out there?

                                 THEO
                     Yeah.  I'll move it.

                                 LENORE
                           (over cellular)
                     They've got her.  There's nothing
                     you can do but go.

        Theo is already exiting the school yard.  The teacher stares
        after him suspiciously.  The security guard follows him to
        the curb, watches him get in.

        INT. THEO'S CAR - DAY

        Theo pounds his fist on the dashboard in total frustration.

                                 THEO
                     I fucking blew it!

        He sees the guard copying down his license plate.

                                 THEO
                     He's copying down my license --
                     for all the good it'll do him.

                                 LENORE
                     It's not your fault, Theo.  You
                     tried.

                                 THEO
                     I should've put them out of the
                     car and come sooner!

                                 LENORE
                     When Jack sees they've got Rachel
               HE'LL tell them what they want to know.

        Theo starts the engine and pulls away from the school.  He
        rounds the corner onto quiet side streets.

                                 THEO
                     You said they wanted to get into
                     some particular safety deposit
                     box?

                                 LENORE
                     The one in Brentwood.

                                 THEO
                     What bank?

                                 LENORE
                     The City National on San Vincente.

        Theo sees something up ahead.  He grins.

                                 THEO
                     Wait just a minute.  Our luck has
                     changed.

                                 LENORE
                     What do you mean?

                                 THEO
                     Black Mercedes, 600S.

        He steps on the gas.

        VARIOUS SHOTS

        Theo pursues the Mercedes, catches up with it and forces the
        driver over to the curb.  The back windows are tinted.

        He leaves the cell phone on the seat as he gets out and
        hurries over to the Mercedes just as the chauffeur jumps
        out.

        Before the driver can say a word Theo decks him.  He goes
        down hard.

        Theo pulls open the back door expecting to see a nine year
        old girl.

        Instead he's looking at an elegant eighty year old woman who
        tosses her beaded handbag into his arms.

                                 OLD WOMAN
                     There -- take it and leave us
                     alone!

        Theo stares at her moment.  Then at the handbag he's
        caught.  He hands it back.

                                 THEO
                     Excuse the misunderstanding.
                           (to driver)
                     Don't get up!

        The driver is sensible enough not to rise until Theo has
        pulled off.

        INT. THEO'S CAR

        Moving fast to get out of the neighborhood.

        He picks up the cell phone.

                                 THEO
                     I'm not doing too well.
                           (a beat)
                     What's the matter?

                                 LENORE
                     I heard someone pulling in behind
                     the house.  I heard Rachel
                     screaming and then she stopped all
                     of a sudden.  I don't know what
                     they did to her.

                                 THEO
                     Which means you can't be more than
                     five or ten minutes from here.

                                 LENORE
                     Even if you found us -- what then?

                                 THEO
                     I'm cutting across to Bundy to
                     Brentwood.  That bank is our best
                     bet.  If anybody shows up I could
                     follow them.

                                 LENORE
                     Jack will negotiate with them.
                     He'll identify the right key and
                     give them the information they
                     need to gain access and they'll
                     let Rachel go.

                                 THEO
                     Not a chance.

                                 LENORE
                     Don't say that.

                                 THEO
                     Do you know what's in that box?

                                 LENORE
                     I'm not supposed to -- but I do.
                     Millions in cash and bearer bonds.

        Theo swallows hard.  That's enough to put him into mild
        shock.  After all Theo Novak is not known for his honesty.

                                 THEO
                     They'll recognize it's not your
                     husband.

                                 LENORE
                     Jack was only at that branch once
                     when he took the box years ago.

                                 THEO
                     They've still got to be able to
                     sign his name.

                                 LENORE
                     It's not hard to do.  I do it all
                     the time.

                                 THEO
                     I'm pretty good at signatures
                     myself.

                                 LENORE
                           (suddenly)
                     Oh my God.  I heard her scream
                     again.  What are they doing to
                     her?  Why can't I do anything to
                     stop them?

                                 THEO
                     You're doing what you can.  Why's
                     all this money stashed?

                                 LENORE
                     To hide it from the I.R.S.

                                 THEO
                     How come everybody turns out to be
                     a crook?

                                 LENORE
                     Don't talk.  Don't talk!

                                 THEO
                     What's going on?

                                 LENORE
                     The front door slammed.  Someone
                     went out.  There's a different car
                     starting.

                                 THEO
                     I might still get there first.
                     The lights are with me.
                           (a beat)
                     How would I identify the guy who
                     shows up at the bank?

                                 LENORE
                     If it's the tall man -- he had one
                     of those hair transplants.  Tufts,
                     you know.  It still hasn't grown
                     fully in.  The other one is from
                     the islands.  Braided hair -- very
                     dark.

                                 THEO
                     It won't be him.

                                 LENORE
                     Theo, I want you to know, you're
                     probably the most decent man I've
                     ever met.

                                 THEO
                     Yeah, sure that's me.  Ask
                     anybody.

                                 LENORE
                     But I guess we haven't really met
                     -- have we?

                                 THEO
                     I've got a lot of respect for you
                     too.  For the way you feel about
                     your family.

                                 LENORE
                     Jack hasn't loved me for years.
                     And now I'm afraid she's turning
                     out to be like him.  So cold and
                     distant.  I've let him make her
                     like that.

                                 THEO
                     Why tell me this?

                                 LENORE
                     Because you're probably the last
                     person I'll ever talk to.

                                 THEO
                     You can't give up.

                                 LENORE
                     When they first started
                     questioning Jack -- he answered
                     them in that tone he usually
                     reserves for me.  And they began
                     beating him.  And I watched.  And
                     I didn't feel anything ... What
                     kind of a person am I?

        Theo is now on San Vincente approaching the Brentwood
        community -- the shops, malls and restaurants.

                                 THEO
                     The bank should be -- there it is.
                     I'm looking for a place to park.
                     Pray for a miracle.  I don't
                     believe it.  Somebody's pulling
                     out of a meter.  Just across from
                     your bank.  Better yet.  There's
                     40 minutes left on the meter.
                     Maybe this is my day.

        There's a click on the line.

                                 THEO
                     Did you jiggle the phone?

                                 LENORE
                     No.

                                 THEO
                     Did you hear that click?

                                 LENORE
                     Yes -- I think so.  Another
                     crossed line?

                                 THEO
                     Or somebody else there is
                     listening in --

                                 LENORE
                     Downstairs.  There must be an
                     extension.  Oh my God --

                                 THEO
                     Don't panic.  I might be wrong.
                           (beat)
                     Hello?
                           (beat)
                     I guess I was wrong.

        Another rude motorist tries to steal Theo's precious space
        before he can pull in.  Theo honks at him.

                                 THEO
                     Don't even think about it!

        The other driver won't budge until Theo threatens to get
        out.  Finally frustrated, the other driver surrenders the
        space.  Theo backs in -- just as Lenore comes back on in a
        panic.

                                 LENORE
                     No.  I hear them.  They're coming
                     upstairs.  They know!

                                 THEO
                     Try what you did before.  It
                     worked before.  I won't talk
                     anymore.

        He gets out carrying the cellular phone which he continues
        to listen to -- even as he crosses the street to the bank.

        There's silence on the other end of the line.

        And Theo makes no attempt at further conversation lest he
        alert Lenore's captors that the phone is open.

        All at once he draws up short.  He sees something across the
        street.

        HIS POV - A POLICE CAR - visible at the mouth of an alley --
        Someone inside.  Is he watching the bank?  The windows are
        pulled up.  All Theo can see is a silhouette inside.

        BACK TO THEO

        Focused on that police car.

        BACK TO LONG SHOT - POLICE CAR - BACKING UP

        It slowly vanishes back into the alley.

        TRUCKING SHOT

        Theo quickly crossing the street.  He peers through the
        glass into the bank.

        HIS POV - INT. THE BANK

        There's plenty of activity.  Customers on line.  Half a
        dozen tellers in action.

        BACK TO THEO

        He decides to go inside for a closer look.

        CAMERA FOLLOWS THEO INTO THE BANK

        He carries the cellular with him -- still listening.

        INT. THE BANK

        Theo looks around for some sign of the man Lenore described
        with such clarity.  There's nobody like that.  He'll wait.

        There are video cameras mounted -- surveying the bank from
        all angles.

        Theo can't just stand idly around.  He'd attract attention.
        He gets on the long line where he won't seem conspicuous.

        He keeps the cell phone to his ear and his hand cupped over
        the speaker portion to muffle even the sound of his
        breathing.  And he listens hard.

        There are male voices distant and unintelligible.

        Then the sound of some furniture being turned over.

        Then A WOMAN'S SCREAM!

        Finally there's a rumble as if the receiver on the other end
        was being roughly dropped and picked up again.

        Theo reacts to what he hears while standing in the midst of
        the crowded bank.  He struggles to control his emotions.

        A deep voice is suddenly heard on the line.

                                 MALE VOICE
                     Is somebody there?  Answer me.

        Theo doesn't know whether to reply.

        In the background Lenore is heard screaming again.

                                 VOICE
                     You shut up!

        There's the sound of violent activity.  At that moment
        someone taps Theo's shoulder.

                                 WOMAN CUSTOMER
                     Next.

        Theo looks back at the woman behind him -- blankly.

                                 WOMAN CUSTOMER
                     Will you kindly pay attention.
                     You're next.

        Theo covering the mouthpiece tightly.

                                 THEO
                     Get ahead of me.

        He walks off the line -- still riveted to the phone.

                                 MALE VOICE
                     Whoever you are -- the girl's
                     gonna suffer for this.  You got
                     them all killed.

        Theo can't hold back anymore.

                                 THEO
                           (into phone)
                     Don't hurt her -- you bastards --

        That's all he gets to say before the phone goes dead.

                                 THEO
                     Don't hang up --

        But they have.  The line is dead.  He has finally lost all
        contact with Lenore.  He's numb with anger.

        CAMERA SWIVELS 180 DEGREES around Theo as he experiences a
        sudden dizziness.  Total isolation sets in.  He just stares
        at the dead phone in his hand -- which is trembling now.

        CAMERA CONTINUES ANOTHER 180 DEGREE SWEEP around him to
        reveal a very tall man coming out of the vault area and
        crossing the bank toward the exit.  HIS UPPER FOREHEAD IS
        COVERED WITH MINUSCULE TUFTS OF IMPLANTED HAIR.  His eyes
        are deeply set and close together.  He carries a large
        leather attache case.

        Theo focuses on the man -- just as he reaches the automatic
        doors which swing open wide.  In an instant he's out on the
        street.

        Theo hurries after him.  CAMERA FOLLOWS.

        EXT. BRENTWOOD STREET - DAY

        The tall man is moving swiftly along the sidewalk.

        Theo is directly behind him.  The dead phone is still in his
        hand.  He realizes this and stuffs it in his jacket pocket.

        TRUCKING SHOT - The tall man walks to the corner with Theo
        behind him.  The light is red.  Traffic thick.

        Suddenly the man abruptly turns looking face to face at
        Theo.

                                 TALL MAN
                     Tell me what you want.

        Theo struggles to control himself and put on an act.

                                 THEO
                     My brother's considering one of
                     those transplants and I wondered
                     -- is it painful?

                                 TALL MAN
                     You were watching me in the bank.

        Theo grabs the wrist of the hand that holds the attache
        case, twists it hard.

                                 THEO
                     That looks heavy.  Let me help you
                     with it.

                                 THE MAN
                   YOU'RE fucking with the wrong
                     people, Mister.

        Theo's instinct is always to hit first.  He throws a jarring
        left that takes the bigger man by surprise.

        His adversary is stunned but pulls free and uses his thick
        attache case as a weapon swinging it hard.

        Theo staggers then lurches forward to avoid a second blow
        tackling the six footer low and propelling him off the
        sidewalk and into the path of oncoming traffic.  WHAM!!!

        A Chevy Blazer slams into Theo's adversary knocking him off
        his feet.

        The car behind the Blazer rearends it as other vehicles slam
        into each other.

        The tall man has struck his head on the sidewalk after
        bouncing off the hood.  He's lying quite still and he's
        bleeding.

        Around him a crowd is forming and traffic is at a
        standstill.  Theo takes a step forward and trips over
        something.  It's the leather attache case at his feet.  He
        stoops and picks it up.

        It's chaos as the drivers of the stopped vehicles jump out
        shouting at each other.

                                 MOTORIST
                     He jumped in front of me.

                                 2ND MOTORIST
                     Look what you fucking did to my
                     car!

                                 MOTORIST
                     All of a sudden he was there.
                     Nobody could've stopped.

                                 2ND MOTORIST
                     Tell it to the cop!  Why isn't
                     there ever a cop?

                                 THEO
                     I'll go look for one.

        He walks casually through the mob that's forming -- in the
        direction of his Chrysler.

        Behind him, the crowd around the accident victim grows.  And
        still no police in sight.

        A uniformed guard from the supermarket kneels over the body.

                                 SUPERMARKET GUARD
                     He's hurt bad.

        An eyewitness rushes over, shouting.

                                 EYEWITNESS
                     I saw the whole thing.  He was
                     pushed!  I was sitting at the
                     Starbuck's over there and I saw it
                     all!

        ANGLE ON THEO

        he's heard the eyewitness -- any moment he could be pointed
        out.

        CAMERA FOLLOWS THEO TO HIS CHRYSLER

        He gets in and lowers the sun visor to partially obscure his
        face as he turns the ignition key and pulls out of the
        parking space.  He makes a quick right into the Ralph's
        Market lot and heads out the far exit which will bring him
        onto an entirely different street.

        He pulls over and turns his attention to the briefcase.  He
        fishes in his pocket and finds a small Swiss army knife.  He
        uses one of the blades on the lock -- finally breaking it.
        The briefcase snaps open.  It's stuffed full of loose money,
        fifties and hundreds -- plus a stack of negotiable bonds
        bound together in wrappers.  An impressive haul.  Theo tries
        to count it but his head is swimming.

                                 THEO
                     Some fucking jackpot.

        He closes the briefcase but now that the lock's broken it
        won't stay shut.  It springs back open.  He can barely keep
        the money inside it.

        He looks around, notices an indoor parking facility across
        the street.

        He drives over, takes an automated ticket -- then pulls up
        the ramp.

        He drives all the way up to the rooftop parking zone.  Few
        cars are up here.  He's alone.

        He pulls into a space.

        INT. THEO'S CAR - ROOFTOP PARKING AREA - DAY

        He reaches into his glove compartment which is crammed full
        of CDs and pushes a button which pops the trunk.

        EXT. ROOFTOP PARKING AREA - DAY

        Theo gets out holding the attache case tightly shut.

        TIGHT SHOT - INSIDE THE TRUNK.  Theo wedges the attache case
        in next to the spare which manages to hold it in place.

        We take casual note of an alternate set of license plates
        lying in the trunk -- before Theo slams the lid shut.

        ANGLE ON THEO

        Looking out from the vantage point of the rooftop at all the
        many homes and residences in the distance.  And in one of
        them Lenore and her family are being held captive.

                                 THEO
                     Where the hell are you, Mrs.
                     Oberfeld?  And why should I give a
                     fuck?  Especially now.

        He tries to figure out what to do.  Should he just keep what
        he's got and take off?  He reaches into the car for his
        cellular.

        CLOSE UP - CELL PHONE - as Theo dials:  STAR 69.

        He's ringing back the last number that called him.  Finally
        the call is picked up.  But nobody speaks.

                                 THEO
                     Don't be afraid to say hello.
                     Your friend with the recent
                     transplant is in no condition to
                     deliver that briefcase.  So I've
                     taken on the task.

                                 VOICE
                     Who are you?

                                 THEO
                     Let me talk to the lady again.

                                 VOICE
                     There's no lady here.

                                 THEO
                     If you've already killed her
                     that's fine.  I'll keep the bonds
                     and the cash.  We got nothing to
                     discuss.

                                 VOICE
                     Hold on.

                                 THEO
                     If her kid or her old man have
                     been harmed we've also got nothing
                     to talk about.

                                 VOICE
                     Let her tell you.

        After a pause a familiar feminine voice is heard.

                                 LENORE
                     Yes?  Yes?

                                 THEO
                     Hi Lenore.  It's me.  I got you
                     back.  Courtesy of Star 69.  Are
                     you hurt?

                                 LENORE
                     They dragged me downstairs.  I
                     thought they were going to kill
                     me.

                                 THEO
                     Lucky for them they didn't.

                                 LENORE
                     What did you do?

                                 THEO
                     I had a little encounter at the
                     bank and our Mr. Transplant ended
                     up under the wheels of a Chevy.

                                 LENORE
                     God, if he doesn't come back --

                                 THEO
                     I'm in possession of the bag he
                     was carrying.  And I'm in a
                     position to negotiate.  What about
                     your husband and your child?

                                 LENORE
                     They're tied with duct tape so
                     they can't speak -- but they seem
                     to be --

        The phone is grabbed away from her.

                                 MALE VOICE
                           (to Theo)
                     Who are you working for?

                                 THEO
                     I'm self employed.  What kind of
                     cut did the hairy one have?

                                 MALE VOICE
                     Twenty percent.

                                 THEO
                     Fine.  I want half.  Plus the
                     release of the family.

                                 MALE VOICE
                     Whatever you say.

        Theo looks over the side of the rooftop -- at the street
        directly below.

        THEO'S POV - AN L.A.P.D. CAR parked there.  CAMERA WHIP PANS
        to the concrete stairs which lead up to the rooftop ...
        Heavy racing footsteps can be heard.  Someone's coming!

        BACK TO THEO - hurrying back to his car -- while the
        conversation continues.

                                 THEO
                     You're making it too easy.

                                 MALE VOICE
                     You got time on your side.  Pretty
                     soon they'll be missed and we'll
                     have the law up our ass.

                                 THEO
                     They saw you kill the driver.

        INT. THEO'S CAR - ALREADY MOVING

                                 MALE VOICE
                     You're up on your details, aren't
                     you?

                                 THEO
                     You can rely on them to keep quiet
                     because this is undeclared money
                     that could land Jack there in
                     federal prison.  He can't afford
                     for you to get caught and have
                     this briefcase appear as evidence.

                                 MALE VOICE
                     Keep talking.

        Theo is already careening down the twisting ramp as he
        speaks.

                                 THEO
                     You're walking away with a clear
                     fifty percent and a guarantee
                     nobody can afford to I.D. you.

                                 MALE VOICE
                     There are no guarantees in this
                     life.

                                 THEO
                     Granted.  But I don't believe
                     they're grieving enough for their
                     chauffeur to piss away their own
                     futures.

        Theo pauses to pay the cashier before exiting.

                                 PARKING CASHIER
                     That's four fifty.

                                 THEO
                     For ten minutes?  Fucking thieves
                     everywhere.

        He pays and pulls off onto San Vincente heading west,
        checking the rearview to be certain he's not being followed.

                                 MALE VOICE
                     Where do we meet?

                                 THEO
                     It's a nice day.  How about the
                     beach?

                                 MALE VOICE
                     Pass.

                                 THEO
                     A large stretch of empty space
                     with no place to hide.  Temescal
                     Canyon parking lot.

                                 MALE VOICE
                     What time frame have you got in
                     mind?

                                 THEO
                     It should take me twenty minutes.
                     Where are you coming from?

                                 MALE VOICE
                     We can be there.

        EXT. WIDE SHOT - THEO'S CAR - DAY

        Weaving through traffic --

                                 THEO
                     I want you all in one vehicle.
                     Your van.  If I see anybody else
                     cruising around I'll keep going.
                     No second chances.  You can kill
                     them and I'll keep what I've got.

                                 MALE VOICE
                     Some loyalty.

                                 THEO
                     There's no loyalty at the expense
                     of my own ass.

        BACK INSIDE THEO'S SPEEDING CAR

                                 THEO
                     Tell the lady to relax.  Tell her
                     I can't wait to meet her in
                     person.

                                 MALE VOICE
                     She's somewhat damaged in the
                     shipping.  But nothing makeup
                     won't cover.

                                 THEO
                     Got a phone in that van?

                                 MALE VOICE
                     Sure.

                                 THEO
                     Take my number.  When you see me
                     -- call me and I'll walk you
                     through the exchange.  It's
                     308-9962 -- Repeat it back.

                                 MALE VOICE
                     308-9962.

                                 THEO
                     Beats yelling our brains out
                     across some parking lot.

                                 MALE VOICE
                     You're getting a lot of mileage
                     out of that cellular.

                                 THEO
                     I wish it had never been invented.

        HIGH ANGLE - 7TH STREET OFF SAN VINCENTE - DAY

        Theo rounding hairpin turns which carry him closer to the
        Pacific Coast Highway and the beach.

        EXT. PACIFIC COAST HIGHWAY - DAY

        As Theo turns and heads up the coast.  Camera follows --

        A few hundred yards ahead a boarded up fruit and produce
        stand is closed for the season.

        Theo pulls off the highway and parks behind the stand.  He
        again pops the trunk using the release button in the glove
        box.

        He gets out and proceeds to the open trunk.

        TIGHTER ANGLE - Theo again examines the overstuffed attache
        case that will no longer lock.  He flips it wide open, looks
        over the loose money spilled out and the bonds secured with
        rubber bands.  He begins tying the money up with the rubber
        bands -- stacking it.  Diving it into portions.

        He doesn't see or hear the highway patrol car that's quietly
        pulling up behind him -- out of focus.

        The whoosh of passing cars hides the sound of the prowl
        car's arrival.

        STILL IN SOFT FOCUS

        We see the uniformed officer getting out and approaching.

        Then Theo senses he's not alone.  He hears the jingle of
        keys and handcuffs on the officer's belt.

        He turns halfway and the cop is there.  The approaching cop
        is about thirty and his nametag identifies him as "Grillo."

                                 OFFICER GRILLO
                     Saw you pull over.  Thought you
                     might have a flat.

        The lid of the trunk is still up.  Theo casually lowers it.

                                 OFFICER GRILLO
                     Leave it open.

        Theo leaves the lid three quarters of the way shut as he
        turns to face the cop.

                                 THEO
                     Since when did you guys start
                     changing tires?

                                 OFFICER GRILLO
                     Only you don't have a flat.

                                 THEO
                     Seems not.

                                 OFFICER GRILLO
                     If you weren't going for a spare
                     what were you doing?

                                 THEO
                     Something was rattling around.
                     Some loose tools.

                                 OFFICER GRILLO
                     Mind if I have a look?

        The cop's hand is resting on his revolver.

                                 THEO
                     Why are you picking on me for?

                                 OFFICER GRILLO
                     Was I picking on you?  How come
                     you pulled in back of this
                     fruitstand?

                                 THEO
                     Tell the truth, I was going to
                     take a much needed leak.

                                 GRILLO
                     Now that'd be a misdemeanor.

                                 THEO
                     I got to get going.  An agent is
                     showing me a house up on Broad
                     Beach in ten minutes.

                                 GRILLO
                     They'll wait.  Meantime, raise the
                     lid.

        Theo is thinking how Lenore described the murderer of her
        driver as a uniformed cop who pulled her over.

        Then he sees the cop's police car is identical to the one he
        saw opposite the bank and near the parking garage.

                                 THEO
                     What'd you do?  Tail me from
                     Brentwood?

                                 GRILLO
                     Why would I do that?

        Theo lifts the lid to the trunk all the way up and steps
        aside.  The cop leans forward for a look.

        He sees the attache case jammed shut against the tire.  He
        also can't miss the extra license plates that lie in plain
        view.

                                 GRILLO
                     Let's have your license, mister.

                                 THEO
                     I'm going to level with you
                     officer.

        Theo flashes the folder with the phony Treasury Dept. I.D.
        which was to be used in the scam.

                                 GRILLO
                     What's this?

                                 THEO
                     See for yourself, federal agent,
                     U.S. Treasury.  On the job.

        As the confused cop studies the impressive I.D. Theo moves
        into action, grabbing Grillo's gun hand so he can't draw the
        weapon -- then throwing all his weight against the cop
        forcing him close enough to the lid of the trunk to be
        struck hard as Theo smashes it down on his shoulder.

        Grillo is momentarily stunned and can't recover in time to
        avoid the impact of the trunk smashing down again.  This
        time on the back of his neck.

                                 THEO
                     Does that answer your question?

        He finishes Grillo with two brutal jabs to the jaw.  The cop
        goes limp.

        Theo is alarmed as a car zips by on the highway and the
        driver leans on its horn.  He fears he's been seen.  There's
        no time to delay.  He lifts the officer's legs and dumps
        Grillo in the trunk.

                                 THEO
                     Seems I've got me a hostage.

        He removes the cop's .38 calibre sidearm from its holster.

        He grabs the attache case before shutting the trunk and
        making sure it's secure.

        Some fifty dollar bills fall loosely to the ground as Theo
        hurries back to the driver's seat.  He doesn't waste time
        scooping more than one or two of them up.

        He starts the ignition and steps on the gas.  He pulls away
        leaving the police cruiser parked where it stands behind the
        fruitstand.

        INT. THEO'S CAR - DAY

        He's sweating now.  The attache case lies half open across
        the seat next to him.  The windows are down and the loose
        money starts blowing all over the inside of the vehicle.

                                 THEO
                     Shit!

        Theo quickly puts the windows up but the damage is done.
        There are loose bills everywhere.

        THEO'S POV - THE HIGHWAY

        As he passes a mobile home park, he sees the carload that
        may have spotted him assault the cop.  They're at a pay
        phone -- excitedly reporting it.  One of them recognizes
        Theo's vehicle going by and points.

        ANGLE ON THEO

        Speeding up.

        VIEW THRU WINDSHIELD - TEMESCAL CANYON BEACH TURNOFF

        The huge parking lot is coming up on the left.  It seems
        totally vacant.  Not another car in sight all the way up the
        beach.  No attendant is on duty so Theo simply pulls in and
        keeps driving.

        There's still no sign of the van.

        Theo looks back toward the main highway half expecting to
        see a squadron of police cars -- but traffic remains normal.

        He sees a wooden shack -- a fast food outlet with large
        colorful signs proclaiming "Fried Clams - Fried Chicken -
        Ice Cream."  It's off season and closed.  Only the diehard
        surfers can be seen far off shore.

        He pulls up behind the concession stand so that his car is
        hidden from the highway.  He's only visible from the ocean
        side.

        TIGHT SHOT - INSIDE THE CAR

        Theo tries to gather up the money -- flatten it out -- put
        it back in stacks and secure it inside the attache case.  He
        lays the officer's gun down on the seat while he does this.

        Then the cell phone beeps.  Theo answers quickly.

                                 THEO
                     I'm here.  Where are you?

                                 MALE VOICE
                     We don't see you.

                                 THEO
                     I'm three quarters of the way up
                     the lot behind the concession
                     stand.

                                 MALE VOICE
                     Stay there.

                                 THEO
                     I don't want you within two
                     hundred feet.  Park down by the
                     lifeguard station.  Nobody gets
                     out.

                                 MALE VOICE
                     It's your call.

                                 THEO
                     Fucking "A" it is!  Any argument
                     and I'm out of here.

                                 MALE VOICE
                     Just relax.

                                 THEO
                     I don't need to relax.  The woman.
                     Put her on.

                                 MALE VOICE
                     You'll see her.

                                 THEO
                     I don't want to see her later.  I
                     want to hear her now.

                                 MALE VOICE
                           (slightly off)
                     Talk to the man.

                                 LENORE
                     Thank you.  God bless you for
                     helping us.

                                 THEO
                     Are you okay?

                                 LENORE
                     They wrapped tape around my wrists
                     and ankles.

                                 THEO
                     That's coming off.  How about the
                     girl?

                                 LENORE
                     She's awake but she hasn't spoken.
                     I don't know what they did to her.
                     I don't want to think about it.

                                 THEO
                     Your husband?

                                 LENORE
                     He's in back.  Lying face down.
                     They haven't hurt him anymore --
                     but he was crying.  I never heard
                     Jack cry before --

                                 THEO
                     You're all three of you in that
                     van?

                                 LENORE
                     Yes.

                                 THEO
                     Now you're going to do just what I
                     tell you to.  No discussion.  No
                     hesitation.

                                 LENORE
                     Yes sir.

                                 THEO
                     Put the man back on.

                                 MALE VOICE
                     Satisfied?

                                 THEO
                     You already tried to pull one
                     little number on me -- and it
                     didn't work.

                                 MALE VOICE
                     I don't know what you mean.

                                 THEO
                     I still don't see you.

                                 MALE VOICE
                     We're waiting for the light to
                     cross the highway.  It just
                     changed.  We're in a grey van.  It
                     reads "Noble Carpet Cleaners."

        THEO'S POV - There it is.  The grey Dodge van circa 1992
        with the lettering "Noble Carpet Cleaners - L.A. - Santa
        Monica - Marina Del Rey."  The windows in back are painted
        over.

        The van enters the huge empty parking lot and keeps rolling.

                                 THEO
                     That's far enough.  What -- do you
                     fucking need a written map?  Pull
                     over.

        The van stops.  There's a huge distance between them.  The
        negotiation continues over the cellular.

                                 MALE VOICE
                     We're waiting on you.

                                 THEO
                     Then just wait.  I'm counting this
                     all out and deducting my share.
                     While I'm at it you can be getting
                     that tape off the lady.  And her
                     little girl.

                                 MALE VOICE
                     It's in the process.

                                 THEO
                     I make my end of the cash at
                     184,000.  Now I'm trying to figure
                     out the bonds.  What the face
                     value is.

                                 MALE VOICE
                     You should've done all this
                     before.

                                 THEO
                     I'm not accepting criticism today.
                     Now don't make me lose count.
                     There's already a half million in
                     this portfolio.

                                 MALE VOICE
                     Her husband said there'd be one
                     million eight.  So nine hundred
                     to you.

                                 THEO
                     My pleasure --

                                 MALE VOICE
                     Be careful in disposing of them.
                     You'll have to discount 'em.
                     You'll be lucky to clear a hundred
                     and a quarter.

                                 THEO
                     Thanks for the sound advice.  Now
                     ask the woman to get out of the
                     van and walk over here.  Alone.

                                 MALE VOICE
                     Negative.

                                 THEO
                     You'll still have the girl and the
                     husband.

                                 MALE VOICE
                     And not a nickel.

                                 THEO
                     Soon as Mrs. Oberfeld is in my car
                     I'll toss out your first third.
                     Then I'll back up 200 feet to
                     behind the public restroom.

                                 MALE VOICE
                     And then?

                                 THEO
                     You pull up -- collect your first
                     installment.  Then you let the
                     daughter go.  When she reaches me,
                     I'll dump out another third.  Same
                     action.  I back up again -- you
                     pull forward.  Satisfy yourself
                     it's there.  Then we do it one
                     last time.  The final exchange.
                     And we go our separate ways.

                                 MALE VOICE
                     And they run straight to the cops
                     who start looking for our van.

                                 THEO
                     I won't let 'em.

        Lenore's voice is heard shouting near the receiver.

                                 LENORE
                     No!  Rachel has to go first.

                                 MALE VOICE
                     I like it better his way.

                                 LENORE
                     I want my daughter out of here!

                                 MALE VOICE
                     Reason with her.

                                 THEO
                     Lenore -- you promised you'd
                     follow instructions.  We're almost
                     there.  Simply get out when they
                     slide the van open and walk to me.

                                 LENORE
                     I'm not leaving my daughter
                     behind.  Not with them.

                                 THEO
                     She's next.  In two or three more
                     minutes she'll be free.

                                 LENORE
                     I can't do it.

                                 THEO
                     Don't start thinking about it.  Is
                     the tape off?

                                 LENORE
                     Yes.

                                 THEO
                     Can you walk?

                                 LENORE
                     Yes.  But I want Rachel to come
                     with me.

                                 THEO
                     They won't allow that.  It's one
                     at a time.  And you have to be
                     first.

                                 LENORE
                     Why can't it be her?

                                 THEO
                     She's a child.  She might panic.
                     She doesn't know me.  She might
                     not come to me.  She might just
                     run.

                                 LENORE
                     All right.  Now that you explain
                     it I see that you're right.

                                 THEO
                     Once you're in the car with me
                     she's sure to come to us.

                                 LENORE
                     I'm sorry.  You've thought this
                     out better than I ever could.  I'm
                     ready now.

                                 MALE VOICE
                     I'm opening the side door.  She'll
                     step out.  But before she gets in
                     your vehicle I want to see the
                     first installment put down in
                     plain view.  If it isn't there I'm
                     shooting her in the back.

                                 THEO
                     Are you trying to panic the women?

                                 MALE VOICE
                     That's how it is.  You see her
                     approaching you toss out
                     installment one.

                                 THEO
                     I'm tying it up in a bundle now.
                     Where is she?

        THEO'S POV - In the distance across the parking lot the door
        to the van slides back.  A woman in her thirties can be seen
        -- a bit wobbly on her feet.  Her dark hair is disheveled,
        her clothes askew and she seems disoriented at first.  The
        bright sunlight blinds her.

        She looks back at the van door closing behind her.  (The
        phone is inside with her abductors.  She can no longer
        communicate with Theo.)

                                 LENORE
                     Rachel -- Oh my God.

                                 THEO
                           (to himself)
                     Just start walking.  Come on.
                     Walk to me.

        Then Lenore begins to walk.  Slowly at first.  Then picking
        up momentum.  Until finally she's running.

        Theo gets ready with the money and bonds which are held
        together by thick rubber bands.

        He opens the passenger door halfway in preparation to throw
        the loot out onto the ground.

        Lenore is still running toward him.

        Then she trips and falls.

                                 THEO
                     Get up.

        For a moment she doesn't.

        Then she rises and begins walking again.

        She has almost reached Theo's car when he tosses the stack
        onto the ground where it can't help but be in plain view.
        Lenore is only a few feet away by now.

                                 THEO
                     Open the door and get in.  Hurry
                     up.

        She tries the passenger door.

                                 LENORE
                     It's locked.

                                 THEO
                     Shit.  I'm sorry.

        He pushes the unlock button.  She slumps in beside him.
        It's only this close that Theo realizes she's beautiful.

                                 LENORE
                     Thank you.  Thank you for doing
                     this.

        She leans over and kisses his cheek.  Her face is wet.

                                 THEO
                     Stop the crying.

                                 MALE VOICE
                     She's yours.  What are we waiting
                     on?

                                 THEO
                     I'm backing up.

        WIDE SHOT - BEACH PARKING LOT - DAY

        As Theo backs out from behind the concession stand leaving
        behind part of the stash.

        He backs several hundred feet -- hiding the car from view
        from the highway behind the concrete public restrooms.

        INT. THEO'S CAR

        He and Lenore watching the van.

                                 LENORE
                     Rachel was terrified when I left
                     her.  I could see it in her eyes.

                                 THEO
                     She'll be with you soon.  They're
                     pulling up.  They'll realize I
                     kept my part of the bargain.

                                 LENORE
                     She'll never be the same.  None of
                     us will.

                                 THEO
                     Include me in that.

        THEO'S POV - THE VAN

        Pulling up.  The driver's door opens -- the initial package
        is picked up.

                                 THEO
                           (into cellular)
                     Count it.

                                 MALE VOICE
                     Don't worry.

                                 THEO
                     Next I want to see Rachel.  Put
                     her on the phone before she gets
                     out so her mother can tell her
                     exactly what to do.
                           (to Lenore)
                     Keep her calm.  Tell her you're
                     fine and that she can join you in
                     this car.

        But Lenore has noticed something on the seat next to Theo.

                                 LENORE
                     You have a gun?

        Theo covers the mouthpiece of the cell phone so the
        abductors won't hear.

                                 THEO
                     Now I have -- it's a long story.

                                 LENORE
                     Why didn't you just shoot them?

                                 THEO
                     Because a lot of people would've
                     gotten killed.  Probably all the
                     wrong ones.

                                 LENORE
                     You're going to let them get away
                     with this?

                                 THEO
                     We've almost got your husband and
                     your daughter out.  So don't get
                     any ideas.

                                 LENORE
                     They tortured us.  And you're
                     going to let them have all that
                     money?

                                 THEO
                     So far they're keeping their part
                     of it.

                                 LENORE
                     They put their hands all over me.

                                 THEO
                     Somehow I got along better with
                     you on the phone.
                           (into cellular)
                     It's all there isn't it?

                                 MALE VOICE
                     Seems like it.

                                 THEO
                     Put the girl on.

        Without warning Lenore reaches out and grabs the gun off the
        seat.

                                 THEO
                     Don't be stupid.  Put it down.

        Lenore has a funny smile on her face.

                                 THEO
                     For Christ sakes don't point it at
                     me.  We want to get Rachel out of
                     there in one piece.
                           (into cellular)
                     I'm waiting for the girl.  Her
                     mother wants to talk to her.

                                 LENORE
                     Hand me the phone.

        Theo keeps looking down the barrel of that police special.

                                 LENORE
                     Hand it to me.

        He passes her the phone.

                                 LENORE
                           (into cellular)
                     He had a gun.  I have it now.

                                 THEO
                     Why are you telling him that.  Are
                     you crazy?

                                 LENORE
                     The rest of the money is here in
                     the car.  Why don't you come and
                     get it?

                                 MALE VOICE
                     Yeah.  Why don't we?

                                 THEO
                     What are you planning to do when
                     they got here?  They'll kill us.
                     They'll kill Rachel.

                                 LENORE
                     I doubt that very much.
                           (a beat)
                     Because right about now she should
                     be doing pirouettes at dance
                     class.

        THEO'S POV - The van is starting to roll toward him.

        BACK TO THEO AND LENORE - who still has the gun pointed at
        him.  The full impact of her words is like a slap across the
        face.

                                 THEO
                     You're not Lenore Oberfeld.

                                 LENORE
                     There isn't any such person.

                                 THEO
                     Whose money is this?

                                 LENORE
                     It belongs to the man you took it
                     from.  Or should I saw stole it
                     from?

                                 THEO
                     The guy with the transplant.

                                 LENORE
                     Jack Oberfeld in person.  Did you
                     kill him?

                                 THEO
                     Damned if I know.

                                 LENORE
                     The video cameras will put you
                     with him in the bank, and I'll bet
                     there were enough witnesses.

                                 THEO
                     At least one.

                                 LENORE
                     Plus they'll remember you going
                     after his daughter at school.

                                 THEO
                     You timed that beautifully.

                                 LENORE
                     They always pick Rachel up early
                     on Thursday.

                                 THEO
                     I got what I fucking deserved.  I
                     had it all.  I could've kept
                     going!

                                 LENORE
                     As they say -- no good deed goes
                     unpunished.

                                 THEO
                     And all that crap about your
                     driver being murdered by a cop --

                                 LENORE
                     I thought it was inspired.

                                 THEO
                     There was no cop involved.  Oh
                     shit!  Fuck!

        He realizes he assaulted a real L.A. cop on the job.  Maybe
        that cop is awake in the trunk and can hear what's going on.
        But she doesn't know that.

                                 LENORE
                     Sit completely still with both
                     hands on the wheel -- until they
                     get here.

                                 THEO
                     Why pick me to be your "mark?"

                                 LENORE
                     Nobody's easier to con than a con
                     man.

                                 THEO
                     You knew about me.

        Suddenly there's a violent thumping inside the car.  The
        vehicle is shaking.  Lenore has no idea what it is.  Theo
        knows immediately.

        It's the cop locked up in the trunk.  He's conscious and
        trying to bust his way out.

        The distraction causes Lenore to glance toward the rear of
        the vehicle -- and it gives Theo the chance to clip her
        across the jaw.  With the other hand he twists the gun out
        of her hand -- even as she is able to fire off one shot.  It
        singes Theo's hair leaving a powder burn across his scalp
        and shatters the side window.

        The van has pulled to a stop six feet ahead of Theo's car.
        Two men inside are halfway out.  A large powerful linebacker
        and a Haitian with braided hair.

        Before they can completely emerge, Theo's foot hits the gas.
        His car plows straight into the van stunning both me.

        Lenore has slumped to the floor of the car as Theo struggles
        to back up.  He's hooked onto part of the torn wreckage of
        the van.

        The larger man inside the van recovers and tries to fire --
        but the clip jams.  By the time he slams the clip straight
        Theo is backing away into a hairpin turn.

        Several shots are now fired at the departing Chrysler.

        TIGHT INSERT SHOT - TWO BULLETS PUNCTURE THE TRUNK -- which
        holds the unfortunate cop.  There's a SCREAM!

        WIDER SHOT - Theo smashes through a low barricade and plows
        down a hillside onto the beach.  In a moment he's driving up
        the Temescal beach -- a totally illegal route -- but the
        quickest getaway path.  An old man flying a kite dashes out
        of his way.

        There's a ramp up ahead down which beach cleaning equipment
        may gain access.  One such large orange vehicle is just
        accessing the beach.

        Theo leans on his horn.  The sanitation dept. vehicle pulls
        up short just avoiding a head-on smashup with Theo who
        speeds by and up the ramp -- heading back toward the Pacific
        Coast Highway.

        INT. THEO'S CAR

        Lenore still lies on the floorboard along with some of the
        bonds and the money.

        Theo has the gun in his right hand as he steers with his
        left.  The cell phone is on the seat.

        The thumping from the trunk continues.

                                 LENORE
                     Who's in back?

                                 THEO
                     L.A.P.D.

                                 LENORE
                     Shit.  You couldn't be in much
                     worse shape.

        ANGLE ON VAN

        Battered but fully operable -- in pursuit.

        INT. THEO'S CAR - DAY

        The phone conversation between Theo and those in the van
        remains open.  Theo's hands are occupied with the wheel and
        the gun which he holds on Lenore in an effort to make her
        behave.

                                 THEO
                     Your friends are probably still on
                     the line.  Pick it up and say
                     hello.

                                 LENORE
                     There's no way out for you.  You
                     have to deal with us.

                                 THEO
                     Assure them that you're being well
                     treated.

        Lenore finally lifts the cellular and speaks.

                                 LENORE
                     Nels, are you there?  Hello, is
                     anybody there?

        The thick voice we've become accustomed to hearing comes on
        the line.  (Now we'll call him by his actual name:  NELSON.)

                                 NELSON
                     I thought you said you could
                     handle him.

                                 LENORE
                     I'm doing fine.  Theo wants to
                     deal.

                                 THEO
                     Tell them I'm keeping what's left.
                     I earned it.  I probably killed
                     some poor bastard for it.

                                 LENORE
                     He seems to think he's entitled to
                     it all.

                                 THEO
                     Not all.  They already have a
                     third.  The question is how much
                     of that are they willing to give
                     to get you back?

                                 LENORE
                     You won't shoot me.  That's not
                     your style.

                                 THEO
                     We might hit a bump and the gun
                     might go off.  Ever see that
                     Tarantino movie -- where Travolta
                     blew that guy away in the back
                     seat -- purely by accident?

                                 LENORE
                     Do you have to point that?

                                 THEO
                     Absolutely.  And Topanga Canyon
                     has a hell of a lot of potholes if
                     I recall.

                                 LENORE
                     He seems to be headed for Topanga.

                                 THEO
                     I'm not trying to lose them.  Nor
                     am I exceeding any speed limits.

                                 LENORE
                     The one thing you don't want is to
                     attract the police.

                                 THEO
                     Granted, the cops are not an
                     alternative.  Certainly not with
                     one of their own still locked in
                     my trunk.

                                 LENORE
                     I don't hear him moving around
                     anymore.

                                 THEO
                     Those shots your associates got
                     off may not have done him too much
                     good.  That's on their head.  All
                     I did I was put him there.

                                 LENORE
                     A typical fuck-up.

                                 THEO
                     What's that supposed to me?

                                 LENORE
                     I knew you were a loser the first
                     night I laid eyes on you.

                                 THEO
                     You, I would've noticed.

                                 LENORE
                     Oh no, you were too busy trying to
                     keep some Croatian from slapping
                     the shit out of his girlfriend.
                     She showed her gratitude by almost
                     taking your eye out with her
                     spiked heel.

                                 THEO
                     You were at the Emerald that
                     night?

                                 LENORE
                     Naturally you didn't learn your
                     lesson.

                                 THEO
                     I guess I ought to stop seeing
                     woman as victims.

                                 LENORE
                     I think it was my tone of voice
                     more than anything else that sold
                     you.  And when you thought I was
                     being kicked around, I wish I
                     could've seen your face.

                                 THEO
                     You're enjoying this too much.

        Theo squeezes the trigger -- pumps off a shot into the seat
        beside her.

        It's the sound of the shot inside the enclosed vehicle that
        shocks her.  She SCREAMS.

                                 THEO
                     Now you're starting to sound like
                     a victim again.

                                 LENORE
                     You could've hit me.

                                 THEO
                     Only in the leg or the thigh.
                     You'd live but you just wouldn't
                     wear shorts.

                                 LENORE
                     You wouldn't --

                                 THEO
                     Yes I would.  Not kill you.  But
                     blow off a few toes, absolutely.
                     I'm entitled to that as
                     retribution.  It'll help you to
                     remember me in years to come --
                     every time you put on stockings.
                     They must have prosthetic toes by
                     now -- with little nails on them
                     you can polish --

                                 LENORE
                     Stop talking like that!

                                 THEO
                     Then scream for me.  A repeat
                     performance.  Let me see how easy
                     you can turn it on.  Scream!  I
                     want to hear you scream for me!

        Lenore fakes the first two screams but then they become more
        real as she focuses on the gun bouncing around in his hand.
        Her final screams are not act.

        Nelson's voice is heard over the phone.

                                 NELSON
                     What's he doing?  Answer me!

                                 THEO
                     Better reassure him.

                                 LENORE
                           (into cellular)
                     I'm still okay.

                                 THEO
                     Inform him the fee is seventy-five
                     large for your return.  All parts
                     intact.

                                 LENORE
                     He wants 75 back.

                                 THEO
                     Plus names, addresses and I.D. for
                     the lot of you.  We're in this
                     together and I need to know who my
                     partners are.  In case I ever need
                     to roll over on somebody.

                                 LENORE
                     Did you hear that?

                                 THEO
                     Let me talk to him.  Hold the
                     phone to my ear -- but don't nudge
                     me.

        Lenore holds the phone up so Theo can continue driving with
        his left hand while holding the gun in his right.

                                 THEO
                     Who am I talking to?

                                 NELSON
                     Call me "Nels."

                                 THEO
                     Okay Nels, you can always keep
                     what you've got and haul ass
                     leaving the lovely lady for me to
                     worry about.  I'll bet she can be
                     friendly when it's in her best
                     interests.

                                 NELSON
                     If you're looking for a quickie
                     all you've got to do is ask.

                                 THEO
                     I think I've already had a
                     "quickie."  Thank you.

        Now Theo makes a sharp tight turn off P.C.H. onto Topanga.

                                 THEO
                     Follow me across Topanga.

        Theo looks in the rearview and sees the van directly behind
        him.

        EXT. PACIFIC COAST HIGHWAY - TOPANGA AREA - DAY

        CAMERA PANS TO REVEAL - Highway patrol officer in his car --
        reporting in.

                                 MOTORCYCLE COP
                     Vehicle matching description 1995
                     Chrysler convertible maroon wanted
                     in connection with missing
                     L.A.P.D. officer.  Has turned
                     north onto Topanga.  Two
                     passengers.  One believed to be
                     female.  Request backup.  License
                     number G47495J.

        BACK INSIDE THEO'S CAR

        He hasn't told anyone he fears being spotted by the police
        but he regularly checks his rearview mirror.

        HIS POV - REARVIEW MIRROR

        Watching the van following but not too close.

        ANGLE ON THEO'S CAR - DEEP IN THE WINDING CANYON

                                 THEO
                     These mountains kill the
                     transmission.  He's gone.
                           (beat)
                     How's it feel to finally be alone
                     with me?

        Theo is deliberately making dramatic turns that toss Lenore
        around as she continues to stare at the loaded gun.

                                 LENORE
                     Use both hands on the wheel!
                     Goddam it!

        HER POV - THE TWISTING CANYON FLASHING BY

        Rock slides after recent storms have narrowed the road.

        TIGHT ON THEO

        In total control of the situation now.  He's been
        manipulated long enough.  Now he's pulling the strings.

        Then he hears a SIREN.  It echoes off the canyon walls.  It
        could be coming from any direction.

                                 THEO
                     It could be a fire.  This is
                     Malibu.

                                 LENORE
                     No, there's a police car way back
                     there.  See it, in the distance
                     coming around the turn?  The van
                     is blocking it now.

                                 THEO
                     What's Nels' number?

                                 LENORE
                     259-7881.

                                 THEO
                     Dial him up.  We need him to run
                     interference.

        Theo watches as she dials -- and since they're much higher
        in the canyon now the call goes through.

                                 LENORE
                           (into phone)
                     Nels, don't let that cop pass you.

                                 NELSON (V.O.)
                     What am I supposed to do?

        She again holds the phone so Theo can speak.

                                 THEO
                     If he pulls me over he gets all
                     the proceeds plus Lenore here.

                                 NELSON
                     And if you ditch us we get zilch.

                                 THEO
                     Sure, I end up with some cash.
                     And a lot of bonds I don't know
                     how to dispose of.

        ZOOM IN - TIGHT ON REARVIEW

        We can clearly see Nelson at the wheel and the Haitian
        beside him.

                                 THEO
                     You're going to have to see to it
                     that both lanes of this road get blocked.

                                 NELSON
                     The fuck I will!

                                 THEO
                     It's in your interest, Nels, since
                     the additional passenger in my
                     trunk -- an LAPD officer is
                     probably carrying a few bullets in
                     him traceable to the piece you're
                     carrying.
                           (to Lenore)
                     Tell the man.

                                 LENORE
                     Lose the hardware now.

                                 NELSON
                     We'll toss it when we make the
                     blind curve.

        EXT. WINDING ROAD - DAY

        Narrowed by the rock slide.  As the van hits a blind spot
        where the cops won't see, the Haitian throws a canvas bag
        holding the guns out into the canyon underbrush.

        BACK TO THEO, LENORE

                                 THEO
                           (into phone)
                     You researched me.  You know where
                     I live.  She'll be waiting for you
                     there along with your split.

                                 NELSON
                     There's two police cars now.

                                 THEO
                     Tailgate me.  I'll jam on the
                     brakes.  You go into a spin to
                     avoid an accident and cut them
                     off.

                                 NELSON
                     You want us to get ourselves
                     killed?

                                 THEO
                     From what I can see you're a
                     pretty fair wheelman.  There's a
                     hairpin coming up -- that's the
                     place for it. The cops'll plow
                     right into you.

                                 NELSON
                     And I end up in a fucking neck
                     brace for life!

                                 THEO
                     Then you can sue the cops.
                     Collect from both ends.  Tighten
                     your belts.  Here it comes.
                           (to Lenore)
                     Ready?

                                 LENORE
                           (yells into phone)
                     Nels, do what he says!

        EXT. MOUNTAIN ROAD - DAY

        As Nelson's van now speeds forward to tailgate Theo's
        Chrysler.  Behind the van the two police cars now appear
        around the curve, sirens blasting.

        They're reluctant to try to pass on these twisting
        rock lined roads with traffic coming around blind curves
        from the other direction.  And there's nowhere to pull over.

        Then Theo jams on the brakes.  The van veers to the left to
        avoid total disaster plowing into the canyon wall and
        blocking both lanes.

        The first police car can't avoid hitting the van broadside.

        The second police car rearends the first.

        It's a total pileup as Theo predicted -- a perfectly
        orchestrated accident.

        Then a camper coming from the Valley approaches and passes
        Theo -- rounds the bend and compounds the accident --
        smashing into the disabled van from the opposite side.

        Nelson and his Haitian friend are sandwiched between wrecks.

        Meanwhile Theo speeds on ahead.

        INT. THEO'S CAR - DAY

        Theo watching in rearview.  Lenore is turned around, looking
        back.

                                 LENORE
                     Do you think they'll walk away?

                                 THEO
                     Ask them.

        He passes her the cell phone.

                                 LENORE
                           (into cellular)
                     Are you okay?  Nels -- answer me!

                                 NELSON'S VOICE
                     Muthafuck!  My shoulder hurts like
                     a bitch.  Rodriego puked all over
                     himself.  Here come the cops.  I'm
                     laying the phone down.

        We can hear what's been said, distant but understandable.

                                 COP'S VOICE
                     Are you guys all right?

                                 NELSON
                     You could've killed us.

                                 COP'S VOICE
                     It was the fugitive in the
                     Chrysler that caused this.  We
                     were trying to overtake him.

                                 NELSON
                     No reason to kill innocent
                     bystanders.  Shit.  I can't hardly
                     move my neck.

                                 COP'S VOICE
                     We've already got an ambulance on
                     the way.  Don't try to get out.

                                 NELSON
                     I'm not staying in here with him
                     puking all over the place.  Get
                     this door open!

        Theo and Lenore concentrate on the road ahead.

                                 LENORE
                     They'll have units blocking us up
                     ahead.

                                 THEO
                     That's why we're turning off onto
                     a fire road.

                                 LENORE
                     Some people fall apart in a pinch.
                     But you shine.

        EXT. MAIN ROAD - DAY

        As Theo veers off onto a dirt road kicking up dust.

        INT. THEO'S CAR - DAY

        Lenore still listens in on the cellular.  There are many
        voices but they're impossible to decipher.  Static, noise.

                                 THEO
                     What's happening?

                                 LENORE
                     I can't hear.  Now there's a
                     siren.  They must be in an
                     ambulance.
                           (into phone)
                     What about the money?  Nels?

                                 THEO
                     Wonderful feeling of security
                     knowing your adversaries are both
                     crippled and unarmed.

                                 LENORE
                           (into phone)
                     The money, Nels ... ?

                                 NELSON
                           (through static)
                     In the backpack with me --

        Then he fades out.  She's lost him.

        He takes the cellular away from her.

                                 THEO
                     I'm learning to love this little
                     invention.

        The car plows through backroads that have become overgrown.

                                 LENORE
                     Any idea where you're going?

                                 THEO
                     I was sentenced to a youth camp
                     out here when I was fourteen.  We
                     cleared some of these same roads.

                                 LENORE
                     They did some great job of
                     reforming you.

                                 THEO
                     That's where this Chicano
                     correctional officer first taught
                     me to slap paint on a canvas.  I
                     could copy any fucking thing he
                     put in front of me.

                                 LENORE
                     Think you could do a picture of
                     me?

                                 THEO
                     I had it in my mind what you'd
                     look like.  "Her," I could've
                     painted.  You, I'd be afraid to
                     turn my back to mix the colors.

        Theo is now turning off down a construction road leading
        into a partially completed residential project.  Several
        small Spanish style home have been left unfinished.

        Construction gear stands gathering rust.  Theo pulls in and
        shuts off the ignition.

                                 THEO
                     Developer ran out of money years
                     back.  I'd hate to think about
                     what's living in there.

                                 LENORE
                     Why are we stopping?

                                 THEO
                     I need a break.  I've been on a
                     marathon run ever since I had the
                     misfortune to strike up a
                     conversation with you.

        He removes the ignition key.  Taking the gun, he gets out of
        the vehicle to stretch his legs.  She follows.  He has
        placed the cellular in his pants pocket.

        TRUCKING SHOT - Lenore -- as she catches up with him and he
        pauses to look her up and down with an artist's eye.  Her
        fragile beauty camouflages her true nature.

                                 THEO
                     Who'd ever think, to look at you?

                                 LENORE
                     As a child I hated being told how
                     sweet I looked.  That angelic
                     little face wasn't me at all.  I
                     had to hurt people to prove to
                     them they had the wrong image.
                     Sometimes words were enough -- but
                     I wasn't beyond inflicting
                     physical pain in order to be taken
                     seriously.  I enjoyed seeing the
                     shock on their poor faces when
                     they realized who I was.  That
                     same look you gave me when I
                     turned the gun on you.

                                 THEO
                     You've had a lot of fun with me
                     today.
                           (a beat)
                     What would you have done if I
                     hadn't responded to your call?

                                 LENORE
                     We had a backup plan.  But I knew
                     you'd come through for me.

        She presses up against him.  He reaches up with his left
        hand and caresses her breast.

                                 LENORE
                     Like steering, it's better if you
                     use two hands.

        But Theo has no intention of relinquishing the .38.

                                 THEO
                     Yeah, I was waiting for that
                     suggestion.

                                 LENORE
                     Sooner or later you'll learn to
                     trust me.

                                 THEO
                     How about "later?"

        She kisses him with an open mouth.  He accepts the kiss but
        gives absolutely nothing back.

                                 THEO
                     What's really on your wicked
                     little mind?

                                 LENORE
                     The cop in the trunk -- he could
                     still be alive.

                                 THEO
                     That's a reasonable possibility.

                                 LENORE
                     He might've heard everything we
                     said in the car.

                                 THEO
                     What's your point?

                                 LENORE
                     We can't leave him to repeat
                     anything.

                                 THEO
                     Which one of us is elected to do
                     the deed?

                                 LENORE
                     You're the man with the gun.

                                 THEO
                     Naturally.

                                 LENORE
                     Naturally.

                                 THEO
                     Maybe your friends already
                     accomplished that chore for us.

                                 LENORE
                     Only one way to find out.

        Camera follows them as they cross towards the parked vehicle.
        The trunk is facing them -- with its two bullet holes quite
        evident.

        He tosses her the keys.

                                 THEO
                     Unlock it.

        Lenore inserts the key in the trunk and steps back as the
        trunk pops open.

        THEIR POV - the L.A.P.D. officer is alive and unhurt as he
        squints up at them.  The burst of sunlight bothers his eyes
        but the bullets have missed him entirely.

        WIDER ANGLE

                                 THEO
                     Come on, Grillo, climb out.

        Officer Grillo doesn't speak.  He looks from Theo with the
        gun to the pretty woman that accompanies him.

                                 LENORE
                           (to Theo)
                     What are you waiting for?

        The cop obediently climbs out of the trunk.  He moves
        slowly, with great effort.  Being cramped up in there has
        been painful.

                                 GRILLO
                     Lady, don't let him do it!

                                 THEO
                     You got it wrong.  I'm the one
                     that's on your side.

                                 GRILLO
                     You almost brain me and lock me in
                     a fucking trunk and you're on my
                     side?  You stupid fuck!

                                 LENORE
                     He's seen both of us now.

                                 GRILLO
                     Look, I've got a wife.  I don't
                     care if either of you ever get
                     caught.

                                 LENORE
                     What else did you expect him to
                     say?  Do it, Theo -- or give me
                     the gun.

                                 THEO
                     I'm going to cuff you and leave
                     you in that house.  It may take
                     awhile but you'll be found after
                     we're long gone.

                                 LENORE
                     That's not good enough.

                                 THEO
                     That's how it's going to be.

        At that moment the cell phone in Theo's pocket rings.

                                 THEO
                     Nels reporting in.
                           (to cop)
                     Sit down where you are.  Arms
                     folded.

                                 GRILLO
                     Yes sir.

        Theo answers the phone.

                                 THEO
                     Yeah?

                                 NELSON (V.O.)
                     I just strolled out of the
                     emergency room while they were
                     admitting Rodriego.

                                 THEO
                     You couldn't be calling at a worse
                     time, Nels.

                                 LENORE
                     If he was here he'd know what to
                     do!  Let me talk!

        She reaches for the phone, he pulls it away.

                                 THEO
                     I'm handling it.

                                 LENORE
                           (shouting into
                           cellular which Theo
                           still holds)
                     He let the fucking cop out -- but
                     he won't --

        As Lenore distracts Theo for an instant Grillo tosses a
        handful of dirt up into Theo's eyes.

        At the same time Lenore makes a grab for the gun.

        The cell phone is dropped as the three of them struggle over
        the weapon.

                                 NELSON (V.O.)
                     What the fuck's coming off?

        The cop wrestles the gun from Theo's grasp -- then stumbles
        backwards covering both of them.

        Lenore breaks out into laughter -- like some kind of
        uncontrollable release.

                                 THEO
                     Glad you're having a good time.

        But she continues laughing.  The cell phone lies in the dirt
        halfway between them and Grillo.

        Keeping the gun leveled on Theo, the cop crouches down and
        picks up the phone.  He speaks.

                                 GRILLO
                     Nels?  You asshole.  You almost
                     nailed me inside that trunk.
                     Shit, that was close.

        CLOSE SHOT - THEO

        As the realization hits him.  He wasn't wrong about the
        officer after all.  The cop was in on it just as Lenore
        described on the phone.

        WIDER SHOT

                                 NELSON (V.O.)
                     How the fuck would I know you were
                     in there?

        Grillo turns to Lenore --

                                 GRILLO
                     It took you long enough to get my
                     ass out.

                                 LENORE
                     With all those holes Nels pumped
                     in I knew you wouldn't suffocate.

                                 GRILLO
                     You can tell she was really
                     worried about me.

        Lenore walks over to the cop and plants a kiss on him as
        Theo looks on -- a numbness rapidly overtaking him.

                                 GRILLO
                             (to Theo)
                     I told you I had a loving wife.

        Lenore and the officer make a chilling couple.

                                 GRILLO
                     In case you crapped out it was my
                     job to go after that briefcase.

                                 THEO
                     Or relieve me of it later.

                                 GRILLO
                     Only I was sloppy.  I let you take
                     me out.  That was quite a
                     humiliation.

        Grillo now retaliates by clubbing Theo several times with
        the barrel of the gun.

        Theo goes down and is smart enough to stay down.

                                 NELSON (V.O.)
                     Don't fuck around.  Pop a cap in
                     him.

                                 LENORE
                     Allow me.

        Theo sees what's coming but he's down on his knees in a
        clearing with no place to run.

        Her husband passes Lenore the gun.  She can't help but hit
        him at such close range.

                                 LENORE
                     Hold the phone out so Nels doesn't
                     miss the show.

        Lenore takes careful aim.

                                 LENORE
                     In appreciation for services
                     rendered, I'll make it quick.

        TIGHT ANGLE - LENORE

        As she fires.  One solitary shot.  (We don't see Theo who is
        on the ground off camera.)

                                 LENORE
                           (into phone)
                     He took it like a man.
                           (to Grillo)
                     Toss him in that drainage ditch.

                                 NELSON
                     There's a taxi stand here.  I can
                     meet you.

        As Grillo continues listening camera swivels 180 degrees.
        We expect to see Theo's body lying sprawled and bloody.

                                 NELSON (V.O.)
                     Only be careful nobody "makes"
                     that Chrysler.

                                 GRILLO
                     It's only a few miles and our
                     friend was thoughtful enough to
                     bring spare plates.

                                 LENORE
                     We're switching plates now.

        Instead of a bloody corpse we see Theo kneeling where he was
        before -- without a mark on him.

        Lenore has fired the shot entirely for Nelson's benefit.
        She's conning him just as she conned Theo.

                                 GRILLO
                           (to Nelson)
                     See you at the canyon house.

        Grillo hangs up.  After a silence Theo finally speaks.

                                 THEO
                     You missed.

                                 GRILLO
                           (to Lenore)
                     Any time you decide to let me in
                     on it.

                                 LENORE
                     You nearly fucked up your end so
                     keep quiet.  Get him busy on those
                     license plates.

        At gunpoint, Theo is forced to kneel down, remove the plates
        and replace them with the ones lying in the trunk.

        He uses the same small Swiss army knife with which he broke
        open the briefcase.

        While Theo works at it, Lenore and Grillo confer in hushed
        tones out of his earshot.

                                 LENORE
                     I prefer to have the sucker die at
                     a more convenient location.  Once
                     Nels arrives with his backpack
                     full of goodies.

                                 GRILLO
                     So Theo and Nels will appear to
                     have whacked each other out and we
                     never existed.  A thing of beauty.
                     Jesus, the shit you come up with!

        Theo finishes the license plate switch, turns to face them.

                                 GRILLO
                     Peg that knife into the bushes.

        Theo obeys tossing the Swiss army knife away.

                                 GRILLO
                     Now turn around.  I'm going to
                     cuff you.

                                 LENORE
                     Put those away.  We can't have
                     marks on his wrists.

                                 GRILLO
                     You never miss a trick.

                                 LENORE
                     I'll see that he stays calm.  Pack
                     the money up and put it in the
                     trunk.

        There's no question about who's calling the shots here --
        Officer Grillo gathers the loose money and bonds and stuffs
        it all in the broken attache case before depositing it back
        in the trunk.

        Lenore forces Theo into the passenger seat in front.  She's
        positioned directly behind him -- the gun at his head.

                                 LENORE
                     Want to try taking it away from me
                     again?

        Grillo gets behind the wheel, starts rolling.

                                 GRILLO
                     How do we get back to the freeway?

                                 THEO
                     Bear right till the fire road
                     ends.  It's not far.

        He reaches out toward the glove compartment.  Then he feels
        extra pressure from the gun on the back of his neck.

                                 LENORE
                     Both hands on your lap.

                                 THEO
                     Nothing but CDs in there.  I
                     thought maybe you'd like some
                     Celine or Whitney.

        Grillo reaches over and opens the glove compartment,
        spilling out dozens of CDs at Theo's feet.  He's satisfied
        there's no weapon in there.  The glove compartment remains
        open.

                                 GRILLO
                     I'd like for you to shut up for
                     awhile.

        The fire road now widens and down below they can see the
        freeway -- busy now with afternoon traffic.  Grillo
        continues driving down, finally approaching the on-ramp.

                                 THEO
                     Yeah, I suppose getting whacked
                     has got to be one of your best
                     ways to die.  Particularly if
                     you're not expecting it.  You
                     don't know what hit you.

                                 GRILLO
                     Can you make him stop!

                                 THEO
                     Mind letting me make the best of a
                     rotten situation?

        EXT. VENTURA FREEWAY EAST ENTRANCE - DAY

        As Grillo drives down the on-ramp and joins the traffic.

        INT. THEO'S CAR - DAY

                                 THEO
                     Just sitting here listening to her
                     voice does it to me all over
                     again.  No harm admitting I fell
                     in love with the sound of you.

                                 LENORE
                     That's a skill you acquire when
                     you do fantasy phone sex for a
                     living.
                     I must've had thirty regulars
                     salivating at 4.99 per minute.

                                 GRILLO
                     Which is how we hooked up
                     initially.  The woman nearly
                     freaked when she learned I was on
                     the force.  Figures it was some
                     kind of sting.

        They are in speeding freeway traffic now.  Lenore is keeping
        the gun out of sight of motorists in the adjoining lanes.

                                 THEO
                     Some nice fantasy you all cooked
                     up for me.

                                 LENORE
                     Took preparation.

                                 THEO
                     Exactly who was this Oberfeld?

                                 LENORE
                     Local lawyer for Dominican
                     dealers.  Off to buy a half
                     interest in a mall in Granada
                     Hills on their behalf.

                                 GRILLO
                     Which is why we had a lot more to
                     worry about than the law.  These
                     are people who don't worry about
                     reading you your rights.

                                 THEO
                     I'm the one they'd be looking for.

                                 LENORE
                     And we'll make certain they find
                     you.

        They're interrupted by the ringing of the cellular.  Is it
        Nelson calling again?

                                 THEO
                     Want me to answer it from beyond
                     the grave?

        Lenore pokes the gun against his neck before answering.

                                 LENORE
                     Yes?

        It's Caitlin's voice that comes on.

                                 CAITLIN
                     What are you doing on Theo's line?

                                 LENORE
                     Taking messages.

                                 CAITLIN
                     He ran out on me to be with you?
                     Well fuck him!  Everything worked
                     twice as good without him.  We
                     didn't need him then and I don't
                     need him now.

                                 LENORE
                     I'm sure he'll be heartbroken.

                                 CAITLIN
                     I know he's there!  He doesn't
                     even have the balls to pick up the
                     phone!

                                 LENORE
                     I won't let him.  He belongs to me
                     now.  Bye, sweetie.

        She hangs up.

        But Theo hasn't been idle during the exchange on the phone.
        He's casually reached into the now empty glove compartment.

                                 THEO
                     Know what else is in here?

                                 LENORE
                     Take your hand out of there.
                     Slowly.

        Theo does not obey the command.

                                 THEO
                     There's a little button under my
                     finger.  And when I push it the
                     trunk pops.

        Grillo reaches out and grabs Theo by the throat.  He
        continues guiding the vehicle with his left hand.

        INSERT SHOT - TIGHT ON THEO'S FINGER

        On that tiny button.

                                 THEO
                     Think about what's going to happen
                     to your valuables when that trunk
                     flies open at 75 miles per?

        BACK TO THREE SHOT IN CAR

                                 LENORE
                     You won't live to see it.

                                 THEO
                     It's going to be some fucking
                     snowstorm.

                                 LENORE
                     Pull over!  Pull over someplace.

                                 GRILLO
                     I can't.

        They're in the center lane and cars are racing along on both
        sides of them.

                                 GRILLO
                     I told you I should've cuffed him.

                                 THEO
                     I want the gun emptied.  I want to
                     see all six slugs tossed up here.
                     And then I want out.  That's all.
                     OUT!

        EXT. THE FREEWAY - DAY

        Cars speeding along at better than 70 mph.

        BACK INSIDE

        CLOSE ON the police service revolver flipped open so the
        bullets can be removed.

        Lenore spills the cartridges out in her hand.

                                 LENORE
                     Five ... six.

                                 THEO
                     Toss them -- one at a time.  I
                     don't want to lose count.

        She tosses the bullets over his shoulder onto the floor of
        the front seat -- so Theo can clearly see them.

        He's still bent forward with his hand inside the glove
        compartment -- pressed against that crucial little button.

        EXT. FREEWAY - HIGH ANGLE - DAY

        Construction ahead.  The lanes will soon converge.  Traffic
        will decrease to a virtual standstill.  Once traffic slows
        or stops Theo's threat become meaningless.

        INT. THEO'S CAR - DAY

        Theo realizes traffic is slowing.  He's got to act now.
        He's bent forward so Grillo doesn't notice that he's
        reaching under the seat with his free hand.

        Just as he pops the trunk he uses all the force in his legs
        and all his body weight to slam the seat back -- straight
        into Lenore's face.

        The impact is quick and violent.

        She's struck in the nose and forehead and propelled
        backwards.

        QUICK CUTS

        The trunk pops open.

        The loose cash and bonds in the broken attache case flutter
        and take flight.

        As Theo predicted it's a snowstorm of cash and negotiable
        instruments.

        WIDER SHOT - THE FREEWAY - DAY

        As bills of high denominations waft through the air landing
        upon and sticking to the windshields of other vehicles.

        The door to Theo's car is flung open.  He's trying to jump.

        MULTIPLE SHOTS - Other drivers in their cars reacting to the
        appearance of cash money on the opposite side of the glass.

        It's money they can't reach.  They're going at better than
        60 mph now and the dough is on the outside of their
        windshield.  Some nearly lose control and veer into other
        lanes.

        INT. THEO'S CAR - DAY

        The front passenger door flung wide open.  Grillo panics.
        His fortune is blowing to hell.  Lenore, in back, is still
        recovering from the blow to the head.

        Grillo still has a firm grip on Theo who's attempting to
        bail out.  Theo elbows Grillo, stunning him.

        The excavation ahead and the converging lanes have forced
        traffic to slow to the 40's -- as Theo breaks loose and
        jumps.

        ANGLE ON THEO'S BODY

        Hitting the surface of the freeway and rolling.

        Other vehicles are coming at him --

        But he rolls out of their path and into the excavation that
        has narrowed the lanes at this section of the freeway.

        He lies there on his back wondering if any bones are broken.
        He aches all over -- but he's alive.

        WIDER SHOT - FREEWAY - DAY

        A few cars and a trailer truck have pulled to a stop.

        Motorists and the truck driver rush out to the aid of the
        man they saw fall from the car.  (The trucker is a thickly
        built Greek.)

        They crowd around Theo.

                                 MOTORIST
                     Talk to me!

                                 TRUCKER
                     Trying to commit suicide, Mister?

        Theo has to think of some response.

                                 THEO
                     Reach into my inside pocket.
                     You'll find I.D.

        The motorist finds the folder with the fake badge.

                                 FIRST MOTORIST
                     Shit.  He's a federal agent.

                                 THEO
                     U.S. Treasury.  On the job.

                                 FIRST MOTORIST
                     If I knew you were a tax man I
                     would've run over you.

                                 2ND MOTORIST
                     Hope you know how close you came.

                                 THEO
                     I been accident prone all day.

                                 FIRST MOTORIST
                     This have anything to do with the
                     money I thought I saw flying all
                     over the fucking freeway?

                                 THEO
                     Not allowed to discuss it.

                                 TRUCKER
                     I already called for an ambulance.

                                 THEO
                     You've got a phone?

                                 TRUCKER
                     Doesn't everybody?

        That's the magic word to Theo.  He starts to get up.

                                 THEO
                     I need a ride.  Help me up.

                                 2ND MOTORIST
                     Better wait for assistance.

                                 THEO
                     Just give me a hand.  See, I can
                     walk.  Hoist me up in there.

        They all help Theo into the cab of the truck.

        INT. TRAILER TRUCK - DAY

        Theo looks at his hands.  They're raw, having been badly
        scraped when he hit the freeway.  His pants and jacket are
        torn at the knees and elbows.

                                 THEO
                     This was once a brand new Armani.

        The Greek trucker climbs behind the wheel.

                                 TRUCKER
                     You ought to be examined.

        The truck is already in motion.

        EXT. THE FREEWAY

        The bottleneck ahead has opened up.  The trailer truck
        barrels on ahead.

        THEO IN TRUCK

        He sees something of interest ahead.

        THEO'S POV - FROM SPEEDING TRUCK

        There in the emergency lane to the far right is Theo's
        Chrysler pulled over.

        Lenore and Grillo are out and leaning inside the trunk,
        trying to organize and secure what's left of their booty.
        It seems it's not all gone.

        BACK ON THEO

        Amused.  He reaches for the trucker's phone.

                                 THEO
                     Can I make a quick call?

                                 TRUCKER
                     Government business?

                                 THEO
                     Very official.  259-7881, if I
                     recall.

        He dials.  Nels answers instantly.

                                 NELSON
                     Yeah?

                                 THEO
                     Nels!  Guess who?  A friendly
                     voice from beyond the grave.

                                 NELSON
                     Who's this?

                                 THEO
                     I thought you'd know me by now.

                                 NELSON
                     What does it take to kill you?

                                 THEO
                     I suppose you're in your taxi?

                                 NELSON
                     Why would she want me to think you
                     were on ice?

                                 THEO
                     Intelligent question, Nels.  I
                     believe she had plans for both our
                     bodies to be found in close
                     proximity.

                                 NELSON
                     That bitch.  What's keeping you
                     from taking off?

                                 THEO
                     My compensation!  Somebody still
                     owes me -- big time!

                                 TRUCKER
                           (who's been listening)
                     What kind of Treasury Dept.
                     business is this?

                                 THEO
                           (covering phone
                            mouthpiece)
                     Undercover.

                                 TRUCKER
                     I thought so.

                                 THEO
                           (into phone)
                     Your partners are currently armed
                     and we're not.  Our edge is that
                     they don't know we're in touch.

                                 NELSON
                     I can see the benefit in that.

                                 THEO
                     You could always disappear with
                     what's already in your backpack.

                                 NELSON
                     Not without the name of the
                     contact who can discount the
                     bonds.  I may need to pry that
                     information out of her.
                           (a beat)
                     What do you stand to gain?

                                 THEO
                     Sweet revenge plus maybe a bit of
                     vigorish off your end.

                                 TRUCKER
                     The 405 is coming up.

                                 THEO
                           (to Nelson)
                     Where is this canyon house where
                     you're supposed to hook up?

                                 NELSON
                     In the hills above Sunset.  Just
                     below the Getty.

                                 THEO
                           (to trucker)
                     Take the 405 south.

        EXT. FREEWAY - DAY

        The truck veers onto the 405.

        INT. TRUCK - DAY

                                 THEO
                           (into phone)
                     How far off are you?

                                 NELSON
                     Five minutes.

                                 THEO
                     Where do I turn?

                                 NELSON
                     Take the Getty Center exit -- make
                     a right onto Cisco.  It'll be a
                     narrow winding road.  You can't
                     miss the house.  It's a mansion
                     built back in '29 -- Spanish --
                     boarded up since the quake.

                                 THEO
                     Have your cab wait at the foot of
                     Cisco -- we'll ride up together.

                                 NELSON
                     And make ourselves a hell of a
                     target.

                                 THEO
                     We're gonna get there first.

                                 NELSON
                     How do you know?

                                 THEO
                     Believe me.  They couldn't be
                     busier at the moment.

        Theo hangs up.

                                 TRUCKER
                     I didn't hear nothing.

        The truck barrels along.

        EXT. GETTY EXIT OFF 405 FREEWAY - DAY

        As the truck pulls off and takes a sharp right turn.  The
        Getty Museum looms majestically above.

        INT. TRAILER TRUCK - DAY

                                 THEO
                     Look for Cisco.

        From inside they now see a taxi parked about fifty feet up a
        narrow side road.  The truck pulls over.

                                 THEO
                           (to trucker)
                     Let's have your name and address.
                     The government will want to send
                     you a letter of commendation.

                                 TRUCKER
                     Who the fuck you kidding?
                           (he jots down an
                           address)
                     Send me money!

        The Greek trucker hasn't believed a word of Theo's Treasury
        Dept. bullshit.  Theo climbs out of the truck, not without
        severe discomfort.

                                 TRUCKER
                     You sure know how to take a lot of
                     punishment.

                                 THEO
                     From here on, I dish it out.

        The truck pulls off as Theo hikes up the road to the waiting
        taxi cab.

        Nelson gets out to greet him.  They've talked on the phone.
        Nelson has tried to kill him.  They've engaged in a car
        chase.  But they've never formally met.

                                 THEO
                     Hello criminal, pleased to meet
                     you.

        Nelson gives Theo a quick frisk to make sure he's clean.

                                 THEO
                     Better haul ass if we're gonna be
                     inside to greet them.

                                 NELSON
                     I've got a couple of spare pieces
                     stashed under the floorboards.

                                 THEO
                     Where's the backpack?

                                 NELSON
                     None of your business, but it's in
                     the cab.  That's all mine.  When
                     we take from them, we divide,
                     eighty-twenty.

                                 THEO
                     At those prices I'd just as soon
                     your cabbie didn't get a look at
                     me.

        Nelson returns to the cab, pays the driver and returns with
        the backpack.

        Theo turns away so the taxi driver can't identify him as he
        pulls off.

        Then he and Nelson double time it up the hill to the
        dilapidated Spanish mansion.

        CAMERA FOLLOWS

        Theo looks up at the massive Getty Museum which dominates
        the hillside above.

                                 THEO
                     Probably as close to the Getty as
                     I'll ever come.  Unless you care
                     to be my "patron," Nels.  You
                     wouldn't be the first successful
                     thief to become a patron of the
                     arts.

                                 NELSON
                     In your dreams.

                                 THEO
                     Don't underestimate me.  I've got
                     original ideas of my own.  Warhol
                     got famous doing a soup can.  What
                     would you think of a cellular
                     phone done in acrylics?

                                 NELSON
                     Are you busting my chops or what?

        As we draw closer we get a better look at the house.  The
        earthquake has left it rather lopsided.  There are cracks
        evident in the pillars in the front portal.  Tiles have
        fallen off the roof.  The lawn is totally overgrown and ivy
        has invaded the house.  Some windows are broken but most are
        boarded up tight.

                                 NELSON
                     Once was a palace.

        He proceeds to the boarded up entrance -- pries the thick
        planks apart to gain access to the door.  He and Theo slip
        through avoiding long rusty nails which jut out.  Nelson
        carefully replaces the boards, squeezing them back together.

        INT. SPANISH MANSION - DAY

        Totally deserted.

        The only furniture left is a ratty old sofa and a few beach
        chairs.  There's no electricity in operation and the covered
        windows allow little light.  It may as well be night.

        There's a gaping hole in the floor that Theo nearly steps
        into.

                                 THEO
                     Somebody better tear this down
                     before it falls down.

                                 NELSON
                     Stay put!  I know my way around.

        Nelson proceeds carefully up the cracked marble staircase to
        the second level.

        Nelson disappears into the darkness above.

        ANGLE ON NELSON - WITH THEO VISIBLE DOWN BELOW

        Nelson kneels, pulls up what's left of a threadbare rug to
        reveal the once luxurious maple floor.  Several planks are
        easily pried up and Nelson reaches in and retrieves one of
        the weapons which have been left here for safekeeping.  It's
        a .45 Glock automatic.  The clip is already loaded.

        He replaces the rug, then opens his backpack and takes out
        his own cell phone which he speed dials.  Lenore picks up.

                                 LENORE
                     Nels?

                                 NELSON
                     I'm still in my cab -- jammed up
                     in traffic.  Are you there yet?

                                 LENORE
                     Any minute.

                                 NELSON
                     I was worried about you.  Both of
                     you.

                                 LENORE
                     We've had our share of fuck-ups
                     but it's going to work out fine.

                                 NELSON
                     Give me 20 minutes at least.

        He hangs up, stuffs the phone into the backpack, then
        crosses to the stairs and descends.  Theo awaits him.

                                 THEO
                     Who were you talking to?

                                 NELSON
                     Them.  They won't be expecting us.

                                 THEO
                     Brilliant -- unless they were
                     close enough to see the cab pull
                     away.  In which case you just
                     warned them.

                                 NELSON
                     Nobody can do anything right but
                     you!

        Nelson jacks a cartridge into the chamber of the Glock.
        Obviously Theo is not to be trusted with a weapon.

                                 NELSON
                     First thing they'll see when they
                     walk in is you.  And while they're
                     wondering how in hell you got here
                     -- I will be picking Grillo off
                     from behind the staircase.

        Theo claps his hands in mock applause.

                                 THEO
                     I'm in awe.

                                 NELSON
                     Following which we will have a
                     serious question and answer
                     session with your girlfriend.

        There's the sound of an automobile coming up the road.
        Lenore and Grillo are making their arrival.  We hear them
        park.

        Theo and Nelson silently await their entry through the
        boarded up front door.

        Moments later they're heard prying away the boards Nelson
        recently replaced.

        Nelson, still carrying the backpack, withdraws into the
        shadows beneath the staircase with the Glock ready to open
        fire at Grillo.

        He motions Theo to move into the center of the entry hall --
        where he can't be missed.  He'll be spotted immediately.

        The boards are being pulled loose.  The door is opening
        inward.  But nobody steps inside.

        Instead two quick shots ring out.

        Nelson staggers out of his hiding place dragging the
        backpack in one hand and sprawls face down on the cracked
        marble floor -- blood oozing out of him.

        He's been shot from behind.  His .45 automatic is still
        gripped in his trembling hand.

        Theo realizes that either Grillo or Lenore must've come in a
        back way -- while the other directed Nelson's attention to
        the front door.

        No one's shooting at Theo yet.  Maybe he can't be seen from
        the shooter's vantage point -- and nobody expects him to be
        here.

        Nelson raises his head a few inches from the floor.  He's
        looking straight at Theo.

        Then with the last bit of strength left in him he skitters
        the gun across the slick marble floor -- directly to Theo
        who makes a dive for it.

        Then the front door swings wide open -- as Grillo rushes in.

        It must be Lenore -- behind Theo in the dark -- who fired
        the fatal shots.

        Grillo spots Theo going for the gun.

                                 GRILLO
                     Lenore -- look out!

        Two more shots spray the marble inches away from Theo -- as
        he grabs the automatic and fires blindly in return.

        Grillo rips a heavy plank with rusted nails away from the
        doorway and makes a mad dash at Theo who's still sprawled on
        the floor.

        Theo stops him with one shot before Grillo can strike a
        lethal blow.

        Grillo tumbles backwards and lies motionless --

        Theo fires wildly into the darkness again as he inches
        forward and reaches out for the strap of the backpack.

        Grasping it, he retreats to cover as a bullet aimed at him
        strikes the backpack instead.

        Theo gets to his feet and stumbles down the long hallway.
        There are half a dozen other rooms on this first level.
        Plenty of places to hide in the pitch dark.

        But Lenore also has many hiding places and she must know the
        layout of the house better than he does.

        CAMERA FOLLOWS Theo from one vacant room to another --
        through what once was a huge kitchen.  All the appliances
        have been ripped out.  Windows everywhere are boarded up --
        blocking out the light.  The floor groans under his weight.

        CLOSE UP - LENORE'S HANDS

        She's leaning over Officer Grillo's body, taking spare
        cartridges from his belt and reloading.

        BACK TO THEO

        Waiting in the darkness.  An idea flashes through his mind.

        He opens the backpack, locates Nelson's cellular phone.

        Once again a cell phone may be crucial to his fate.

        He steps out into the corridor again.  The floor creaks as
        it did before advertising his progress.

        CAMERA MOVES FORWARD WITH THEO

        There are half a dozen doorways ahead -- on both sides.

        She could be anywhere.

        A few more steps forward -- then he pauses.  Stays
        absolutely still.

        She's heard enough of the creaking to draw her to him.

        It's nearly pitch black in that narrow hall.

        If he can't see her then she can't see him.

        He's ready to put the cellular to use.

        EXTREME CLOSE UP - CELL PHONE

        As Theo punches REDIAL.

        WIDER SHOT

        As in the darkness another cell phone begins to ring.

        (Theo guessed right.  Lenore is still in possession of the
        cellular that once belonged to him.  The cellular Nelson
        dialed only minutes ago.)

        The ringing in the dark pinpoints Lenore's position exactly.

        Theo empties his weapon in the direction of the ringing.

        There's a scream.  Several flashes as Lenore's gun goes off
        -- as we hear her fall.

        Then just the constant unnerving sound of the cellular
        ringing.

        Theo waits.  Then he hears her.

                                 LENORE'S VOICE
                     Oh God -- Oh no -- Help me --
                     Don't let me -- Die.

                                 THEO
                     Didn't we play this scene before?

                                 LENORE'S VOICE
                     Don't leave me here to die --
                     Theo, please -- you can't let me
                     die --

                                 THEO
                     I'm afraid I've used up all my
                     good deeds for the day.

        There's another gunshot fired by her -- a wild shot that
        blows a hole in the stucco wall inches away from Theo's
        head.

        Then the sound of the gun clattering to the wood floor.  A
        gasp.  Then only the continuous ringing ...

        After a moment Theo approaches her body.  He's still
        dragging the backpack beside him.

        He kicks the .38 away from her cautiously before
        ascertaining that she's no longer any threat.  She won't
        live much longer.  But she can still speak.  The phone lying
        beside her keeps ringing.

                                 LENORE
                     I picked the wrong number when I
                     chose you ... didn't I?

                                 THEO
                     Turns out you did me a favor.
                     You're looking at a rich man.

                                 LENORE
                     -- The phones, Theo.  Don't leave
                     any of them behind.  The cops
                     could pull up a record of all our
                     calls and -- find you.

        Even lying there losing blood she's still trying to call the
        shots.

                                 THEO
                     You are some control freak, lady.

        He bends over and retrieves his own cellular, flipping it
        off before dropping it in the backpack along with Nelson's
        phone.

                                 LENORE
                     I've got ... one last number for
                     you, Theo ...

                                 THEO
                     I don't want it.

                                 LENORE
                     My fence in San Francisco ...
                     305-4410.  Maurice.  Don't take
                     less than a third on the face
                     value of those bonds.

                                 THEO
                     Sure, like I'm gonna take advice
                     from you.

                                 LENORE
                     I told you ... sooner or later
                     you'd have to trust me ...

        She raises her hand and Theo grips it tightly.  He can see
        she's slipping away.

                                 THEO
                     You know, I meant what I said
                     about falling for your voice.

        Through the pain she forces an odd smile.

                                 THEO (Cont'd)
                     Now just say goodbye.

        But she isn't saying anything more.  She releases his hand.
        Her head slumps to the side.  She's dead.  He looks at her
        for a long moment -- sadly -- before leaving her there.

        INT. ENTRY HALL

        Theo pauses by Grillo's body and searches his pockets.  He
        finds his own car keys.

        EXT. THE OLD SPANISH HOUSE - DAY

        As Theo emerges and crosses to his Chrysler, peers inside --

        THEO'S POV - THE MONEY, THE BONDS - THE ATTACHE CASE

        All where Lenore and Grillo left them on the seat.

        WIDER SHOT - IN CAR

        As Theo stuffs everything of value into the backpack and
        tosses it on the floor next to him.

        He starts the engine and backs out.

        He executes a turn and heads back down the hill.

        He doesn't look back.

        EXT. THE ROAD STRETCHING BELOW THE GETTY MUSEUM - DAY

        As Theo drives safely away.

        INT. THEO'S CAR

        He hits Sunset and keeps going.

        After a moment he reaches over into the backpack and
        retrieves his own cellular for one final call.  He dials
        411 --

                                 THEO
                           (into phone)
                     Information -- I need a number for
                     the United Airlines shuttle to San
                     Francisco.

        It seems he's taking Lenore's advice after all.  But the
        call is interrupted by a shrill beeping.

        The battery has finally run out.

        Theo looks down at the phone fondly.

                                 THEO
                     I take back every rotten thing I
                     said about you.

        The much despised cellular which got him into this -- has
        gotten him out of it and made him rich.

        The phone continues beeping plaintively as he smiles at it
        with a warmth reserved for old friend who's shared a lot of
        grief and whose time is now up.

                                 THEO
                     You did good.  Get some rest.

        Theo kisses the cellular lovingly -- then flips it off.
        CLICK!  SILENCE!

        BLACKOUT

                                  THE END








