






                                    
                                    HALLOWEEN

                                  a screenplay

                                       by

                                 John Carpenter

                                      and

                                   Debra Hill




















                                                        SHOOTING DRAFT
                                                        REV. 4-10-78

                                                        SCENE/SHOT NUMBERS
                                                        REMOVED











               MAIN TITLE SEQUENCE

               OPEN on a black screen. SUPERIMPOSE in dark red letters:

                                       HALLOWEEN

               Then we slowly:

               FADE IN TO:

               Darkness, with a small shape in the center of the screen. 
               As MAIN TITLES CONTINUE OVER, CAMERA SLOWLY MOVES IN on 
               the shape.

               We get closer and closer until we see that the shape is a 
               Halloween mask. It is a large, full-head platex rubber 
               mask, not a monster or ghoul, but the pale, neutral features 
               of a man weirdly distorted by the rubber. .

               Finally CAMERA MOVES IN CLOSE on the eye of the mask. It 
               is blank, empty, a dark, staring socket.. SUPERIMPOSE FINAL

               CREDIT.

                                                               FADE OUT:

               FADE IN:

               Black screen.  SUPERIMPOSE:

                                 HADDONFIELD, ILLINOIS

                                   OCTOBER 31, 1963

                                                            DISSOLVE TO:

               EXT./INT. MYERS HOUSE -- NIGHT -- SUBJECTIVE POV 
               (PANAGLIDE)

               It is night. We move toward the rear of a house through 
               Someone's POV. CAMERA MOVES UP to a Jack-o'-lantern glowing 
               brightly on a windowsill. It is a windy night and the 
               curtains around the Jack-o'-lantern ruffle back and forth.

               Suddenly we hear voices from inside the house.

                                     SISTER (V.O.)
                         My parents won't be back till ten.

                                     BOYFRIEND (V.O.)
                         Are you sure?

               Then LAUGHTER.

               The POV moves from the Jack-o'-lantern down to another 
               window and peers inside. We see the sister's bedroom through 
               the blowing curtains.

               Into the bedroom comes the SISTER, 18, very pretty. She 
               GIGGLES as the BOYFRIEND jumps into the room. Also 18, he 
               wears a Halloween mask and costume.

                                     BOYFRIEND
                              (continuing)
                         We're all alone, aren't we?

                                     SISTER
                         Michael's around someplace....

               The boyfriend grabs the sister and kisses her.

                                     SISTER
                              (continuing)
                         Take off that thing.

               The boyfriend rips off his mask. He is a handsome young 
               man underneath. They kiss again, this time with more 
               passion. The boyfriend begins to unbutton the sister's 
               blouse. She responds to him.

               The POV swings away from the window and begins to restlessly 
               pace back and forth, agitated, disturbed. We HEAR THE SOUNDS 
               of the sister and boyfriend inside the bedroom growing 
               more and more passionate.

               Finally the POV moves back up to the window. Inside through 
               the moving curtains, we see the sister and the boyfriend 
               on the bed, naked, making love.

               The POV springs back from the window and stalks quickly 
               down the side of the house, past the Jack-o'-lantern, around 
               to a door. Quietly the door is opened and the POV moves 
               inside.

               The POV glides silently through the house into the kitchen, 
               up to a drawer. The drawer is opened. A large butcher knife 
               is withdrawn.

               Then the POV swings around and moves to the kitchen door. 
               We look down a hallway to the front door. The boyfriend 
               steps out of the bedroom door, buttoning his shirt. The 
               sister stands in the doorway, a sheet wrapped around her.

                                     BOYFRIEND
                         I gotta go.

                                     SISTER
                         Will you call me tomorrow?

                                     BOYFRIEND
                         Yeah, sure.

                                     SISTER
                         Promise?

                                     BOYFRIEND
                         Yeah.

               They kiss again and the boyfriend walks to the front door.  
               The sister watches as he leaves and shuts the door behind 
               him. Then she turns and steps back into the bedroom.

               The POV moves slowly down the hall to the bedroom door and 
               peers around inside. The sister sits at her night-table 
               brushing her hair. She is still completely nude.

               Slowly the POV moves into the room. Suddenly we move down 
               to the discarded Halloween mask on the floor. The POV bends 
               down and picks it up. Then suddenly the POV is covered by 
               the mask and we see through the eye-holes.

               The POV moves up behind the sister. Sensing a presence, 
               she spins around and stares at the POV, covering her breasts 
               quickly.

                                     SISTER
                         Michael...?

               Suddenly the POV lunges forward. The sister continues to 
               stare incredulously. There is a rapid blur as the POV drives 
               the butcher knife into the sister's chest and out again 
               almost before we've seen it.

               The sister looks down at the blood forming at her hands, 
               then

               back up at the POV with an astonished disbelief.

               Then in a wild paroxysm the butcher knife blurs continuously 
               in and out of frame, slashing the sister mercilessly. She 
               begins to SCREAM, trying to fend off the blows with her 
               hands, then suddenly falls out of frame to the floor.

               The POV moves back away from the sister's lifeless body, 
               spins around and careens out of the bedroom.

               At top speed the POV races through the darkened house, to 
               the front door, out the door, down the steps and rapidly 
               up the street. The CAMERA careens along in frenzied flight, 
               up the sidewalk, up a small side alley, down someone's 
               backyard, then to a sudden, abrupt halt in front of MOTHER 
               and FATHER just coming out of a neighbor's house.

               Mother and Father stare at the POV, at first in puzzlement, 
               then slow, growing horror.

                                     MOTHER
                         Michael?

               CLOSE SHOT -- MICHAEL -- CRANE

               The father's hand reaches up and rips off the Halloween 
               mask, revealing MICHAEL, 6, underneath, a bright-eyed boy 
               with a calm, quiet smile on his face. CAMERA PULLS BACK, 
               revealing the blood-stained butcher knife in his hand, 
               then further back, CRANING UP past his parents standing 
               there, up from the neighbor's house to a HIGH SHOT of the 
               neighborhood as the sounds of POLICE SIRENS rise in the 
               distance.

                                                               FADE OUT:

               FADE IN TO:

               BLACK. SUPERIMPOSE:

                                SMITH'S GROVE, ILLINOIS

                                   OCTOBER 30, 1978

                                                            DISSOLVE TO:

               EXT. HIGHWAY -- RAIN -- NIGHT

               Two headlights appear in the darkness, backlighting the 
               rain that pours down on a lonely strip of highway. A station 
               wagon HISSES along the wet road surface.

               INT. STATION WAGON -- NIGHT

               The back seat is separated from the front by a wire-mesh 
               screen, much like a police car. MARION, 30, drives. She is 
               dressed in a crisp, white nurse's uniform. Next to her in 
               the passenger seat is SAM LOOMIS, a clinical psychiatrist. 
               He is a tough-looking man in his forties who flips through 
               pages in a manila folder.

                                     LOOMIS
                         ...then he gets another physical 
                         by the state, and he makes his 
                         appearance before the judge. That 
                         should take four hours if we're 
                         lucky, then we're on our way.

                                     MARION
                         What did you use before?

                                     LOOMIS
                         Thorazine.

                                     MARION
                         He'll barely be able to sit up.

                                     LOOMIS
                         That's the idea.  Here we are.

               POV THROUGH WINDSHIELD -- SANITARIUM

               Through the rain we see a large sign:

                       SMITH'S GROVE -- WARREN COUNTY SANITARIUM

               Behind the sign is the sanitarium itself, a cold-looking 
               building surrounded by a fence.

               INT. STATION WAGON

                                     LOOMIS
                              (Continuing)
                         The driveway's a few hundred yards 
                         up on your right.

                                     MARION
                         Are there any special instructions?

                                     LOOMIS
                         Just try to understand what we're 
                         dealing with here. Don't 
                         underestimate it.

                                     MARION
                         I think we should refer to 'it' as 
                         'him.'

                                     LOOMIS
                         If you say so.

                                     MARION
                         Your compassion is overwhelming, . 
                         Doctor.

               Loomis glances at Marion as she lights a cigarette. She 
               shoves the matches into the pack and tosses it on the 
               dashboard. Loomis stares at the cigarette pack. The pack 
               of matches reads: "The Rabbit in Red Lounge -- Entertainment 
               Nightly." Loomis turns his eyes back to the rain-slicked 
               road.

                                     LOOMIS
                         Ever done anything like this before?

                                     MARION
                         Only minimum security.

                                     LOOMIS
                         I see.

                                     MARION
                              (defensively)
                         What does that mean?

                                     LOOMIS
                         It means... I see.

                                     MARION
                         You don't have to make this any 
                         harder than it already is.

                                     LOOMIS
                         I couldn't if I tried.

                                     MARION
                         The only thing that ever bothers 
                         me is their gibberish. When they 
                         start raving on and on...

                                     LOOMIS
                         You don't have anything to worry 
                         about. He hasn't spoken a word in 
                         15 years.

               Both of them suddenly stare out the windshield in front of 
               them.

               POV THROUGH WINDSHIELD -- FIELD

               Through the rain we see a field off to the side of the 
               road. Dimly lit by the car headlights are FIVE PATIENTS, 
               dressed in wind-blown white gowns, drenched by the rain, 
               wandering aimlessly around the field.

               INT. STATION WAGON

                                     MARION
                         Since when do they let them wander 
                         around?

               They look up ahead.

               POV THROUGH WINDSHIELD -- PATIENT

               Standing by the side of the road is a MALE PATIENT, a wild-
               looking man in his sixties dressed in a white gown, who 
               stares at the station wagon.

               INT. STATION WAGON

               Marion slows the station wagon and pulls off to the side 
               of the road. Loomis jumps out.

               POV THROUGH WINDSHIELD -- LOOMIS AND PATIENT

               Through the windshield we see Loomis rush over to the 
               patient, stand and talk for a moment, then hurry back.

               INT. STATION WAGON

               Loomis climbs back in, dripping from the rain.

                                     LOOMIS
                         Pull up to the entrance!

                                     MARION
                         Shouldn't we pick him up?

                                     LOOMIS
                         Move it!

               Marion starts down the road.

                                     MARION
                         What did he say?

                                     LOOMIS
                         He asked me if I could help him 
                         find his purple lawn mower.

                                     MARION
                         I don't think this is any time to 
                         be funny...

                                     LOOMIS
                         He said something else. "It's all 
                         right now. He's gone. The evil's 
                         gone."

               POV THROUGH WINDSHIELD -- SANITARIUM DRIVE

               Ahead of them is the entrance to the sanitarium.

               INT. STATION WAGON

               Marion slows down to turn.

               Through the rear window we see a SHAPE spring up out of 
               the darkness, streak through the rain and leap up on the 
               rear of the station wagon.

               The station wagon bounces up and down. The roof sags in 
               and out with the weight of someone on top.

                                     MARION
                         Something fell on the roof.

               The roof continues to buckle in and out wildly.

                                     LOOMIS
                         Something jumped on the roof...

               Marion stops and rolls down her window to look outside.

               Loomis opens his door and steps out. Suddenly he is hit in 
               the face by a powerful fist from the roof. Loomis staggers 
               backwards and falls by the side of the road.

               Marion starts to react. Suddenly a hand reaches in through 
               the window and lunges at her.

               The fingers grab her hair. She SCREAMS. The fingers tighten 
               around her hair and the hand pulls Marion roughly to the 
               window.

               Twisted around in the seat, Marion's foot jams down all 
               the way on the gas pedal. The station wagon ROARS forward.

               Marion continues to SCREAM, clawing at the hand.

               POV THROUGH WINDSHIELD -- ROAD

               Through the rain the road spins crazily ahead, the wipers 
               erasing sheets of rain.

               Suddenly the other hand reaches down from the roof and 
               grabs the wiper, holding it tightly. Rain splashes on the 
               windshield obscuring the road.

               INT. STATION WAGON

               The hand rips at Marion's hair. SCREAMING. Clawing.

               POV THROUGH Windshield 

               The windshield is completely obliterated by rain.

               INT. STATION WAGON

               The station wagon skids and WHAMS into the shoulder on the 
               Side of the road. Marion is hurled across the seat against 
               the passenger door.

               Suddenly the hand springs down from above and SLAMS against 
               the passenger window, shattering it.

               SHRIEKING, Marion scurries across the front seat, opens 
               the driver's door and scrambles out.

               EXT. ROAD -- STATION WAGON

               Marion frantically crawls her way across the rain-drenched 
               road away from the station wagon. CAMERA TRACKS with her 
               as she slides down into the muddy shoulder. She looks back.

               POV -- STATION WAGON

               From the shoulder we see the station wagon in the rain, 
               and the shape jump in the driver's seat and SLAM the door.

               Then the station wagon takes off and disappears down the 
               road into the darkness.

               ANGLE ON SHOULDER

               Loomis runs up out of the rain and helps Marion to her 
               feet.  She CRIES hysterically. Loomis stares off down the 
               road at the disappearing taillights.

                                     LOOMIS
                         You can calm down. The evil's gone.

                                                               FADE OUT:

               FADE IN TO:

               BLACK SCREEN. SUPERIMPOSE:

                                      HADDONFIELD

                                   OCTOBER 31, 1978

                                                            DISSOLVE TO:

               EXT. LAURIE'S HOUSE -- DAY

               LAURIE, 17 and pretty in a quiet sort of way, steps out of 
               her two-story frame house, down the front walk to the 
               street. Her face has a soft, innocent quality, her eyes 
               bright and alive. Her FATHER steps out of the door behind 
               her and walks to the car in the driveway. His car has 
               "STRODE REAL ESTATE" emblazoned on the side door.

                                     FATHER
                         Don't forget to drop off the key 
                         at the Myers place...

                                     LAURIE
                         I won't.

                                     FATHER
                         They're coming by to see the house 
                         at 10:30. Be sure you leave it 
                         under the mat...

                                     LAURIE
                         I promise.

               TRACKING SHOT -- LAURIE

               CAMERA MOVES with Laurie as she walks down the residential 
               street. She carries a large bundle of schoolbooks in her 
               arms. Across a backyard TOMMY DOYLE, an eight-year-old boy 
               with tousled brown hair and bright blue eyes comes running 
               with his books.

                                     TOMMY
                         Hey, Laurie...

                                     LAURIE
                         Hi, Tommy.

               He catches up with her and they walk along down the street.

                                     TOMMY
                         Are you coming over tonight?

                                     LAURIE
                         Same time, same place.

                                     TOMMY
                         Can we make Jack-o'-lanterns?

                                     LAURIE
                         Sure.

                                     TOMMY
                         Can we watch the monster movies?

                                     LAURIE
                         Sure.

                                     TOMMY
                         Will you read to me? Can we make 
                         popcorn?

                                     LAURIE
                         Sure. Sure.

               They walk up to the front of the old, two-story Myers house 
               set back from the street. It is now weather-beaten and 
               dilapidated. Laurie walks through the front gate and starts 
               up toward the porch.

                                     TOMMY
                         You're not supposed to go up there.

               Laurie holds up a key.

                                     LAURIE
                         Yes, I am.

                                     TOMMY
                         Uh-uh. That's a spook house.

                                     LAURIE
                         Just watch.

               Laurie strolls up to the front porch. She bends down, lifts 
               the welcome mat and places the key under it.

               INT. MYERS HOUSE -- THROUGH WINDOW

               Through a front window, we see Laurie bending over the 
               welcome mat. Suddenly a dark shape, the outline of a man, 
               leans forward, watching her. As she walks back to Tommy at 
               the street the shape moves to watch them, then fades back 
               into the interior of the house.

               TRACKING SHOT -- LAURIE AND TOMMY

               Laurie and Tommy continue walking down the street.

                                     TOMMY
                         Lonnie Elam said never to go up 
                         there. Lonnie Elam said that's a 
                         haunted house. He said real awful 
                         stuff happened there once.

                                     LAURIE
                         Lonnie Elam probably won't get out 
                         of sixth grade.

               Tommy breaks stride and runs across the street.

                                     TOMMY
                         I gotta go.  I'll see you tonight.

                                     LAURIE
                         See you.

               Laurie continues walking alone. She begins to sing quietly 
               to herself.

                                     LAURIE
                              (sings)
                         I wish I had you all alone...
                         Just the two of us...
                         I would hold you close to me...
                         So close to me...

               ANGLE DOWN STREET

               We see Laurie walking off down the street in the distance.  
               CLOSE TO CAMERA the dark shape moves into frame, watching 
               Laurie disappear around the corner.

                                     LAURIE
                              (sings, continuing)
                         Just the two of us...
                         So close to me...

                                                                 CUT TO:

               EXT. SANITARIUM -- DAY

               Sam Loomis strides quickly out of the front of the 
               sanitarium followed immediately by DR. WYNN, a gray-haired 
               man in his forties. CAMERA TRACKS with them across the 
               parking lot.

                                     WYNN
                         I'm not responsible, Sam.

                                     LOOMIS
                              (angrily)
                         Of course not.

                                     WYNN
                         I've given them his profile.

                                     LOOMIS
                         You must have told them we shocked 
                         him into a grinning idiot. Two 
                         roadblocks and an all-points 
                         bulletin wouldn't stop a five-year 
                         old!

               Loomis reaches a car and unlocks it.

                                     WYNN
                         He was your patient, Doctor. If 
                         the precautions weren't sufficient, 
                         you should have notified...

                                     LOOMIS
                         I notified everybody! Nobody 
                         listened.

                                     WYNN
                         There's nothing else I can do.

                                     LOOMIS
                         You can get back on the telephone 
                         and tell them exactly what walked 
                         out of here last night. And tell 
                         them where he's going.

                                     WYNN
                         Probably going.

                                     LOOMIS
                         I'm wasting time.

               Loomis gets in the car. Wynn leans down to the window.

                                     WYNN
                         Sam, Haddonfield is a hundred and 
                         fifty miles from here. How could 
                         he get there, he can't drive?

                                     LOOMIS
                         He was doing all right last night.
                         Maybe somebody around here gave 
                         him lessons.

               Loomis starts up the car and pulls away from the sanitarium.

               Wynn watches him go, then hurries back into the building.

                                                                 CUT TO:

               INT. CLASSROOM -- DAY

               Laurie sits at the back of a classroom of HIGH SCHOOL 
               STUDENTS. CAMERA MOVES IN on her as a TEACHER drones away 
               at the front of the room.

                                     TEACHER (V.O.)
                         ...and the book ends, but what 
                         Samuels is really talking about 
                         here is fate.

               CAMERA MOVES to a CLOSE-UP of Laurie. She barely listens 
               to the teacher as she doodles in her notebook in front of 
               her.

                                     TEACHER
                              (continuing)
                         You see, fate caught up with several 
                         lives here. No matter what course 
                         of action Rollins took, he was 
                         destined to his own fate, his own 
                         day of reckoning with himself.
                         The idea is that destiny is a very 
                         real, concrete thing that every . 
                         person has to deal with.

               Laurie lets her gaze move to a window. She stares dreamily 
               outside.

               LAURIE'S POV -- STREET

               From the window she can see the street, and a station wagon 
               parked along the sidewalk.

               Behind the station wagon stands the shape of a man. We 
               can't quite see his features from here, but it is clear 
               that he is looking in the school window.

               ANGLE ON LAURIE

               She turns away from the window and begins to doodle again.

               ANGLE ON NOTEBOOK

               We see Laurie draw:

                                     LAURI STRODE 
                                     TEACHER (V.O.)
                              (continuing)
                         Edwin, how does Samuel's view of 
                         fate differ from that of Costaine?

               ANGLE ON LAURIE

               She glances up from the book and out the window again.

               LAURIE'S POV -- STREET

               The shape behind the station wagon is still there and 
               staring right at her.

               ANGLE ON LAURIE

               She frowns, staring back at the shape.

                                     EDWIN (V.O.)
                         Uh... doesn't he feel that no matter 
                         how complicated something is, it's 
                         also really simple too?

                                     TEACHER (V.O.)
                         No.
                              (pause)
                         Laurie.

               This springs her around from the window.

                                     LAURIE
                         M'am?

                                     TEACHER (V.O.)
                         Answer the question.

                                     LAURIE
                         Costaine wrote that fate was somehow 
                         related only to religion, where 
                         Samuels felt that fate was like a 
                         natural element, like earth, air, 
                         fire and water.

                                     TEACHER (V.O.)
                         That's right, Samuels definitely 
                         personified fate...

               Laurie sneaks a glance back to the window.

               LAURIE'S POV -- STREET

               The shape and the station wagon are gone.

               ANGLE ON LAURIE

               She turns back from the window and back to her notebook.

               ANGLE ON NOTEBOOK

               She has written:

                               "LAURIE STRODE IS LONELY"

                                                                 CUT TO:

               EXT. GAS STATION -- HIGHWAY -- DAY

               We see a car parked in front of a small, closed-down gas 
               station/diner by the side of the highway. CAMERA SLOWLY 
               TRACKS over to a phone booth. Loomis is inside on the 
               telephone.

                                     LOOMIS
                              (into telephone)
                         No, not since Thursday.
                              (pause)
                         Yes, yes I'm all right. Stop 
                         worrying. After this I'll sleep 
                         for a week, two weeks...
                              (pause)
                         I said I'm all right. Believe me. 
                         I'll be home soon. Yes I do. Very 
                         much. I just... have to stop him...  
                         Of course it's possible, but I 
                         know him. And when he gets there, 
                         God help us.
                              (pause)
                         Right, right, I'll call you. Me 
                         too. Goodbye.

               Loomis hangs up the phone and steps out of the booth. He 
               looks up the highway.

               LOOMIS' POV -- HIGHWAY

               The highway disappears off into the distance. There is an 
               old weather-beaten sign that reads:

                                 HADDONFIELD 73 MILES

               Just above the horizon huge clusters of clouds, dark and 
               ominous, are blown along by the wind.

               EXT. GAS STATION

               Loomis turns and walks back to his car. He glances at the 
               old gas station as he walks.

               LOOMIS' POV -- GAS STATION -- MOVING SHOT

               The building is dark, empty, dilapidated. On the padlocked 
               door are huge marks like the clawing of an animal wanting 
               to get in.

               ANGLE ON LOOMIS

               Loomis stops, stares at the door and then slowly walks 
               over to it. He touches the marks with his hands, then looks 
               at the dirt driveway around the building.

               LOOMIS' POV -- DRIVEWAY

               There are definite tire tracks leading from the highway up 
               to the door, then back to the highway again.

               Then his gaze returns to a discarded object crushed in the 
               dirt of the driveway: a pack of cigarettes.

               ANGLE ON LOOMIS

               He picks up the cigarette pack.

               CLOSE SHOT -- CIGARETTE PACK

               Stuck in the cellophane of the crushed pack are matches:

               "The Rabbit in Red Lounge -- Entertainment Nightly."

               EXT. GAS STATION

               Loomis turns and quickly strides back to his car, gets in 
               and roars away from the lonely gas station.

                                                                 CUT TO:

               EXT. SCHOOLYARD -- DAY

               The playground is filled with CHILDREN just getting out of 
               school for the day. Some are dressed in Halloween costumes, 
               some carry pumpkins and orange and black streamers, some 
               carry Jack-o'-lanterns.

               Tommy Doyle comes out of the door carrying a very large 
               pumpkin. He is followed by 3 BOYS, RICHIE, KEITH and LONNIE, 
               who are LAUGHING and pushing him.

                                     TOMMY
                         Leave me alone!

                                     LONNIE
                         He's gonna get you!

               Lonnie runs up to Tommy and wiggles his fingers in Tommy's 
               face. The other boys form a circle around Tommy and taunt 
               him. In unison they sing:

                                     BOYS
                         He's gonna get you, he's gonna get 
                         you...

                                     LONNIE
                         The Boogeyman is coming!

                                     TOMMY
                         No he's not. Leave me alone.

                                     LONNIE
                         He doesn't believe us. Don't you 
                         know what happens on Halloween?

                                     TOMMY
                         Yeah, we get candy.

               The boys LAUGH. Richie runs up to Tommy and makes a face.

                                     RICHIE
                         Oooooo! The Boogeyman!

               The other boys join in the chant.

                                     BOYS
                              (in unison)
                         The Boogeyman, the Boogeyman, the 
                         Boogeyman...

               Tommy turns from them and starts to run away. Richie sticks 
               out his foot. Tommy trips and falls to the concrete, 
               SMASHING his pumpkin beneath him. The other boys run away 
               GIGGLING and SCREAMING with delight.

               PLAYGROUND ENTRANCE -- GATE

               As the boys race out of the playground, Richie barrels 
               through the gate and runs right into the dark shape.

               We don't see the shape's face, just his lower body. He is 
               dressed in pants and a shirt that look too big for him. He 
               grabs Richie and holds him back at arm's length.

               A large object falls out of his pocket. Richie quickly 
               stares down at it. The shape lifts his foot and SMACKS it 
               down over the object to hide it. Quickly Richie and the 
               other 2 boys run around the man and on down the block.

               The shape lifts his foot. Underneath it is a large butcher 
               knife. He quickly picks it up and shoves it into his pocket.

               Slowly the shape turns and walks away from the playground 
               gate, CAMERA TRACKING WITH HIM. Across from him in the 
               playground we see Tommy get to his feet, wiping the 
               demolished pumpkin off his shirt and pants.

               We TRACK WITH THE shape to a station wagon. On the side of 
               the door is a state emblem.

               INT. STATION WAGON

               The shape gets in the station wagon. We still don't see 
               his face. Separating the front and back seats is the wire-
               mesh screen. It is Loomis' vehicle. The shape starts the 
               engine. He pulls away from the curb.

               POV FROM WINDOW

               Slowly the station wagon moves down the street. We see 
               Tommy hurrying along the sidewalk, still rubbing off the 
               pumpkin splatter. Tommy turns off the sidewalk and cuts up 
               a side alley.

               The wagon picks up speed and continues on down the street.

               EXT. HIGH SCHOOL -- DAY

               Laurie and LYNDA stroll down the front steps of the high 
               school and turn up the street. Laurie carries another large 
               stack of books. Lynda is a knockout in tight jeans and 
               tight T-shirt. She carries no books. CAMERA TRACKS WITH 
               THEM up the street.

                                     LYNDA
                         It's totally insane!  We have three 
                         new cheers to learn in the morning, 
                         the game in the afternoon, I get 
                         my hair done at five, and the dance 
                         is at eight. I'll be totally wiped 
                         out!

                                     LAURIE
                         I think you have too much to do 
                         tomorrow.

                                     LYNDA
                         Totally!

                                     LAURIE
                         As usual, I don't have anything to 
                         do.

                                     LYNDA
                         It's your own fault and I don't 
                         feel sorry for you.

               ANNIE comes out of the side doors of the high school and 
               calls after Laurie and Lynda.

                                     ANNIE
                         Hey, Lynda, Laurie!

               The girls stop and wait for Annie.

                                     ANNIE
                              (continuing)
                         Why didn't you wait for me?

                                     LYNDA
                         We did. Fifteen minutes. You totally 
                         never showed up.

                                     ANNIE
                         That's not true. Here I am.

                                     LAURIE
                         What's wrong, Annie? You're not 
                         smiling.

                                     ANNIE
                         I'm never smiling again. Paul 
                         dragged me into the boy's locker 
                         room to tell me...

                                     LAURIE
                         Exploring uncharted territory?

                                     LYNDA
                         It's been totally charted.

                                     ANNIE
                         We just talked.

                                     LYNDA
                         Sure.

                                     ANNIE
                         Old jerko got caught throwing eggs 
                         and soaping windows. His parents 
                         grounded him for the weekend. He 
                         can't come over tonight.

                                     LAURIE
                         I thought you were baby-sitting 
                         tonight.

                                     LYNDA
                         The only reason she baby-sits is 
                         to have a place to...

               Laurie suddenly stops and turns back toward the school.

                                     LAURIE
                         Shit!

                                     ANNIE
                              (indignant)
                         I have a place for that.

                                     LAURIE
                         I forgot my chemistry book.

                                     LYNDA
                         Who cares? I always forget my 
                         chemistry book.

               Laurie glances down the street.

               LAURIE'S POV -- STATION WAGON

               The station wagon slowly moves up the street toward them. 
               The shape isn't visible behind the windshield.

               ANGLE ON GIRLS

                                     LYNDA
                         Isn't that Davon Graham?  He's 
                         cute.

                                     LAURIE
                         don't think so...I

               Laurie stares at the station wagon as it moves past. She 
               looks directly at the shape inside. There is a quick glimpse 
               of him, a strange pale face staring back.

               INT. STATION WAGON

               The shape is close to CAMERA, out of focus. Out the window 
               we see the three girls on the sidewalk.

               The shape stares at Laurie looking back at him, then tromps 
               on the accelerator. The wagon whizzes past them.

               ANGLE ON GIRLS

                                     ANNIE
                         (yells after the car)
                         Speed kills!

               POV -- STATION WAGON

               Up the street the wagon suddenly stops. It sits there, 
               waiting.

               ANGLE ON GIRLS

                                     ANNIE
                              (softer now)
                         Can't you take a joke?

               POV -- STATION WAGON

               For a moment the station wagon just sits there. Then it 
               takes off down the street and disappears around a corner.

               ANGLE ON GIRLS

                                     LAURIE
                         Annie, some day you're going to 
                         get all of us in deep trouble.

                                     LYNDA
                         Totally.

                                     ANNIE
                         I hate a guy with a car and no 
                         sense of humor.

               The girls start walking again. Laurie is quiet, puzzled by 
               the appearance of the man in the car.

                                     LYNDA
                         Well, are we still on for tonight?

                                     ANNIE
                              (coldly)
                         I wouldn't want to get you in deep 
                         trouble, Lynda.

                                     LYNDA
                         Come on, Annie. Bob and I have 
                         been planning on it all week.

                                     ANNIE
                         All right. The Wallaces leave at 
                         seven.

                                     LAURIE
                              (excited)
                         I'm baby-sitting for the Doyles.  
                         It's only three houses away. We 
                         can keep each other company.

                                     ANNIE
                         Terrific. I've got three choices.

               Watch the kid sleep, listen to Lynda screw or talk to you.

                                                                 CUT TO:

               EXT. RESIDENTIAL STREET -- DAY

               The three girls stop in front of Lynda's house, a modest 
               suburban home on a quiet, tree-lined street.

                                     ANNIE
                         What time?

                                     LYNDA
                         I don't know yet. I have to get 
                         out of taking my stupid brother 
                         trick or treating.

                                     ANNIE
                         Saving the treats for Bob?

                                     LYNDA
                         Fun-ny. See you.

               Lynda strolls up to her house. Annie and Laurie start down 
               the street. CAMERA MOVES IN to a CLOSE SHOT of Laurie's 
               face. She stares ahead along the sidewalk.

               LAURIE'S POV -- MOVING SHOT -- BUSHES

               Up the sidewalk is a series of bushes lining the street.  
               There, partially hidden in the shadows of a bush, is the 
               shape of a man, watching them. He is barely visible, almost 
               blending in with the dark foliage.

               ANGLE ON LAURIE -- ANNIE

                                     LAURIE
                         Look.

                                     ANNIE
                         Look where?

                                     LAURIE
                         Behind that bush there.Annie looks.

               POV -- MOVING SHOT -- BUSHES

               The shape is gone. Just bushes.

               ANGLE ON LAURIE -- ANNIE

                                     ANNIE
                         I don't see anything.

                                     LAURIE
                         That man who drove by so fast, the 
                         one you yelled at.

                                     ANNIE
                         Subtle, isn't he? Hey creep!

               Annie walks right over to the bushes and kicks them hard.

               Nothing happens.

                                     ANNIE
                              (continuing)
                         Laurie, my dear, he wants to talk 
                         to you.

               Laurie just stands on the sidewalk several feet from the 
               bushes.

                                     ANNIE
                              (continuing)
                         He wants to take you out tonight.

               Slowly Laurie walks over and stares at the bush.

                                     LAURIE
                         He was standing right here.

                                     ANNIE
                         Poor Laurie. You scared another 
                         one away.

                                     LAURIE
                         Cute.

               They start walking down the sidewalk again.

                                     ANNIE
                         It's tragic. You never go out.

               You must have a small fortune stashed from baby-sitting so 
               much.

                                     LAURIE
                         The guys think I'm too smart.

               Laurie glances back at the bushes behind them.

                                     ANNIE
                         I don't. I think you're whacko.

               You're seeing men behind bushes.

               The two girls stop in front of Annie's house, another small 
               suburban home.

                                     ANNIE
                              (continuing)
                         Well, home sweet home. I'll see 
                         you later.

                                     LAURIE
                         Okay. Bye.

               Annie walks up to her door.

               For a moment Laurie looks around cautiously before starting 
               down the sidewalk again, CAMERA TRACKING WITH HER. A strong 
               wind rises and blows her hair in front of her face. Again 
               she turns around and glances back down the street.

               LAURIE'S POV -- BUSHES

               There is still nothing there.

               ANGLE ON LAURIE

               Suddenly, Laurie walks right into a man standing on the 
               sidewalk in front of her. She SCREAMS and drops her books.

               It is LEE BRACKETT, Annie's father. He is a tall man in a 
               county sheriff's uniform. He quickly bends down and picks 
               up her books.

                                     BRACKETT
                         Excuse me, Laurie.

                                     LAURIE
                         Mister Brackett...

                                     BRACKETT
                         Didn't mean to startle you.

                                     LAURIE
                         It's okay...

                                     BRACKETT
                         Well, it's Halloween. I guess 
                         everybody's entitled to a good 
                         scare.

                                     LAURIE
                         Yes, sir. Nice seeing you.

               Brackett walks down the sidewalk to his house. Laurie 
               bundles her books and hurries up the street.

               EXT. LAURIE'S HOUSE -- DAY

               Laurie walks up on the front porch of her house. She pauses 
               a moment and glances down the street.

               LAURIE'S POV -- TRICK-OR-TREATERS

               Several CHILDREN in costumes are going door to door 
               collecting their treats.

               ANGLE ON LAURIE

                                     LAURIE
                              (to herself)
                         Well, kiddo, I thought you outgrew 
                         superstition.

               INT. LAURIE'S HOUSE -- DAY

               Laurie strolls through the living room. Through the doorway 
               into the kitchen we see LAURIE'S MOTHER busy making candied 
               apples.

                                     LAURIE
                         Hi, Mom, I'm home.

                                     LAURIE'S MOTHER
                         Laurie, Annie just called. She 
                         said call her back.Laurie turns 
                         and hurries up the stairs.

                                     LAURIE
                         Thanks, mom.

               INT. LAURIE'S ROOM

               Laurie walks into her bedroom. She tosses her books on the 
               bed and starts to her telephone.The wind blows her curtains 
               through the open window. Laurie crosses to the window and 
               leans up to close it.

               LAURIE'S POV -- BACKYARD

               From her room in the second story, Laurie can see into the 
               backyard next door.

               There is a clothesline with sheets blowing in the wind. In 
               between the sheets we glimpse the shape standing there, 
               looking up at Laurie.

               ANGLE ON LAURIE

               She freezes and stares down fearfully.

               LAURIE'S POV -- BACKYARD

               The sheets continue to twist and turn in the wind, but now 
               the shape is gone.

               ANGLE ON LAURIE

               Laurie SLAMS the window and locks it. She slowly walks to 
               the middle of her room and stands there for several moments, 
               unsure as to whether she has actually seen it.

               Suddenly, the phone RINGS, loud and shrill, startling 
               Laurie.

               She answers it.

                                     LAURIE
                         Hello.

               Silence.

                                     LAURIE
                              (continuing)
                         Hello?

               There is a SOUND from the receiver, like chewing...

                                     LAURIE
                              (continuing)
                         Who is this?

               The chewing continues. She slams the receiver down.

               Almost immediately, the phone RINGS again. Laurie looks at 
               it. It rings again. She picks it up.

                                     LAURIE
                         Hello?

                                     ANNIE (V.O.)
                         Why did you hang up on me?

                                     LAURIE
                         Annie, was that you?

                                     ANNIE (V.O.)
                         Of course.

                                     LAURIE
                         Why didn't you say anything? You 
                         scared me to death.

                                     ANNIE (V.O.)
                         I had my mouth full. Couldn't you 
                         hear me?

                                     LAURIE
                         I thought it was an obscene phone 
                         call.

                                     ANNIE (V.O.)
                         Now you hear obscene chewing.
                         You're losing it, Laurie.

                                     LAURIE
                         I've already lost it.

                                     ANNIE (V.O.)
                         I doubt that. Listen, my mother is 
                         letting me use her car. I'll pick 
                         you up. 6:30.

                                     LAURIE
                         Sure, see you later.

                                     ANNIE (V.O.)
                         Bye.

               Laurie hangs up.

                                     LAURIE
                              (to herself)
                         Calm down. This is ridiculous.

                                                                 CUT TO:

               EXT. GRAVEYARD -- DAY

               WIDE SHOT of an old graveyard on a windy hillside. CAMERA 
               BOOMS DOWN as a car pulls up on the small road in f.g. Sam 
               Loomis gets out, along with TAYLOR, the graveyard owner.  
               Taylor is a small, officious man in his late sixties. He 
               glances at a small notepad.

                                     TAYLOR
                         Let's see. Myers. Judith Myers. 
                         Row 18, plot 20. Over this way.

               The two men begin walking along through the graveyard, 
               winding around headstones and flowers.

                                     TAYLOR
                              (continuing)
                         Every town has something like this 
                         happen. I remember a guy over is 
                         Russellville. Charley Bowles. About 
                         fifteen years ago, he finished 
                         dinner, excused himself from the 
                         table, went out into the garage 
                         and got a hacksaw, then came back 
                         into the house, kissed his wife 
                         and two children goodbye, and then 
                         proceeded to...

                                     LOOMIS
                         Where are we?

                                     TAYLOR
                         Just right over there a ways. And 
                         I remember Judith Myers. Just 
                         couldn't believe it. A young boy 
                         like that...

               Taylor stops cold.

                                     LOOMIS
                         Lost?

                                     TAYLOR
                              (sadly)
                         Why do they do it?

               He points to a plot right in front of them. Loomis stares.

               The headstone is missing, uprooted from the ground.

                                     TAYLOR
                         Goddamn kids.  They'll do anything 
                         on Halloween.

                                     LOOMIS
                         Whose grave is it?

               Taylor checks his notebook, then counts the rows and plots.

                                     TAYLOR
                         18, 20... Judith Myers...

               Taylor gives Loomis a quizzical look. Loomis shakes his 
               head and looks out across the graveyard.

                                     LOOMIS
                         He came home...

                                                                 CUT TO:

               EXT. LAURIE'S HOUSE -- DUSK

               CAMERA BEGINS on the trees that line the residential street, 
               twisting and writhing in the dusk wind. SLOWLY CAMERA BOOMS 
               DOWN to Laurie waiting outside her house by the street. 
               She carries a tote bag with schoolbooks and knitting needles 
               stuck inside, and a large pumpkin. The sun is a pale glow 
               behind the trees.

               Laurie turns her gaze down the street

               LAURIE'S POV -- TRICK-OR-TREATERS

               More CHILDREN in costumes walk from house to house, some 
               with MOTHERS and SISTERS, trick or treating. The wind blows 
               their costumes, billowing them outward.

               ANGLE ON LAURIE

               She watches the trick-or-treaters as a car swings around 
               the corner and pulls up in front of her. It is Annie.

                                     ANNIE
                         Hurry up.

               Laurie walks around to the passenger door and gets in.

               INT. ANNIE'S CAR -- DUSK

               Annie pulls away from the curb and hands Laurie a joint.

                                     ANNIE
                         We just have time.

               Laurie lights the joint and puffs vigorously.

                                     ANNIE
                              (continuing)
                         You still spooked?

                                     LAURIE
                         I wasn't spooked.

                                     ANNIE
                         Lies.

                                     LAURIE
                         I saw someone standing in Mr.
                         Riddle's backyard.

                                     ANNIE
                         Probably Mister Riddle.

                                     LAURIE
                         He was watching me.

                                     ANNIE
                         Mister Riddle was watching you?
                         Laurie, Mister Riddle is eighty-
                         seven.

                                     LAURIE
                         He can still watch.

                                     ANNIE
                         That's probably all he can do.

               Behind them through the rear-view mirror, we see Loomis' 
               station wagon pull out of an alley and follow along.

                                     ANNIE
                              (continuing)
                         What's the pumpkin for?

                                     LAURIE
                         I brought it for Tommy. I figured 
                         making a Jack-o'-lantern would 
                         keep him occupied.

                                     ANNIE
                         I always said you'd make a fabulous 
                         girl scout.

                                     LAURIE
                         Thanks.

                                     ANNIE
                         For that matter, I might as well 
                         be a girl scout tonight. I plan on 
                         making popcorn and watching Doctor 
                         Dementia.
                              (cont'd)
                         Six straight hours of horror movies. 
                         Little Lindsey Wallace won't know 
                         what hit her.

               EXT. HADDONFIELD SQUARE -- DUSK

               Annie's car drives through the main square of Haddonfield. 
               Following behind is the station wagon.

               INT. ANNIE'S CAR

               Annie points up ahead and quickly hides the joint.

                                     ANNIE
                         My dad!

               POV THROUGH WINDSHIELD

               Two police cars are parked in the street in front of Nichols 
               Hardware Store. An ALARM BELL inside the store CLANGS 
               SHRILLY.

               INT. ANNIE'S CAR

               They quickly roll down the windows and begin wildly clearing 
               out the marijuana smoke. Behind them the station wagon 
               disappears off down a side street.

               ANGLE ON POLICE CARS

               Annie's car stops at the police cars. Lee Brackett strolls 
               out to the car and leans down to the window.

                                     BRACKETT
                         Hi, Annie, Laurie...

                                     ANNIE
                         Hi, Dad. What happened?

                                     BRACKETT
                              (strains to hear 
                              over the alarm)
                         What?

                                     ANNIE
                         What happened?

                                     BRACKETT
                         Someone broke in the hardware store. 
                         Probably kids.

                                     ANNIE
                         You blame everything on kids.

                                     BRACKETT
                         The only things missing were some 
                         Halloween masks, rope, a set of 
                         knives. What does that sound like 
                         to you?

               Annie turns to Laurie.

                                     ANNIE
                         It's hard growing up with a cynical 
                         father.

               Behind Brackett, Sam Loomis walks up the street. We see 
               Loomis talk to a COP who points to Brackett.

                                     BRACKETT
                         You're going to be late at the 
                         Doyle's, Annie.

                                     ANNIE
                              (unable to hear 
                              over the alarm)
                         Huh?

               Just as Brackett is about to speak the alarm goes off.

                                     BRACKETT
                              (shouts)
                         You're going to be late!

                                     ANNIE
                              (to Laurie)
                         He shouts, too.

               Brackett smiles as Loomis walks up behind him.

                                     BRACKETT
                         Goodbye, girls.

                                     ANNIE & LAURIE
                         Bye.

               Annie's car pulls away.

                                     LOOMIS
                         Sheriff? I'm Doctor Sam Loomis.

                                     BRACKETT
                         Lee Brackett.

               As they talk CAMERA SLOWLY MOVES AROUND THEM to a view of 
               the street.

                                     LOOMIS
                         I'd like to talk with you, if I 
                         could.

                                     BRACKETT
                         May be a few minutes. I gotta stick 
                         around here...

                                     LOOMIS
                         It's important.

               Loomis' station wagon moves by behind them. Loomis doesn't 
               see it.

                                     BRACKETT
                         Ten minutes.

                                     LOOMIS
                         I'll be there.

                                                                 CUT TO:

               EXT. MOON -- NIGHT

               Through the blowing trees we see the full moon rising in 
               the night sky. There are SOUNDS of wind and CHIRPING 
               CRICKETS.

               EXT. RESIDENTIAL STREET -- NIGHT

               Annie's car moves down a quiet little residential street 
               and pulls up in front of a two-story house set back from 
               the street: the Doyle house.

               ANGLE FROM STATION WAGON

               We are in the front seat of the station wagon. Through the 
               windshield we see Laurie get out of Annie's car, say goodbye 
               and walk up to the Doyle's house.

               Then Annie's car makes a wide U-turn in the street and 
               starts down the other direction. The station wagon pulls 
               forward and follows her.

               Annie stops three houses down the street and pulls into a 
               garage. The station wagon stops several feet away.

               We see Annie come out of the garage and walk to another 
               two-story frame house: the Wallace's.

               TRACKING SHOT BEHIND SHAPE

               The shape gets out of the station wagon, close to CAMERA 
               so we can't see him. He glances down the street. Gusts of 
               wind blow the costumes of children going from house to 
               house.

               The shape moves. CAMERA TRACKS behind him as he walks toward 
               the Wallace house.

               The shape stops in front. Through the front room windows 
               we can see Annie talking to the WALLACES as they put on 
               their coats.

               The front door opens. CAMERA and shape quickly move behind 
               a tree to hide from sight.

               The Wallaces step out of their house and walk to the garage.  
               Annie and LINDSEY WALLACE, a pretty little nine-year-old, 
               stand in the doorway framed by the hall light. Out of the 
               garage comes the Wallace's car. It turns and disappears 
               down the street.

               Annie closes the door. The shape steps out from behind the 
               tree and stares at the house.

               ANGLE ON WINDOW

               The shape moves to see inside a window of the Wallace house.

               Inside, we see Annie turn on the TV. She goes to a mirror 
               on the wall and begins to brush her hair.

                                                                 CUT TO:

               EXT. MYERS HOUSE -- NIGHT

               A police car pulls up in front of the Myers house. Brackett 
               and Loomis get out and stand by the front gate.

                                     LOOMIS
                         Anybody live here?

                                     BRACKETT
                         Not since 1963, since it happened.
                         Every kid in Haddonfield thinks 
                         this place is haunted.

                                     LOOMIS
                         They may be right.

               ANGLE DOWN SIDE OF HOUSE

               Looking down the side of the house we see Loomis and 
               Brackett walk up to the front porch. A broken, rusted rain 
               gutter CLANGS back and forth against the house in the wind.

               INT. MYERS HOUSE -- NIGHT

               The front door slowly opens. Brackett and Loomis stand in 
               the doorway. They glance at each other. Brackett draws his 
               gun and the two men step inside.

               It is totally dark in the house. Brackett's flashlight 
               comes on, illuminating the two men. As they move through 
               the house CAMERA TRACKS with them.

               Suddenly Brackett stops. He trains his flashlight on a small 
               object in the corner of the room.

                                     LOOMIS
                         What is it?

               For a moment Brackett doesn't speak. Then he steps closer 
               to the object.

                                     BRACKETT
                         A dog...

               Both men look down off screen at the animal. Brackett bends 
               down to it.

                                     BRACKETT
                              (continuing)
                         Still warm.

               He stands back up and looks at Loomis.

                                     LOOMIS
                         He got hungry.

               Brackett gets a disgusted expression and steps away.

                                     BRACKETT
                         Come on... A skunk could have killed 
                         it...

                                     LOOMIS
                         Could have...

               Brackett looks back at the dead animal.

                                     BRACKETT
                         A man wouldn't do that...

                                     LOOMIS
                         He isn't a man.

               INT. MYERS BEDROOM

               Loomis and Brackett cautiously step into the bedroom, the 
               same room where the murder took place fifteen years ago.  
               The glow from a distant streetlight casts the shadows of 
               blowing trees on the walls.

                                     LOOMIS
                         It happened in here.

               Loomis walks over to the spot where the sister was sitting.

                                     LOOMIS
                              (continuing)
                         She was sitting here when he came 
                         through the door.

               Loomis turns and glances at the window. He slowly walks 
               toward it.

                                     LOOMIS
                              (continuing)
                         He must have watched them through 
                         this window...

               LOOMIS' POV -- WINDOW

               CAMERA SLOWLY TRACKS IN toward the window.

               ANGLE ON LOOMIS

               Loomis stops by the window.

                                     LOOMIS
                              (continuing)
                         Standing just outside, he could . 
                         peer over the sill...

               Blown loose by the wind, the rain gutter suddenly swings 
               down and SMASHES through the window with a THUNDERING CRASH 
               of broken glass.

               Loomis jumps back, reaches into his coat pocket and draws 
               a .357 magnum revolver.

               Brackett stares at him. Loomis sees Brackett's reaction 
               and slowly reholsters the revolver.

                                     LOOMIS
                              (continuing, looks 
                              at Brackett)
                         I suppose I do seem a bit sinister 
                         for a doctor.

                                     BRACKETT
                         Looks like to me you're just plain 
                         scared.

                                     LOOMIS
                         I am.
                              (he glances around 
                              the bedroom)
                         I met him fifteen years ago. I was 
                         told there was nothing left, no 
                         conscience, no reason, no 
                         understanding, in even the most 
                         rudimentary sense, of life or death 
                         or right or wrong. I met this six-
                         year-old boy with a blank, cold 
                         emotionless face and the blackest 
                         of eyes, the devil's eyes. I spent 
                         eight years trying to reach him 
                         and another seven trying to keep 
                         him locked away when I realized 
                         what was living behind that boy's 
                         eyes was purely, simply evil.

               Brackett just looks at him a moment.

                                     BRACKETT
                         What do we do?

                                     LOOMIS
                         He was here, earlier tonight, and 
                         he may be coming back. I'm going 
                         to wait for him.

                                     BRACKETT
                         I keep thinking I should call the 
                         radio and TV stations...

                                     LOOMIS
                         If you do they'll be seeing him 
                         everywhere, on every street corner, 
                         in every house. Just tell your men 
                         to shut their mouths and open their 
                         eyes.

                                     BRACKETT
                         I'll check back in an hour.

               Brackett turns and walks out of the bedroom. For a moment 
               Loomis stares at the rain gutter in the broken window.

                                                                 CUT TO:

               INT. DOYLE HOUSE -- NIGHT

               CAMERA SLOWLY TRACKS through the Doyle house. It is a large 
               home with a staircase that leads to the bedrooms upstairs. 
               Through a doorway we see a very modern kitchen. There is a 
               dining room and living room with a big bay window that 
               looks out into the street.

               Laurie sits with Tommy Doyle on the couch reading him a 
               story. Tommy has his Halloween costume on and a big bag of 
               candy on the floor.

                                     LAURIE
                              (reads)
                         ..."How now, cried Arthur. 'Then 
                         no one may pass this way without a 
                         fight?'  'That is so,' answered 
                         the knight in a bold and haughty 
                         manner..."

                                     TOMMY
                         I don't like that story.

                                     LAURIE
                         But King Arthur was always your 
                         favorite.

               Tommy pulls out a stack of comic books from underneath the 
               couch.

                                     TOMMY
                         Not any more.

                                     LAURIE
                         Why are they under there?

                                     TOMMY
                         Mom doesn't like me to have them.

               Laurie glances through the stack of comic books.

                                     LAURIE
                         'Neutron Man'... 'Laser Man'... I 
                         can see why. 'Tarantula Man'...

                                     TOMMY
                         Laurie, what's the Boogeyman?

               The phone RINGS in the other room. Laurie goes to answer 
               it.

               She picks up the receiver in the den.

                                     LAURIE
                         Hello.

               INT. DOYLE KITCHEN

               Annie stands making popcorn, the phone at her ear.

                                     ANNIE
                         Having fun? Never mind, I'm sure 
                         you are. I have big, big news for 
                         you...

               Lester, a large ferocious-looking German shepherd, trots 
               happily into the kitchen, spies Annie and walks over to 
               her.

               He nudges her legs with his head.

                                     ANNIE
                         Oops! Hold on a minute...

               She turns and reaches for Lester uncertainly.

                                     ANNIE
                         Hi Lester...

               Lester GROWLS at her menacingly.

                                     ANNIE
                         Lindsey, Lindsey!
                              (into phone)
                         I'm about to be ripped apart by 
                         the family dog.

               Lindsey trots into the room.

                                     ANNIE
                         Get him out of here!

                                     LINDSEY
                         Here, Lester.

               Immediately Lester walks over to the back door. Lindsey 
               opens the door and the dog trots out. Then Lindsey closes 
               the back door and walks back into the living room.

                                     ANNIE
                              (into phone)
                         I hate that dog. I'm the only person 
                         in the world he doesn't like.

                                     LAURIE (V.O.)
                              (into phone)
                         What's this big, big news?

                                     ANNIE
                         What would you say if I told you 
                         that you were going to the 
                         Homecoming Dance tomorrow night?

               INTERCUT WITH LAURIE IN THE DEN

                                     LAURIE
                         I'd say you must have the wrong 
                         number.

                                     ANNIE
                         Well, I just talked with Ben Tramer 
                         and he got real excited when I 
                         told him how attracted you were to 
                         him.

                                     LAURIE
                         Annie you didn't. Tell me you 
                         didn't.

                                     ANNIE
                         You guys will make a fabulous 
                         couple.

               INT. DOYLE LIVING ROOM

               Tommy walks to the front window and looks out.

               TOMMY'S POV -- STREET

               A couple TRICK-OR-TREATERS walk by.

               Behind them, across the street, stands the shape, looking 
               into the house.

               EXT. STREET -- DOYLE HOUSE

               CAMERA is behind the shape, looking into the Doyle house. 
               We can see Laurie talking on the phone. The shape's head 
               moves slightly and WE PAN to see Tommy at the front room 
               window looking out. Tommy moves away from the window. PAN 
               BACK to see him enter the den and pull on Laurie's blouse.

               INT. DOYLE HOUSE

                                     TOMMY
                         Laurie...

                                     LAURIE
                              (into phone)
                         I'm so embarrassed. I couldn't 
                         face him...

                                     ANNIE (V.O.)
                         You'll have to. He's calling you 
                         tomorrow to find out what time to 
                         pick you up.

                                     LAURIE
                              (panicked)
                         Annie!

                                     TOMMY
                         Laurie, the Boogeyman is outside.
                         Look!

               Tommy runs to the window in the den and points. Laurie 
               walks over with the phone and looks.

               LAURIE'S POV -- STREET

               The street is empty.

               ANGLE ON LAURIE -- TOMMY

                                     LAURIE
                              (into phone)
                         Hold on.
                              (to Tommy)
                         There's nobody there, Tommy. Go 
                         watch some TV.

               Tommy runs out of the den.

               INT. DOYLE HOUSE - LIVING ROOM

               Tommy dashes up to the front window and looks out.

               POV -- STREET

               We SEE the man as he passes under a streetlight on his way 
               toward the Wallace house.

                                                                 CUT TO:

               INT. WALLACE HOUSE -- NIGHT

               Annie stands by the kitchen stove making popcorn..

                                     ANNIE
                              (into telephone)
                         Look, it's simple. You like him, 
                         he likes you. All you need is a 
                         little push.

               POV FROM OUTSIDE KITCHEN WINDOW

               The shape stands close to CAMERA watching Annie make 
               popcorn.

               She puts the butter in the pan.

                                     ANNIE
                              (continuing)
                         It won't hurt you to go out with 
                         him, for God's sake.

               Annie starts to pour the butter over the popcorn but instead 
               pours it on herself.

                                     ANNIE
                              (continuing)
                         Shit! No, no, I gotta call you 
                         back. I just made a mess of myself. 
                         Nothing unusual.

               Annie hangs up. She quickly takes off her blouse and blue 
               jeans. She stands in the kitchen with only her panties on.

               She pulls a box of cornstarch out of the closet and 
               sprinkles it out on the stains of butter.

               ANGLE ON SIDE OF HOUSE

               The shape moves closer to the kitchen window and knocks 
               over a potted plant. It CRASHES noisily against the side 
               of the house..

               INT. WALLACE HOUSE

               Annie is startled by the crash. She looks outside the 
               window.

               POV OUT KITCHEN WINDOW

               A hanging plant swings in the wind. It BUMPS against the 
               side of the house.

               ANGLE OF ANNIE

               She turns from the window and walks out of the kitchen.

               EXT. WALLACE HOUSE

               The hanging plant continues to WHAP against the house.  A 
               hand suddenly stops its motion. The shape leans up close 
               to the kitchen window, looking inside.

               ANGLE ON DOG

               From the darkness of the backyard Lester springs forward 
               into CAMERA, SNARLING and BARKING viciously.1

               ANGLE ON SHAPE -- DOG

               The shape darts away from the kitchen window, the dog 
               SNAPPING right after him.

               INT.  WALLACE HOUSE

               Annie listens to the GROWLING of the dog. She turns to 
               Lindsey in the living room.

                                     ANNIE
                         Lindsey, Lester's barking again 
                         and getting on my nerves again...

                                     LINDSEY (O.S.)
                         No he's not.

               Suddenly the GROWLING sounds abruptly stop.

                                     ANNIE
                         Never mind. He found a hot date.

               Annie turns and walks into the living room.

               EXT. WALLACE HOUSE

               We SEE the shape's legs a few feet from the house. Next to 
               him are Lester's legs, kicking and struggling a few feet 
               above the ground.

               Off screen, the shape is strangling the dog in mid-air.

               Finally the dog's legs stop moving and dangle lifelessly.  
               The shape moves away from the house.

                                                                 CUT TO:

               INT. DOYLE HOUSE -- LIVING ROOM -- NIGHT

               Laurie and Tommy are sitting on the couch watching the 
               Horrorthon on TV.

                                     TOMMY
                         What about the Jack-o'-lantern?

                                     LAURIE
                         After the movie.

                                     TOMMY
                         What about the rest of my comic 
                         books?

                                     LAURIE
                         After the Jack-o'-lantern.

                                     TOMMY
                              (quietly)
                         What about the Boogeyman?

                                     LAURIE
                         There's no such thing.

                                     TOMMY
                         Richie said he was coming after me 
                         tonight.

                                     LAURIE
                         Do you believe everything that 
                         Richie tells you?

                                     TOMMY
                         No...

                                     LAURIE
                         Tommy, Halloween night is when you 
                         play tricks on people and scare 
                         them. It's all make believe.

               Richie was trying to scare you.

                                     TOMMY
                         I saw the Boogeyman. I saw him 
                         outside.

                                     LAURIE
                         There was no one out there.

                                     TOMMY
                         There was.

                                     LAURIE
                         What did he look like?

                                     TOMMY
                         The Boogeyman!

                                     LAURIE
                         We're not getting anywhere. All 
                         right, look, Tommy. The Boogeyman 
                         can only come out on Halloween 
                         night, right?

                                     TOMMY
                         Right.

                                     LAURIE
                         And I'm here tonight and I won't 
                         let him get you.

                                     TOMMY
                         Promise?

                                     LAURIE
                         I promise.

                                     TOMMY
                         Can we make the Jack-o'-lantern 
                         now?

               Laurie holds out her hand. Tommy takes it and together 
               they walk into the kitchen.

               EXT. PASSAGEWAY TO LAUNDRY -- WALLACE HOUSE -- NIGHT

               Annie walks through the passageway to the laundry room. 
               She is wearing a nylon robe and carrying her clothes to be 
               washed.  The wind blows the robe open.

               ANOTHER ANGLE -- PASSAGEWAY

               The shape stands behind a tree watching Annie walk along 
               the passageway.

               INT. LAUNDRY ROOM

               Annie walks into the dark laundry room.

               Almost immediately the wind blows the door shut!

               Annie stands motionless for a moment, then begins looking 
               for the light switch.

                                     ANNIE
                         Terrific!

               ANGLE ON DOOR

               The door creaks open. Behind the door we see the outline 
               of the shape standing there.

               ANGLE ON ANNIE

               Annie turns toward the slightly opened door.

                                     ANNIE
                         Hello?

               Silence.

                                     ANNIE
                         (continuing)
                         Who's there?

               Silence.  The wind blows the door open a little wider. In 
               the light from the main house, Annie sees the light switch. 
               Quickly she flicks on the switch and the laundry room lights 
               up. She glances outside the door.

               There is no one there.

                                     ANNIE
                         Paul, is this one of your cheap 
                         tricks?
                              (Pause, disappointed)
                         I guess not.

               She steps back inside and crosses to the washing machine. 
               She opens the top and dumps her clothes inside.

                                     ANNIE
                         No tricks for Annie tonight.

               Suddenly a big gust of wind comes through the opened window 
               above her. The door slams shut!

               Annie hurries to the door and tries to open it. It won't 
               open.

               CLOSE SHOT -- ANNIE

               She tries to pull the door open. Behind her, in the open 
               window above the washing machine, we see the shape looking 
               in.

                                     ANNIE
                         Lindsey! Lindsey, come out here!

               INT. WALLACE HOUSE

               LINDSEY WALLACE, 8 years old with a pretty face, watches 
               the Horror Marathon at top volume on TV. She doesn't hear 
               Annie's call.

               INT. LAUNDRY ROOM

                                     ANNIE
                         Lindsey, I'm in the laundry room!

               The door is stuck!

               Annie turns and glances at the window above the washing 
               machine. The shape is gone.

               She quickly crosses to the washing machine, climbs up on 
               top of it and starts out the window. Half way through she 
               gets stuck. She tries to squirm her way back in but it's 
               hopeless.

                                     ANNIE
                         Lindsey! Lindsey, goddamn it, help!

               From the house Annie hears the phone ring.

                                     ANNIE
                              (continuing)
                         Lindsey, answer the phone! It's 
                         Paul! Lindsey! LINDSEY!

               INT. WALLACE HOUSE

               Lindsey still sits in front of the TV. She lets the phone 
               ring away. Finally she gets up and walks to the phone, her 
               eyes pivoted on the TV. She picks up the receiver.

                                     LOOMIS
                         HELLO.

                                     PAUL (V.O.)
                         Hi, Lindsey, this is Paul. Is Annie 
                         there?

                                     LINDSEY
                         Yes, she is.

                                     PAUL (V.O.)
                         Will you get her for me.

                                     LINDSEY
                         She's washing her clothes.

                                     PAUL (V.O.)
                         Well, go tell her its me, okay?

                                     LINDSEY
                         Okay.

               Lindsey hangs up the phone and walks through the kitchen 
               to the back door. She calls from the door.

                                     LINDSEY
                         Annie, Paul's on the phone!

               115 ANGLE ON ANNIE HANGING OUTSIDE THE WINDOW 115

                                     ANNIE
                         Lindsey, open the door! I'm locked 
                         in the laundry room!

               EXT. LAUNDRY ROOM

               Lindsey crosses to the laundry room door. It is bolted 
               from the outside. She lifts the bolt and looks inside the 
               room.

               INT. LAUNDRY ROOM

                                     LINDSEY
                         You locked yourself in.

                                     ANNIE
                         I know. Pull my legs. I'm stuck.

               Lindsey pulls on Annie's legs and she slides from the window 
               onto the dryer.

                                     ANNIE
                         Lindsey, promise you won't tell 
                         anyone!

               INT. WALLACE HOUSE

               As Annie and Lindsey walk back inside the house, the phone 
               rings. Lindsey races across the room and picks it up.

                                     LINDSEY
                         She was stuck in the window, she'll 
                         be right here.

               Lindsey sets down the receiver and walks out of the kitchen.

               Annie gives Lindsey a dirty look and picks it up.

                                     ANNIE
                         Hello, Paul.
                              (pause)
                         All right, cut it out. It can happen 
                         to anyone.
                              (pause)
                         Yeah, but I've seen you stuck in 
                         other positions!

               Suddenly behind Annie the shape walks through the hallway 
               between the living room and the kitchen. She doesn't see 
               it.

                                     ANNIE
                              (continuing)
                         That's fantastic! When did they 
                         leave?
                              (pause)
                         Utterly fabulous!  So why don't 
                         you just walk over?
                              (pause)
                         My clothes are in the wash. I can't 
                         come now.
                              (pause)
                         Shut up, jerk. I've got a robe on.  
                         That's all you think about.
                              (pause)
                         That's not true. I think about 
                         lots of things. Why don't we not 
                         stand here talking about and get 
                         down to doing them? All right, see 
                         you in a few minutes.

               Annie hangs up the phone. She walks into the living room. 
               Lindsey is back watching the TV Horrorthon.

                                     LINDSEY
                              (excitedly)
                         I'm scared.

                                     ANNIE
                         Then why are you sitting here with 
                         the lights off?

                                     LINDSEY
                         I don't know.

                                     ANNIE
                         Well, come on, get your coat. We're 
                         going to pick up Paul.

                                     LINDSEY
                         I don't want to.

                                     ANNIE
                         Look, Lindsey, I thought we 
                         understood each other.

                                     LINDSEY
                         I want to stay here and watch this.

               Annie calculates a moment.

                                     ANNIE
                         Okay, if I can fix it so you can 
                         watch TV with Tommy Doyle would 
                         you like that?

               Lindsey's eyes light up.

                                     LINDSEY
                         Yes.

                                     ANNIE
                         Come with me.

                                                                 CUT TO:

               EXT. STREET -- NIGHT

               Annie and Lindsey come out of the Wallace house. Lindsey 
               carries a bowl of popcorn. Annie has a coat over the 
               negligee.

               They walk down the street to the Doyle's. The wind blows 
               strong and whips the negligee around Annie's lets.  

               ANOTHER ANGLE -- STREET

               As the girls make their way down the street. The shape 
               steps into the glow of a streetlight and watches them. He 
               pulls a large knife from his pocket. The blade glistens in 
               the light.

               INT. DOYLE HOUSE -- NIGHT

               Laurie and Tommy are covered with pumpkin meat when the 
               doorbell rings. Tommy runs to answer it. He opens the door.

               Annie and Lindsey stand there.

                                     TOMMY
                         Hi, come on in. We're making a 
                         Jack-o'-lantern.

                                     LINDSEY
                         I want to watch TV.

               Lindsey see the TV on and runs into the living room. She 
               takes off her coat; sits in front of the TV and eats her 
               popcorn.

               Laurie comes from the kitchen. She glances at Annie's coat.

                                     LAURIE
                         Fancy.

                                     ANNIE
                         This has not been my night. My 
                         clothes are in the wash, I spilled 
                         butter down the front of me, I got 
                         stuck in a window...

                                     LAURIE
                         I'm glad you're here because I 
                         have something I want you to do. I 
                         want you to call up Ben Tramer and 
                         tell him you were just fooling 
                         around.

                                     ANNIE
                         I can't.

                                     LAURIE
                         Yes, you can.

                                     ANNIE
                         He went out drinking beer with 
                         Mike Godfrey and he won't be back 
                         until late. You'll have to call 
                         him tomorrow. Besides, I'm on my 
                         way to pick up Paul.

               Laurie glances at Lindsey.

                                     LAURIE
                         Wait a minute here...

                                     ANNIE
                         If you watch her, I'll consider 
                         talking to Ben Tramer in the 
                         morning.

                                     LAURIE
                         Deal. Hey, I thought Paul was 
                         grounded.

                                     ANNIE
                         He was. Old jerko found a way to 
                         sneak out. Listen, I'll call you 
                         in an hour or so.

               Before Laurie can say anything else, Annie rushes out the 
               door. Laurie closes the door and looks in at Tommy and 
               Lindsey engrossed in the Horrorthon.

                                     LAURIE
                         The old girl scout comes through 
                         again.

               EXT. WALLACE HOUSE -- GARAGE -- NIGHT

               Annie hurries across the backyard and steps into the garage.

               She walks to her car.

                                     ANNIE
                              (sings to herself)
                         Oh, Paul, I give you all...

               She tries the door. It is locked.

                                     ANNIE
                              (continuing)
                         No keys, but please... my Paul.

               Quickly she turns and walks out of the garage.

               INT. WALLACE HOUSE

               Annie wanders through the empty house looking for her purse.  
               She finds it in the front room, takes out her brush and 
               lipstick and stands in front of the mirror primping.

                                     ANNIE
                              (sings)
                         My Paul, I can no longer stall...

               She glances up at her image in the mirror.

                                     ANNIE
                              (continuing)
                         Lucky thing. Spilled butter on her 
                         clothes, but nobody will know...
                              (sings)
                         except for Paul...

               Suddenly the phone RINGS. Quickly Annie grabs it.

                                     ANNIE
                         Hello. Oh hi, Dad.
                              (pause)
                         No, just watching TV with Lindsey.
                              (pause)
                         Be careful about what?
                              (pause)
                         Well, if you won't tell me how can 
                         I be careful?
                              (pause)
                         Sure, sure I will. Bye, dad.

               She hangs up, grabs her purse and rushes out the door.

               INT. GARAGE

               Annie walks into the garage, over to her car and opens the 
               door. It is now unlocked, but Annie doesn't notice.

               INT. CAR

               Annie slides in and inserts the key in the ignition. The 
               car starts. Annie glances at the car door lock. Suddenly 
               she remembers it was locked. She stares at it, puzzled.

               An instant later, a man sits up in the back seat.

               He wears a Halloween mask made of rubber with the grotesque 
               features of a man. He reaches forward and grabs her.

               Annie SCREAMS. She lurches for the door. The man puts one 
               hand over her mouth and brings the huge butcher knife up 
               to her throat.

               INT. GARAGE -- ANGLE ON CAR

               From outside the car we see the struggle inside. Annie's 
               Anguished face presses against the steamed window. Her 
               SCREAMS are muffled by the closed car.

               Suddenly, the struggle stops.

               Annie's face slides down the car window leaving a track in 
               the wet surface. Then slowly the track in the glass steams 
               over again.

                                                                 CUT TO:

               INT. DOYLE HOUSE -- NIGHT

               Music from Invasion of the Body Snatchers fills the room.  
               Lindsey and Tommy are riveted to the screen.

               Tommy glances at Lindsey and slowly sneaks away from the 
               couch. He jumps to a window and ducks behind a curtain.

                                     TOMMY
                              (from behind curtain)
                         Lindsey. Lindsey.

               Lindsey turns around and looks for Tommy.

                                     LINDSEY
                         Where are you?

               No answer. Lindsey gets up from the couch to search for 
               Tommy.

               BEHIND CURTAIN

               Tommy hides, preparing to jump out and scare Lindsey. For 
               a moment, he glances out the window.

               TOMMY'S POV -- WALLACE BACKYARD

               The figure of a man carries what seems to be a body across 
               the Wallace's backyard.

               INT. DOYLE HOUSE

               Tommy SCREAMS and jumps out from the curtain, scaring the 
               hell out of Lindsey, who also SCREAMS and begins crying.

                                     TOMMY
                         There he is, there he is! The 
                         Boogeyman!

               Laurie rushes in from the kitchen finding the children in 
               tears.

                                     LAURIE
                         What's wrong?

               Tommy points out the window.

                                     TOMMY
                         I saw him again! He's over at 
                         Lindsey's house. The Boogeyman!

               At this, Lindsey begins to CRY even louder. Laurie bends 
               down to comfort her.

                                     LAURIE
                         Tommy, stop it! You're scaring 
                         Lindsey.

                                     TOMMY
                         I saw him...

                                     LAURIE
                         I said, stop it! There is no 
                         Boogeyman. There's nothing out 
                         there. If you don't stop all this, 
                         I'm turning off the TV and you go 
                         to bed.

               Tommy turns away from Laurie and Lindsey and walks over to 
               the couch in front of the TV set. Almost instantly, Lindsey 
               stops crying and follows him.

                                     TOMMY
                         Nobody believes me.

                                     LINDSEY
                         I believe you, Tommy.

               Lindsey sits up next to Tommy and hugs him.

               Laurie shakes her head and walks back into the kitchen.

                                                                 CUT TO:

               EXT. MYERS HOUSE -- NIGHT

               The old Myers house looks ominous and foreboding silhouetted 
               against the dark, whishing trees. CAMERA TRACKS behind the 
               hedge to where Loomis sits waiting.

               Suddenly, there are noises from the street. Loomis parts 
               the hedge in front of him and stares.

               LOOMIS' POV -- STREET

               Three boys, Keith, Richie, and Lonnie (from the playground) 
               creep up to the edge of the sidewalk in front of the old 
               house. They stare fearfully at the dark, tomb-like 
               structure.

                                     LONNIE
                         I'm not afraid.

                                     RICHIE
                         Bullshit.

                                     RONNIE
                         I'm not!   
                         Then go in.

               For a moment Lonnie hesitates, then slowly moves through 
               the front gate up toward the porch.

               ANGLE ON LOOMIS

               He watches the young boy walk toward the house, unsure 
               whether he should interfere or just watch.

               LOOMIS' POV -- OLD HOUSE -- STREET

               Lonnie makes it to the front porch and tentatively steps 
               up to the door. He glances back to his friends in the 
               street.

               Loomis' POV moves to the street.

                                     RICHIE
                         Chicken!

                                     KEITH
                         Go on, Lonnie!   

               Then Loomis' POV moves back to Lonnie at the front door. 
               The boy turns to open the door. He's scared out of his 
               mind

               ANGLE ON LOOMIS

               Loomis quietly stands up behind the hedge.

                                     LOOMIS
                         Lonnie...

               LOOMIS' POV -- OLD HOUSE

               Lonnie spins around and stares in horror at the talking 
               hedge.

               ANGLE ON LOOMIS

                                     LOOMIS
                         Get your ass away from there!

               LOOMIS' POV -- OLD HOUSE -- STREET

               Moving like the wind, Lonnie barrels off the porch and 
               races back to his friends. The three boys hurtle off down 
               the dark street in utter terror.

               ANGLE ON LOOMIS

               He watches them race away, smiling to himself.

               Suddenly, two hands enter frame and grab Loomis' shoulders.  
               Loomis jumps and spins around.

               Standing there is Brackett.

                                     LOOMIS
                         Jesus!

                                     BRACKETT
                         You all right?

                                     LOOMIS
                         Sure...

                                     BRACKETT
                         Nothing's going on. Just kids 
                         playing pranks, trick or treating, 
                         parking, getting high... I have 
                         the feeling you're way off on 
                         this...

                                     LOOMIS
                         You have the wrong feeling.

                                     BRACKETT
                         You're not coming up with much to 
                         prove me wrong.

                                     LOOMIS
                         Exactly what do you need?

                                     BRACKETT
                         Well, its going to take more than 
                         fancy talk to keep me up all night 
                         creeping around these bushes.

                                     LOOMIS
                         I watched him for fifteen years, 
                         sitting in a room staring at a 
                         wall, not seeing the wall, seeing 
                         past it, seeing this night. He's 
                         waited for it, inhumanly patient.  
                         Hour after hour, day after day, 
                         waiting for some silent, invisible 
                         alarm to trigger him. Death has 
                         arrived in your little town, 
                         sheriff. You can ignore it, or you 
                         can help me stop it.

                                     BRACKETT
                         More fancy talk... You want to 
                         know what Haddonfield is?  Families. 
                         Children, all lined up in rows, up 
                         and down these streets. You're 
                         telling me they're lined up for a 
                         slaughterhouse.

                                     LOOMIS
                         They could be.

                                     BRACKETT
                         I'll stay out with you tonight, 
                         Doctor, just on that chance that 
                         you're right. And if you are right, 
                         damn you for letting him out.

               Brackett turns and walks back to the street. Loomis watches 
               him for several moments.

                                                                 CUT TO:

               EXT. WALLACE HOUSE -- NIGHT

               The house is quiet, dark. The lights are all out. Annie's 
               car is parked in the garage.

               A car pulls up in front of the house and parks. Its lights 
               flick off. The sounds of LAUGHTER come from inside.

               INT. CAR -- NIGHT

               BOB SIMMS, a good-looking 17-year-old, POPS open a can of 
               beer. Next to him Lynda guzzles hers. They embrace.

                                     LYNDA
                         Now... First we'll talk a little, 
                         then Annie will distract Lindsey 
                         and we sneak quietly up the stairs 
                         to the first bedroom on the left.
                         Got it?

                                     BOB
                         Okay. First I rip your clothes 
                         off.

               Bob grabs Lynda and she starts giggling. The can of beer 
               falls over onto the front seat.

                                     LYNDA
                         You idiot!

                                     BOB
                         ...Then you rip my clothes off.
                         Then we rip Lindsey's clothes off.
                         I think I've got it.

                                     LYNDA
                         Totally...

               EXT. WALLACE HOUSE

               Bob opens the door and together they fall out onto the 
               ground. Bob picks Lynda up and carries her up to the front 
               door.

                                     LYNDA
                         Bob... Put me down. Put me down.
                         This is totally silly.

               Lynda squirms in Bob's arms. As he sets her down her foot 
               accidentally hits the front door and it swings open. Lynda 
               and Bob both stop.

                                     LYNDA
                         Annie, Annie, we're here!

               Bob and Lynda enter the house.

               INT. WALLACE HOUSE -- NIGHT

               The living room is empty. The lights are off. Lynda and 
               Bob enter the house and begin turning on the lights.

                                     BOB
                         I wonder where they went.

                                     LYNDA
                         Annie probably took Lindsey out or 
                         something. Let's look for a note.

               Bob walks over to Lynda.

                                     BOB
                         Let's don't.

               They embrace. Bob pulls Lynda over to the couch and turns 
               out the light. They kiss. A shadow comes over them. They 
               continue kissing, unaware of the shape of a man on the 
               stairway watching.

               INT. DOYLE HOUSE -- NIGHT

               The house is totally black inside. The only sound is the 
               music score from "The Thing."

               Suddenly, the sound of laughter is heard from the kitchen. 
               Then an orange light floats through the room. As it gets 
               closer, we see that Laurie is carrying a Jack-o'-lantern, 
               with a candle illuminating from the center of the pumpkin. 
               Behind Laurie is Tommy and Lindsey making scary noises.  
               The procession continues through the house.

                                     TOMMY
                         Oooooo... He's gonna get you.

                                     LINDSEY
                         No, he's not.

                                     LAURIE
                         Nobody's going to get anybody. Now 
                         stop scaring each other.

               The procession continues to the front window. Laurie places 
               the Jack-o'-lantern on the windowsill. She looks down the 
               street toward the Wallace's.

               LAURIE'S POV OF THE WALLACE HOUSE

               Laurie sees Bob's car parked in front of the house.

               ANGLE ON LAURIE

               Laurie smiles to herself.

                                     LAURIE
                         Everybody has a good time tonight. 
                         Okay, kids, what do you want to do 
                         now.

                                     LINDSEY
                         Let's make more popcorn.

                                     LAURIE
                         You've had enough. Why don't we 
                         just sit down and watch the rest 
                         of the movie.

               Laurie sits down on the couch and sighs. Lindsey and Tommy 
               cuddle up with her, one on either side.

               The phone rings.

               Laurie gets up to answer it.

                                     LAURIE
                         Hello.

               INT. HOUSE -- NIGHT

               Lynda sits on the couch in the dark. Her hair and clothes 
               are messed up. Bob lies on the couch, his head on her lap.

                                     LYNDA
                         Hi, Laurie, what's up?

                                     LAURIE (V.O.)
                         Nothing. I was just sitting down 
                         for the first time tonight.

                                     LYNDA
                         Is Annie around?

                                     LAURIE
                         No. I thought she'd be home by 
                         now. She went to pick up Paul.

                                     LYNDA
                         Well, she's totally not here.

                                     LAURIE (V.O.)
                         They probably stopped off somewhere. 
                         Have her call me when she gets 
                         back. I've got Lindsey here and I 
                         want to know what time to put her 
                         to bed.

                                     LYNDA
                         Okay. Later.

                                     LAURIE (V.O.)
                         Have a good time.

               Lynda hangs up the phone and grins.

                                     LYNDA
                         We sure will.

               Lynda grabs Bob's hand and stands up.

                                     LYNDA
                              (continuing)
                         Lindsey is gone for the night.

               Bob grins.

                                     BOB
                         Now that's wonderful.

               Lynda pulls Bob up from the couch and they walk quickly up 
               the stairs.

               INT. DOYLE HOUSE -- NIGHT

               Laurie stands by the telephone. She walks to the window 
               and glances out.

               LAURIE'S POV -- WALLACE HOUSE

               It is dark.

               ANGLE ON LAURIE

               Laurie shrugs, turns away from the window and walks back 
               to Tommy and Lindsey sitting on the couch.

                                                                 CUT TO:

               INT. WALLACE BEDROOM -- NIGHT

               Sounds of lovemaking come from the bed. The only light is 
               a candle illuminating the sheets as they move slowly up 
               and down and from side to side. Empty beer cans leave a 
               trail from the door to the bed.

               The moans from Lynda begin increasing. They get louder. 
               Building to a crescendo. The phone rings. The lovemaking 
               suddenly stops.

                                     LYNDA
                         Shit! Not again.

               Lynda rises up on one arm. The sheet falls away from her, 
               showing a very beautiful young body. Her hair is a mess 
               and she is frustrated. The phone continues to ring.

                                     BOB
                         I can't help it. It just keeps 
                         ringing.

                                     LYNDA
                         And I can't keep you interested?

                                     BOB
                         Should we answer it?

               Bob opens a fresh can of beer. He chugs it down.

                                     LYNDA
                         That's great. Now you'll be too 
                         drunk to...

                                     BOB
                         Just answer the damn phone.

                                     LYNDA
                         I can't. What if it's the Wallaces!?  
                         We'd get Annie in trouble.

               The phone stops ringing.

                                     BOB
                         Take it off the hook.

               Lynda reaches over and kisses Bob behind the ears. She 
               slowly moves around his ear with her tongue. Bob grabs 
               Lynda and pushes her down on the bed.

               CAMERA MOVES BACK from the bed as their lovemaking 
               continues, back through the bedroom doorway. Standing there 
               in the darkness is the shape watching them.

               Finally, Bob and Lynda climax. Bob rolls off Lynda. She 
               lights a cigarette and hands it to Bob, then lights one 
               for herself.

                                     LYNDA
                         Fantastic. Totally.

                                     BOB
                         Yeah.

                                     LYNDA
                         Want a beer?

                                     BOB
                         Yeah.

                                     LYNDA
                         Is that all you have to say?

                                     BOB
                         Yeah.

                                     LYNDA
                         Go get me a beer.

                                     BOB
                         I thought you were gonna get one 
                         for me.

                                     LYNDA
                         Yeah?

               Bob gets out of bed and pulls his jeans on. He looks for 
               his glasses. He finds them and puts them on.

                                     BOB
                         I'll be right back. Don't get
                         Dressed.

               Bob leans over and kisses Lynda. He leaves.

               Lynda leans back onto the pillows. She smiles to herself.

               INT. WALLACE KITCHEN

               Bob comes through the swinging doors. He opens the 
               refrigerator and takes out two beers. He looks around the 
               kitchen. He opens some cupboards and takes out a bag of 
               potato chips. In another cupboard, he finds a can of 
               peanuts.

               Bob gathers the food and beer into his arms. He shuts out 
               the light with his elbow. He turns to leave the doors. 
               WHAM! He steps into a chair, knocking him backwards. The 
               beer falls on the floor along with the chips and peanuts. 
               Bob leans down to pick them up.

                                     BOB
                         Goddammit!

               ANOTHER ANGLE 153

               Bob has his head down, intent on cleaning up the mess.There 
               is a SLAM from across the kitchen. Bob looks up. 

               BOB'S POV -- DOOR

               The back door of the kitchen slowly swings open, as if it 
               has been slammed shut and the bolt didn't catch. It squeaks 
               on its hinges as it swings back and forth.

               INT. KITCHEN

               Slowly, Bob gets to his feet and walks over to the door.

                                     BOB
                         Annie, Paul...

               He steps to the door and looks outside. 

               BOB'S POV -- BACKYARD

               The yard is empty. Just the wind blowing the trees.

               ANGLE ON BOB

               He turns from the door.

               There is a SQUEAK from one of the two closet doors by the 
               kitchen counter.Bob freezes, staring at the two doors.

                                     BOB
                         Lynda, you asshole!

               He walks to one of the doors and opens it. Nothing inside.

                                     BOB
                              (continuing)
                         All right, Lynda, come on out.

               He steps to the other door and opens it.

               Right behind the door stands the shape wearing the rubber 
               mask.

               He steps out and grabs Bob around the neck in an 
               instantaneous lunge.

               Bob tries to jump away, but the shape has a firm hold on 
               his neck. Bob COUGHS and GAGS from the pressure.

               Then the shape lifts Bob up off the floor.

               ANGLE ON BOB'S FEET

               Bob's feet leave the floor.

               ANGLE ON BOB'S FACE

               He makes a guttural sound deep in his throat as the shape's 
               hand closes tightly around his windpipe.

               ANGLE ON SHAPE

               Behind the mask are two burning eyes. The shape moves 
               forward.

               ANGLE ON WALL

               Still holding him up with one hand the shape SLAMS Bob 
               against the wall, holding him up several feet off the floor.  
               Bob struggles to get free.

               The shape lifts his other hand. It holds the butcher knife.

               The shape drives the knife deeply into Bob's chest with a 
               SLAMMING THUD, the other end of the knife stuck through 
               the wall.

               Then the shape steps away. Bob hangs there, impaled on the 
               wall, eyes still open in horror, dead.

                                                                 CUT TO:

               INT. WALLACE BEDROOM

               Lynda lounges on the bed smoking another cigarette. She 
               hears Bob enter the room but doesn't look up.

                                     LYNDA
                         Where's my beer?

               No answer. Lynda turns around and looks.

               ANOTHER ANGLE -- LYNDA'S POV

               The shape stands in the doorway. He is covered with a sheet 
               like a ghost. He wears Bob's glasses.

                                     LYNDA
                              (continuing)
                         Cute, Bob. Real cute.

               The ghost doesn't answer.

               ANOTHER ANGLE -- LYNDA AND GHOST

               Lynda looks at the ghost. She slides the sheets down from 
               her body.

                                     LYNDA
                              (continuing)
                         Come here, you fool.The ghost 
                         doesn't answer. He continues to 
                         stare at Lynda. Can't I get your 
                         ghost, Bob?

               Lynda laughs at her own joke, then stops when she sees the 
               ghost is motionless.

                                     LYNDA
                              (continuing)
                         All right, all right. So where's 
                         the beer.

               Nothing. The ghost just stands there.

                                     LYNDA
                              (continuing)
                         Well, answer me! Okay, don't answer 
                         me. Boy, are you weird!

               Lynda gets out of bed. She is nude and looks beautiful and 
               sensuous in the candle light. She walks over to the phone.

                                     LYNDA
                              (continuing)
                         Well, I'm gonna call Laurie.  I 
                         wanna know where Annie and Paul 
                         are. This isn't going anywhere.

               Lynda sits down on a chair by the telephone. In the b.g. 
               the ghost stands in the doorway. She starts to dial the 
               phone. The ghost starts walking toward her.

               INT. DOYLE HOUSE -- NIGHT

               The house is very quiet. The kids are asleep. Laurie is 
               sitting on the couch knitting. The phone RINGS.

                                     LAURIE
                         Finally.

               Laurie crosses to answer the phone.

               INT. WALLACE BEDROOM

               Lynda holds the phone to her ear. The ghost walks up slowly 
               behind her. He raises his hands to grab her.

               INT. DOYLE HOUSE

               Laurie answers the telephone.

                                     LAURIE
                         Hello.

               INT. WALLACE BEDROOM

               Lynda hears Laurie's hello as the ghost grabs the phone. 
               He clamps one hand over Lynda's mouth. She squirms and 
               writhes. He takes the telephone cord and wraps it around 
               her neck.

               INT. DOYLE HOUSE

                                     LAURIE
                         Hello?

               Laurie hears SQUEALS, and rustling sounds across the phone.

                                     LAURIE
                              (continuing)
                         All right, Annie! I've heard your 
                         famous chewing, now I get your 
                         famous squeals?

               Laurie continues to hear weird SOUNDS.

                                     LAURIE
                              (continuing)
                         Annie?

               INT. WALLACE BEDROOM

               Lynda tries to fight off the ghost. He wraps the cord around 
               the neck. He pulls tight. Lynda reaches up and pulls on 
               the sheet. It slides off of the man, to reveal the grotesque 
               Halloween mask.

               Lynda gasps and tries to scream. The man pulls the cord 
               tighter. Her face turns blue. She opens her mouth, trying 
               to get air, then slowly slumps forward and remains 
               motionless. Lynda is dead.

               The shape picks up the receiver and puts it to his ear.

               INT. DOYLE HOUSE -- ANGLE ON LAURIE

                                     LAURIE
                         Annie, Annie! Are you all right?

               Silence over the phone.

                                     LAURIE
                              (continuing)
                         Are you fooling around again?

               Silence.

                                     LAURIE
                              (continuing)
                         I'll kill you if this is a joke!

               More silence.

                                     LAURIE
                              (continuing)
                         Annie...

               Suddenly the phone goes dead.

               Laurie stares at the receiver, then hangs up. She crosses 
               to the window and looks out toward the Wallace house.

               LAURIE'S. POV -- WALLACE HOUSE

               The street is quiet, dark and windy. Bob's car is parked 
               in front of the Wallace house.

               Suddenly a light goes on in the bedroom.

               ANGLE ON LAURIE

               She stares at the house, puzzled.

               LAURIE'S. POV -- WALLACE HOUSE

               Then the light goes off.

               INT. DOYLE HOUSE

               Laurie moves from the window back to the telephone and 
               dials Annie's number. We HEAR the phone ringing on the 
               other end.

               INT. WALLACE HOUSE -- BEDROOM

               CAMERA SLOWLY TRACKS through the darkened bedroom of the 
               Wallace house. There is no sign of a struggle. The room is 
               empty. The phone RINGS away.

               INT. DOYLE HOUSE

               Laurie finally hangs up the phone. She stands for a moment 
               considering it, then turns and walks upstairs.

               INT. DOYLE BEDROOM

               Laurie opens the door to the bedroom. Tommy and Lindsey 
               are sound asleep on the bed. She looks at them a moment, 
               then closes the door behind her.

               INT. DOYLE HOUSE -- LIVING ROOM

               Laurie comes back downstairs. She takes a key out of her 
               purse and again steps to the window.

               LAURIE'S POV -- WALLACE HOUSE

               Dark and silent.

               ANGLE ON LAURIE

               She steps to the front door.

                                                                 CUT TO:

               EXT. MYERS HOUSE -- NIGHT

               Loomis sits in silence behind the hedge watching the Myers 
               house. Frustrated, he gets up and walks to the street.

               For a moment he glances back at the Myers house, then starts 
               down the quiet residential street.

               LOOMIS' POV -- STREET -- STATION WAGON

               It is empty except for a station wagon parked several blocks 
               away.

               ANGLE ON LOOMIS

               He turns away from the street. Then a thought strikes him. 
               He looks again.

               LOOMIS' POV -- STREET -- STATION WAGON

               The lone car is Loomis' station wagon.

               ANGLE ON LOOMIS

               He's not certain of it. Slowly Loomis starts walking down 
               the street toward the station wagon.

                                                                 CUT TO:

               EXT. STREET -- NIGHT

               Laurie locks the Doyle house and walks away out into the 
               street. The wind whips her clothes and hair.

               LAURIE'S POV -- WALLACE HOUSE -- MOVING SHOT 

               MOVING SHOT TOWARD THE WALLACE HOUSE, DARK AND OMINOUS

               MOVING SHOT -- LAURIE

               She moves down the street, shivering in the chill wind. 

               She puts the key to the Doyle house in her pocket.

               LAURIE'S POV -- WALLACE HOUSE -- MOVING SHOT 

               Car turns the corner and drives past the Wallace house, 
               casting a strange shadowy pattern across the front of the 
               house.

               MOVING SHOT -- LAURIE

               She picks up her speed now up the sidewalk.

               LAURIE'S POV -- WALLACE HOUSE -- MOVING SHOT

               The house looms closer and closer.

                                                                 CUT TO:

               EXT. STREET -- NIGHT

               TRACKING SHOT with Loomis as he walks up the street.

               LOOMIS' POV -- STATION WAGON

               The station wagon moves closer.

               MOVING SHOT -- LOOMIS

               He recognizes it and races forward.

               LOOMIS' POV -- STATION WAGON

               CAMERA TRACKS IN to the station wagon, right up to the state 
               emblem emblazoned on the side.

                                                                 CUT TO:

               EXT. WALLACE HOUSE -- NIGHT

               CAMERA MOVES UP to the front of the Wallace house. 

               Laurie walks up to the front porch. She stands there a 
               moment, listening, as if to hear some sound of life from 
               the inside.

               She KNOCKS on the door and RINGS the doorbell. She waits.

               Silence.

               She steps off the porch and walks around to the side of 
               the house, CAMERA TRACKING WITH HER. She moves to the garage 
               and peeks inside. There is Annie's car.

               Laurie thinks a moment, then looks to the street.

               LAURIE'S POV -- BOB'S CAR

               Bob's car sits there on the street.

               ANGLE ON LAURIE

               She turns and walks through the breezeway between the house 
               and the garage around to the back door.

               The kitchen door is ajar, swinging back and forth in the 
               wind.

               Laurie pulls open the door and steps into the house.

               INT. WALLACE KITCHEN

               The kitchen is dark. Laurie stands there a moment staring 
               into the blackness.

                                     LAURIE
                         Annie?

               No answer.

                                     LAURIE
                              (continuing)
                         Bob, Lynda, Annie?

               No one answers. Laurie searches for the wall light. She 
               flips it and nothing happens. She looks again into the 
               darkness.

                                     LAURIE
                              (continuing)
                         Hello?

               Nothing. Laurie moves forward into the house, CAMERA 
               TRACKING WITH HER.

               Laurie walks into the living room. She stops to let her 
               eyes get accustomed to the almost total darkness. She 
               reaches for a nearby lamp and trips over the cord. The 
               lamp CLUNKS to the floor.

                                     LAURIE
                              (continuing)
                         Shit.

               Suddenly there is a CRASHING SOUND from upstairs.

               Laurie spins around and stares up the dark staircase.

               Another SQUEAK from above.

               Laurie smiles.

                                     LAURIE
                              (continuing)
                         All right, meatheads. The joke is 
                         over.

               Silence.

                                     LAURIE
                              (continuing)
                         Come on, Annie, enough.

               Another SOUND from upstairs, a DRAGGING across the floor.

               Laurie moves to the head of the staircase. 

               The dragging sound stops abruptly. Silence.

                                     LAURIE
                              (continuing)
                         This has most definitely stopped 
                         being funny. Now cut it out!

               A SCRAPING SOUND, then silence.

                                     LAURIE
                              (continuing)
                         You'll be sorry.

               Slowly Laurie starts up the staircase.

                                                                 CUT TO:

               EXT. STREET -- NIGHT

               Loomis stands by his car glancing up and down the empty 
               street. Finally he makes up his mind and starts moving 
               down the street, almost running, looking back and forth at 
               the rows of houses on either side for something out of 
               place.

                                                                 CUT TO:

               INT. WALLACE HOUSE -- NIGHT

               SLOWLY TRACKING up the staircase.

               MOVING SHOT -- LAURIE

               As she slowly moves up the stairs. She reaches the top and 
               stops.

               LAURIE'S POV -- SECOND FLOOR HALLWAY

               It is totally dark. At the end of the hall is the bedroom 
               door.  From around the edges of the door is the faintest 
               orange glow.

               ANGLE ON LAURIE

               She moves for the door, CAMERA TRACKING WITH HER.

               LAURIE'S POV -- DOOR 

               She reaches the door. Her hand reaches out and touches it.

               The door swings open.

               A Jack-o'-lantern casts an eerie glow around the room. 
               There is someone lying on the bed but from this position 
               Laurie can't see.

               ANGLE ON LAURIE

               She moves forward toward the bed.

               LAURIE'S POV

               CAMERA MOVES FORWARD. There on the bed is Annie! Her face 
               is a chalky white and there is a huge red gash across her 
               throat.

               At the head of the bed is Judith Myer's tombstone.

               ANGLE ON LAURIE

               She stares at the bed and then SCREAMS at the top of her 
               lungs.

               Suddenly something drops down at her from above.

               Laurie jumps back to the door.

               LAURIE'S POV -- BOB 

               Strung up to the light fixture on the ceiling, dangling 
               there in the middle of the room, is Bob, eyes open and 
               staring.

               INT. SECOND FLOOR HALLWAY

               Laurie backs out of the bedroom. Her mouth is open in 
               speechless horror.

               Suddenly a door next to her slowly opens. There is Lynda 
               standing there, propped up by a chair, staring at her with 
               glazed, dead eyes.

               ANGLE ON LAURIE -- CORNER (LIGHTING EFFECT)

               Laurie shrinks back into a dark corner. She can only stare 
               in horror at the sight of her friend.

               Suddenly we are aware of something there in the dark 
               corner.

               It is almost as if our eyes have suddenly begun to adjust 
               to the darkness and we see the outline of a man standing 
               right behind her.

               The outline becomes more and more clear. It is the shape, 
               wearing the mask, the butcher knife in his hand, gleaming, 
               right behind Laurie.

               Laurie suddenly moves away from the corner.

               The shape lunges out at her.

               CLOSE SHOT -- LAURIE'S BACK -- HAND

               The hand grasps a piece of Laurie's blouse and RIPS it.

               CLOSE SHOT -- LAURIE

               She SCREAMS and spins around.

               ANGLE ON SHAPE

               He stands there holding up the piece of material, then 
               raises the butcher knife and moves for her.

               ANGLE ON LAURIE

               CAMERA MOVES WITH HER as she backs away, SCREAMING at the 
               top of her lungs.

               ANGLE ON SHAPE

               He lunges at her suddenly with the knife.

               ANGLE ON LAURIE -- TOP OF STAIRCASE

               The knife slices across her arm, ripping her flesh.

               Laurie suddenly jumps backward, raising her arm 
               instinctively.

               ANGLE ON RAILING.

               Laurie bumps back into the railing.

               ANGLE ON SHAPE

               He lunges again with the knife.

               ANGLE ON LAURIE

               She leaps backward to avoid the blade and slips over the 
               edge of the railing.

               LAURIE'S POV

               CAMERA PLUNGES DOWN from the second floor and SLAMS into 
               the floor.

               ANGLE ON LAURIE

               She hits the floor and rolls over, holding her leg 
               painfully. Then she looks up at the staircase. 

               POV STAIRCASE

               The shape moves to the top of the staircase and starts 
               down toward her.

               ANGLE ON LAURIE

               She pulls herself up off the floor and hobbles into the 
               living room. 

               ANGLE ON STAIRCASE

               The shape races down the stairs. 

               ANGLE ON LAURIE

               She moves for the kitchen. She trips on the fallen lamps 
               and falls to the floor. 

               ANGLE ON SHAPE

               The shape steps into the living room, knife raised.

               ANGLE ON LAURIE -- KITCHEN

               She crawls to the kitchen, rolls inside and SLAMS the 
               kitchen door behind her. In a flash she leaps up and CLICKS 
               the lock.

               There is a POUNDING on the door from the other side.

               Laurie slowly climbs to her feet and limps toward the back 
               door.

               Suddenly the kitchen door EXPLODES, the middle of it 
               breaking apart. The shape reaches through, groping for the 
               lock.

               Laurie reaches the back door.

               ANGLE ON DOOR

               Her hand tries the door. It is key-locked.

               ANGLE ON LAURIE

               Desperately she tries the door, glancing behind her.

               ANGLE ON SHAPE

               The shape's hand reaches for the lock.

               ANGLE ON LAURIE

               She steps back from the door into the kitchen.  

               LAURIE'S POV -- KITCHEN WINDOW

               She sees the kitchen window over the sink.

               ANGLE ON LAURIE

               She hobbles to the sink, climbs up on it and grabs the 
               window. With a heave she opens it up halfway.

               ANGLE ON SHAPE

               The shape's hand grabs the lock and CLICKS it open.

               ANGLE ON LAURIE -- KITCHEN WINDOW

               She can only get it three-fourths open. Headfirst she crawls 
               through the window.

               ANGLE ON SHAPE

               The shape pushes the door open and leaps into the kitchen.

               ANGLE ON LAURIE

               She drags herself roughly out the window.

               CLOSE SHOT -- WINDOW

               The shape grabs at Laurie's legs as they disappear through 
               the sill.

               EXT. WALLACE HOUSE

               Laurie picks herself up from the ground and runs as fast 
               as she can, limping across the backyard, CAMERA MOVING 
               WITH HER. She passes the driveway and scurries into the 
               neighbor's backyard, up to the back door of the house. She 
               POUNDS furiously on the door.

                                     LAURIE
                         Help me!  Help me!

               She looks behind her.

               LAURIE'S POV -- WALLACE HOUSE

               No sign of the shape. The house is dark and silent.

               ANGLE ON LAURIE

               The back porch light comes on. Laurie continues to POUND 
               on the door.

               LAURIE'S POV -- DOOR

               Through the glass in the back door we see an OLD WOMAN 
               dressed in a nightgown approach.

               ANGLE ON LAURIE

                                     LAURIE
                         Please, help me! Call the police!  
                         Please!

               LAURIE'S POV -- DOOR

               The old woman stares at her suspiciously for a moment, 
               then turns from the door and walks away.

               ANGLE ON LAURIE

               The porch light goes out.

                                     LAURIE
                         No! No!  Please, open the door!

               She turns around and looks back.

               LAURIE'S POV -- WALLACE HOUSE

               Nothing. No sign of the shape.

               ANGLE ON LAURIE

               She hobbles off the back porch and runs across the yard to 
               the street.  CAMERA MOVES WITH HER as she limps along.

               EXT. DOYLE HOUSE

               Laurie rushes up to the front door. She reaches in her 
               pocket for the key and drops it on the porch.

               Quickly she bends down and scrambles for it. She looks 
               back toward the street.

               LAURIE'S POV -- STREET

               The street is empty. The wind WHISHES the trees. Leaves 
               sprinkle down.

               EXT. DOYLE HOUSE

               Laurie gropes around for the key. It lies over a crack in 
               the wooden porch. She reaches for it but her finger nudge 
               the key between the crack, down out of sight.

               Laurie SCREAMS with frustration and glances back at the 
               street.

               LAURIE'S POV -- STREET

               The shape walks slowly down the middle of the street, right 
               toward her!

               ANGLE ON LAURIE

               Laurie begins to BANG on the front door.

                                     LAURIE
                         Tommy!  Tommy, open the door!

               She grabs a planter on the porch, steps back and hurls it 
               at an upstairs window.

               ANGLE ON UPSTAIRS WINDOW

               The planter SMASHES against the window. A light goes on. 
               Tommy appears sleepily at the window.

                                     TOMMY
                         Who is it?

               ANGLE ON LAURIE

                                     LAURIE
                         Tommy, let me in!

               She looks back at the street.

               LAURIE'S POV -- STREET

               The street is empty. The shape is gone.

               ANGLE ON LAURIE

               She stands there breathlessly, her eyes burning in the 
               darkness.

               Finally the door opens. Tommy stands there in his pajamas.

               Laurie leaps inside and SLAMS the door.

               INT. DOYLE HOUSE 259

               Laurie bolts the door from the inside.

                                     LAURIE
                         Tommy, I want you to go back 
                         upstairs...

                                     TOMMY
                         What is it, Laurie?

                                     LAURIE
                         Be quiet! Get Lindsey and get into 
                         the bedroom and lock the door!

                                     TOMMY
                         I'm scared...

                                     LAURIE
                         DO WHAT I SAY! NOW!

                                     TOMMY
                         It's the Boogeyman, isn't it?

                                     LAURIE
                         HURRY!  

               Tommy turns and runs upstairs CRYING.

               Laurie moves from the door to the telephone. She picks it 
               up, dials a number and waits.

               Then suddenly she reacts..  The phone is dead. No dial 
               tone.

               She puts down the phone and stands very still. There is a 
               slight breeze blowing her hair.Slowly Laurie moves around 
               the couch.

               LAURIE'S POV -- KITCHEN

               From the living room we see into the kitchen. The back 
               door is open.

               ANGLE ON LAURIE

               Laurie doesn't move.  She begins crying softly, her eyes 
               wide with fear.

                                     LAURIE
                         Please stop... Please...

               Silence. No movement anywhere in the house.Slowly Laurie 
               sinks down to her knees by the couch.

               CLOSE SHOT --KNITTING NEEDLES

               Her hand brushes against the knitting needles protruding 
               from her tote bag.

               ANGLE ON LAURIE -- COUCH

               She reacts to the feel of the knitting needles and pulls 
               one out. It is long and deadly sharp. She stares at it.

               Suddenly the shape leaps up from behind the couch! He 
               springs at her, plunging the butcher knife.

               ANGLE ON COUCH

               The blade of the butcher knife THUMPS into the couch.

               ANGLE ON LAURIE -- SHAPE

               Instinctively Laurie raises the knitting needle and drives 
               it home, right into the shape's neck!

               The shape springs backward, clawing at the needle, rolling 
               his head back and forth. Then suddenly he freezes, hands 
               outstretched, motionless, and falls in a heap on the floor.

               Laurie sits there.

               The shape doesn't move.

               Laurie begins to cry again, harder and harder.

                                                                 CUT TO:

               EXT. STREET -- NIGHT

               CAMERA MOVES WITH LOOMIS as he moves along the street. 
               Suddenly two headlights hit him and a police car swerves 
               to a stop next to him. Brackett gets out.

                                     BRACKETT
                         Where were you? I went back to the 
                         Myers house...

                                     LOOMIS
                         I found the car! He's here!

                                     BRACKETT
                         Where!

                                     LOOMIS
                         Three blocks down. Get in the car 
                         and go up that other street then 
                         back down here. I'm going up the . 
                         block.

               Brackett turns and hurries back to the car.

               Loomis starts up the street again as Brackett pulls off in 
               the other direction.

                                                                 CUT TO:

               INT. DOYLE HOUSE -- NIGHT

               WIDE SHOT of the living room. Laurie is on one side of 
               frame, the motionless shape lying behind the couch on the 
               other.

               Slowly Laurie stands up, stares at the shape and then moves 
               to the staircase.

               Slowly, painfully, Laurie climbs up the stairs.

               INT. BEDROOM

               Tommy and Lindsey are huddled in a corner WHIMPERING softly. 
               The door opens and Laurie steps in. The two children run 
               to her CRYING. She holds them in her arms tightly and nudges 
               the door shut with her foot.

                                     LAURIE
                         It's all right now. Shhh, it's all 
                         right...

               She takes the children back to the bed and sits down with 
               them.

                                     LAURIE
                              (continuing)
                         Now I want you to change your 
                         clothes, Tommy. We're going to 
                         take a walk outside.

                                     TOMMY
                         Was it the Boogeyman?

                                     LINDSEY
                         I'm scared!

                                     LAURIE
                         There's nothing to be scared of 
                         now. Get changed.

                                     TOMMY
                         Are you sure?

                                     LAURIE
                         Yes.

                                     TOMMY
                         How?

                                     LAURIE
                         I killed him...

                                     TOMMY
                         But you can't kill the Boogeyman.

               Suddenly the bedroom door swings open. Standing there is 
               the shape, the butcher knife raised.

               Both children SCREAM. Laurie shoves them into the bathroom 
               and pulls the door shut, leaving herself outside in the 
               bedroom.

                                     LAURIE
                         Lock the door! Lock the door!

               The shape moves for her, slowly now, but relentless, the 
               knife glistening.

               There is a CLICK as the bathroom door is locked. Laurie 
               leaps away from the door and circles around the bed.

               The shape keeps coming.

               Laurie dashes to a clothes closet and ducks inside.

               INT. CLOTHES CLOSET

               Laurie pulls the sliding doors closed and crawls back into 
               the small, dark interior of the closet.

               Suddenly the doors begin to buckle as the shape pounds on 
               them.

               ANGLE ON LAURIE

               She reaches up and grabs a wire hanger from the top of the 
               closet. She rips off the shirt and begins unhooking it.

               ANGLE ON CLOSET DOOR

               The door buckles inward as the shape SMASHES against it.

               ANGLE ON LAURIE

               She twists the top of the hanger, unwinding the wire.

               ANGLE ON CLOSET DOOR 

               The door BREAKS IN. The shape steps inside, pushing aside 
               the clothes.

               ANGLE ON LAURIE

               She unhooks the hanger and bends it out straight.

               ANGLE ON SHAPE

               The shape leans in, peering down at Laurie in the corner, 
               raising the knife.

               ANGLE ON LAURIE

               Holding the hanger with both hands she thrusts it forward 
               with all her might.

               ANGLE ON SHAPE

               The wire hanger flashes into the shape's right eye.He leaps 
               back in pain, dropping the butcher knife, grabbing his eye 
               with both hands.

               ANGLE ON LAURIE

               She grasps the butcher knife with both hands and jabs it 
               upward.

               ANGLE ON SHAPE

               The butcher knife plunges into the shape's mid-section, 
               right down to the hilt. The shape stumbles backward out of 
               the closet.

               ANGLE ON LAURIE

               She just sits there in the corner of the closet. There is 
               a THUMP from the bedroom, then silence.

               Slowly Laurie crawls around and peeks out of the closet 
               doors.

               LAURIE'S POV -- SHAPE

               The shape lies on the floor by the bed, the butcher knife 
               protruding from his stomach.

               INT. BEDROOM

               Laurie emerges from the closet and carefully crosses the 
               bedroom, avoiding the shape's body. She goes to the bathroom 
               door and knocks softly.

                                     LAURIE
                         Tommy, it's me. Open the door.

               There is a silence, then the door opens. On the other side 
               are Tommy and Lindsey, looking utterly terrified. Laurie 
               bends down and shields them from the sight of the shape.

                                     LAURIE
                              (continuing)
                         Now, I want you to walk to the 
                         door, down the stairs and right 
                         out the front door.

                                     LINDSEY
                         You're coming with us...

                                     LAURIE
                         Listen to me. I want you to walk 
                         down the street to the MacKensie's 
                         and knock on their door. You tell 
                         them to call the police and send 
                         them over here. Do you understand?

                                     TOMMY
                         Laurie, you come with us...

                                     LAURIE
                         No! Do as I say.

               She stands up and guides the children carefully across the 
               bedroom to the door and ushers them outside.

               She watches for a moment as they walk down the stairs, 
               then slumps down against the door frame in an exhausted 
               heap.

               EXT. DOYLE HOUSE -- NIGHT

               Tommy and Lindsey run out of the house and down the walk 
               to the sidewalk. They rush up the street. As they leave 
               frame we see Loomis on the other side of the street.

               ANGLE ON LOOMIS

               He watches the children with a puzzled frown.

               LOOMIS' POV -- TOMMY AND LINDSEY

               Shrieking with fear, Tommy and Lindsey run up the sidewalk.

               ANGLE ON LOOMIS

               He stares at them for a moment, then moves for the Doyle 
               house.

                                                                 CUT TO:

               INT. DOYLE HOUSE -- ANGLE THROUGH BEDROOM DOOR -- NIGHT

               We SEE through the bedroom door. In f.g. sits Laurie, 
               slumped against the door frame, staring out at nothing, 
               tears streaming down her face. In b.g. lies the shape.

               Slowly Laurie begins to pull herself together once again.

               She gets up to her knees and begins to pull herself up to 
               her feet.

               Her back is to the shape. As she starts to stand the shape 
               sits up, the head turning to Laurie.

               CLOSE SHOT -- LAURIE

               Laurie rises into frame, holding herself erect by grasping 
               the doorframe.

               Behind her the shape rises up into frame, quickly, silently.

               Laurie just hangs there on the doorframe. An exhausted, 
               ironic smile comes over her face.

                                     LAURIE
                         Well, kiddo. Some Halloween...

               Slowly the shape moves for her, his hands outstretched.

               Just as he is about to grab her, Laurie manages to step 
               out the door.

               ANGLE IN HALL

               Unaware he is behind her, Laurie limps toward the stairs.

               Suddenly the shape jumps out of the bedroom and grabs her, 
               hands around her neck.

               Laurie SCREAMS. She twists and squirms and claws at him, 
               her finger ripping at his mask. She pulls it off over his 
               face, wriggles out of his grip and turns around.

               CLOSE SHOT -- MICHAEL

               The shape, Michael, stares at her with his one eye. He has 
               a dank, white face with blond hair. There is something 
               completely unhuman about his features, the open mouth, the 
               dark staring eye.

               ANGLE IN HALL

               Michael lunges at her again.

               Suddenly there is a THUNDERING EXPLOSION and Michael is 
               blown off his feet. Laurie falls back against the wall.

               ANGLE ON LOOMIS

               Standing at the top of the stairs is Loomis, gun in his 
               hand. He moves forward down the hall.

               ANGLE IN HALL

               Michael slowly gets to his feet, still refusing to die.

               Loomis stops and takes aim. BLAM! BLAM! BLAM!

               Michael is hit three times, each bullet throwing him 
               backward further down the hall until he hits the window at 
               the end and SMASHES through it.

               EXT. DOYLE HOUSE -- UP ANGLE

               Michael falls from the second story right down into CAMERA 
               with a CRASH!  

               ANGLE IN HALL

               Loomis rushes to Laurie and bends down beside her. For a 
               moment she just cries in his arms, sobbing hysterically.

               Then she looks up at him with a glazed, wild expression.  

                                     LAURIE
                         It was the Boogeyman...

               Loomis looks down at her, then up at the shattered window 
               at the end of the hall.

                                     LOOMIS
                         As a matter of fact it was.

               He walks slowly down to the window and peers out.

               LOOMIS' POV -- BACKYARD

               He looks down at the spot where Michael should be, but 
               there is nothing there, just a trampled patch in the grass.

               ANGLE ON LOOMIS

               He stares down with a growing fear, then looks out from 
               the house.

               LOOMIS' POV

               The backyard, the neighboring yards, the street, all are 
               empty, quiet, dark. There is only the SOUND of the wind 
               swelling in the trees.

               Michael is gone.

               FADE TO BLACK.

               ROLL END TITLES.

                                        THE END
